begin;

set local statement_timeout = '120s';

lock table public.vendsoft_food_sales_imports in access exclusive mode;

create table if not exists public.vendsoft_food_archive_manifests (
  id bigint generated by default as identity primary key,
  archived_before timestamptz not null,
  archived_rows bigint not null,
  archived_quantity numeric not null,
  archived_revenue_czk numeric not null,
  first_event_at timestamptz,
  last_event_at timestamptz,
  telemetry_rows_verified bigint not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.vendsoft_food_archive_manifests enable row level security;
drop policy if exists "Allow read VendSoft archive manifests" on public.vendsoft_food_archive_manifests;
create policy "Allow read VendSoft archive manifests"
on public.vendsoft_food_archive_manifests
for select to authenticated using (true);

insert into public.vendsoft_food_archive_manifests (
  archived_before,
  archived_rows,
  archived_quantity,
  archived_revenue_czk,
  first_event_at,
  last_event_at,
  telemetry_rows_verified,
  note
)
select
  timestamp with time zone '2026-07-25 00:00:00+02',
  count(*),
  coalesce(sum(imported.quantity), 0),
  coalesce(sum(coalesce(imported.total_amount_czk, imported.unit_price_czk * imported.quantity, 0)), 0),
  min(imported.source_event_at),
  max(imported.source_event_at),
  count(*) filter (where exists (
    select 1
    from public.telemetry_sales_events event
    where event.provider = 'VendSoft'
      and event.source_event_key = imported.event_key
  )),
  'Duplicitní pomocná evidence odstraněna po ověření 1:1 proti telemetry_sales_events. Detail pro reporty a predikce zůstává v telemetry_sales_events.'
from public.vendsoft_food_sales_imports imported
where imported.source_event_at < timestamp with time zone '2026-07-25 00:00:00+02';

do $$
declare
  archived_count bigint;
  verified_count bigint;
begin
  select archived_rows, telemetry_rows_verified
  into archived_count, verified_count
  from public.vendsoft_food_archive_manifests
  order by id desc
  limit 1;

  if archived_count <> verified_count then
    raise exception 'VendSoft archive verification failed: % rows, % verified.', archived_count, verified_count;
  end if;
end;
$$;

create table public.vendsoft_food_sales_imports_recent
(like public.vendsoft_food_sales_imports including all);

insert into public.vendsoft_food_sales_imports_recent
select *
from public.vendsoft_food_sales_imports
where source_event_at >= timestamp with time zone '2026-07-25 00:00:00+02';

drop table public.vendsoft_food_sales_imports;
alter table public.vendsoft_food_sales_imports_recent rename to vendsoft_food_sales_imports;

select setval(
  pg_get_serial_sequence('public.vendsoft_food_sales_imports', 'id'),
  coalesce((select max(id) from public.vendsoft_food_sales_imports), 1),
  true
);

alter table public.vendsoft_food_sales_imports enable row level security;
drop policy if exists "Allow read VendSoft food sales imports" on public.vendsoft_food_sales_imports;
create policy "Allow read VendSoft food sales imports"
on public.vendsoft_food_sales_imports
for select to authenticated using (true);

commit;
