create table if not exists public.employee_location_logs (
  id bigint generated by default as identity primary key,
  attendance_day_id bigint references public.attendance_days (id) on delete cascade,
  employee_id uuid not null references public.employees (id) on delete cascade,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  source_type text not null default 'manual'
    check (source_type in ('shift_start', 'manual', 'movement', 'heartbeat', 'shift_end')),
  event_at timestamp with time zone not null default now(),
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  accuracy_m numeric(8, 2),
  heading_deg numeric(7, 2),
  speed_kmh numeric(8, 2),
  note text,
  created_at timestamp with time zone not null default now()
);

create index if not exists employee_location_logs_employee_idx
  on public.employee_location_logs (employee_id, event_at desc);

create index if not exists employee_location_logs_day_idx
  on public.employee_location_logs (attendance_day_id, event_at desc);

create index if not exists employee_location_logs_vehicle_idx
  on public.employee_location_logs (vehicle_id, event_at desc);

alter table public.employee_location_logs enable row level security;

create policy "Allow read employee location logs"
on public.employee_location_logs
for select
to authenticated, anon
using (true);

create policy "Allow insert employee location logs"
on public.employee_location_logs
for insert
to authenticated, anon
with check (true);

create policy "Allow update employee location logs"
on public.employee_location_logs
for update
to authenticated, anon
using (true)
with check (true);
