alter table public.employees
  add column if not exists employment_type text
  check (employment_type in ('hpp', 'dpp', 'dpc', 'external'));

alter table public.employees
  add column if not exists contracted_weekly_hours numeric(6,2);

alter table public.employees
  add column if not exists annual_hours_limit numeric(8,2);

alter table public.employees
  add column if not exists employment_start_date date;

alter table public.employees
  add column if not exists employment_end_date date;

alter table public.employees
  add column if not exists attendance_profile_id bigint;

create table if not exists public.attendance_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  requires_warehouse boolean not null default false,
  requires_vehicle boolean not null default false,
  earliest_payable_start time,
  early_start_mode text not null default 'allow'
    check (early_start_mode in ('allow', 'shift_to_end', 'needs_approval', 'forbid')),
  home_start_mode text not null default 'needs_approval'
    check (home_start_mode in ('allow', 'needs_approval', 'forbid')),
  max_shift_hours_without_review numeric(6,2),
  auto_close_enabled boolean not null default true,
  break_required boolean not null default false,
  break_after_hours numeric(6,2),
  approval_required_for_exceptions boolean not null default true,
  note text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists attendance_profiles_code_unique
  on public.attendance_profiles (code)
  where code is not null;

alter table public.employees
  add constraint employees_attendance_profile_fk
  foreign key (attendance_profile_id)
  references public.attendance_profiles (id)
  on delete set null;

create table if not exists public.attendance_days (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees (id) on delete cascade,
  attendance_profile_id bigint references public.attendance_profiles (id) on delete set null,
  attendance_date date not null,
  day_type text not null default 'work'
    check (day_type in ('work', 'vacation', 'sick', 'business_trip', 'off')),
  status text not null default 'open'
    check (status in ('open', 'closed', 'auto_closed', 'needs_review', 'approved', 'rejected')),
  start_location_type text not null default 'warehouse'
    check (start_location_type in ('warehouse', 'home')),
  start_warehouse_id bigint references public.warehouses (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  payable_start timestamp with time zone,
  payable_end timestamp with time zone,
  payable_minutes integer not null default 0,
  break_minutes integer not null default 0,
  adjustment_minutes integer not null default 0,
  adjustment_reason text,
  requires_approval boolean not null default false,
  approval_status text not null default 'not_required'
    check (approval_status in ('not_required', 'pending', 'approved', 'rejected')),
  approval_reason text,
  approved_by uuid,
  approved_at timestamp with time zone,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (employee_id, attendance_date)
);

create index if not exists attendance_days_employee_idx
  on public.attendance_days (employee_id, attendance_date desc);

create index if not exists attendance_days_status_idx
  on public.attendance_days (status, approval_status);

create index if not exists attendance_days_vehicle_idx
  on public.attendance_days (vehicle_id);

create table if not exists public.attendance_events (
  id bigint generated by default as identity primary key,
  attendance_day_id bigint not null references public.attendance_days (id) on delete cascade,
  employee_id uuid not null references public.employees (id) on delete cascade,
  event_type text not null
    check (event_type in ('shift_start', 'break_start', 'break_end', 'shift_end', 'manual_adjustment', 'approval')),
  event_time timestamp with time zone not null default now(),
  note text,
  created_by uuid,
  created_at timestamp with time zone not null default now()
);

create index if not exists attendance_events_day_idx
  on public.attendance_events (attendance_day_id, event_time asc);

create index if not exists attendance_events_employee_idx
  on public.attendance_events (employee_id, event_time desc);

create or replace function public.set_attendance_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_profiles_updated_at on public.attendance_profiles;

create trigger trg_attendance_profiles_updated_at
before update on public.attendance_profiles
for each row
execute function public.set_attendance_profiles_updated_at();

create or replace function public.set_attendance_days_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_days_updated_at on public.attendance_days;

create trigger trg_attendance_days_updated_at
before update on public.attendance_days
for each row
execute function public.set_attendance_days_updated_at();

alter table public.attendance_profiles enable row level security;
alter table public.attendance_days enable row level security;
alter table public.attendance_events enable row level security;

create policy "Allow read attendance profiles"
on public.attendance_profiles
for select
to authenticated, anon
using (true);

create policy "Allow insert attendance profiles"
on public.attendance_profiles
for insert
to authenticated, anon
with check (true);

create policy "Allow update attendance profiles"
on public.attendance_profiles
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read attendance days"
on public.attendance_days
for select
to authenticated, anon
using (true);

create policy "Allow insert attendance days"
on public.attendance_days
for insert
to authenticated, anon
with check (true);

create policy "Allow update attendance days"
on public.attendance_days
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read attendance events"
on public.attendance_events
for select
to authenticated, anon
using (true);

create policy "Allow insert attendance events"
on public.attendance_events
for insert
to authenticated, anon
with check (true);

create policy "Allow update attendance events"
on public.attendance_events
for update
to authenticated, anon
using (true)
with check (true);

insert into public.attendance_profiles (
  name,
  code,
  requires_warehouse,
  requires_vehicle,
  earliest_payable_start,
  early_start_mode,
  home_start_mode,
  max_shift_hours_without_review,
  auto_close_enabled,
  break_required,
  break_after_hours,
  approval_required_for_exceptions,
  note,
  active
)
values
  (
    'Operátor flex',
    'operator_flex',
    true,
    true,
    '06:00',
    'shift_to_end',
    'needs_approval',
    12,
    true,
    true,
    6,
    true,
    'Operátor musí vždy vybrat místo zahájení a vozidlo. Start z domova i výjimky jdou do schválení.',
    true
  ),
  (
    'Technik servis',
    'technician_service',
    true,
    true,
    '06:00',
    'shift_to_end',
    'needs_approval',
    12,
    true,
    true,
    6,
    true,
    'Technik má provozní režim podobný operátorovi, ale navazuje na servisní workflow.',
    true
  ),
  (
    'Administrativa',
    'administration',
    false,
    false,
    '06:00',
    'allow',
    'allow',
    12,
    true,
    false,
    null,
    false,
    'Kancelářský režim bez povinného skladu a vozidla.',
    true
  )
on conflict (code) do nothing;
