create table if not exists public.budget_scenarios (
  id bigint generated by default as identity primary key,
  month_date date not null,
  title text not null,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'locked')),
  forecast_method text not null default 'run_rate'
    check (forecast_method in ('run_rate', 'actual_plus_plan')),
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists budget_scenarios_month_title_idx
  on public.budget_scenarios (month_date, lower(title));

create index if not exists budget_scenarios_month_idx
  on public.budget_scenarios (month_date desc);

create table if not exists public.budget_lines (
  id bigint generated by default as identity primary key,
  scenario_id bigint not null references public.budget_scenarios (id) on delete cascade,
  category_key text not null,
  label text not null,
  line_type text not null
    check (line_type in ('income', 'cost')),
  data_source text not null
    check (data_source in (
      'sales_documents',
      'stock_movements_v13',
      'purchase_orders',
      'vehicle_operation_logs',
      'vehicle_expenses',
      'service_requests',
      'manual'
    )),
  target_amount numeric(14,2) not null default 0,
  note text,
  sort_order integer not null default 100,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (scenario_id, category_key)
);

create index if not exists budget_lines_scenario_idx
  on public.budget_lines (scenario_id, sort_order);

create or replace function public.set_budget_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_budget_scenarios_updated_at on public.budget_scenarios;
create trigger trg_budget_scenarios_updated_at
before update on public.budget_scenarios
for each row
execute function public.set_budget_updated_at();

drop trigger if exists trg_budget_lines_updated_at on public.budget_lines;
create trigger trg_budget_lines_updated_at
before update on public.budget_lines
for each row
execute function public.set_budget_updated_at();

alter table public.budget_scenarios enable row level security;
alter table public.budget_lines enable row level security;

drop policy if exists "Allow read budget scenarios" on public.budget_scenarios;
create policy "Allow read budget scenarios"
on public.budget_scenarios
for select
using (true);

drop policy if exists "Allow insert budget scenarios" on public.budget_scenarios;
create policy "Allow insert budget scenarios"
on public.budget_scenarios
for insert
with check (true);

drop policy if exists "Allow update budget scenarios" on public.budget_scenarios;
create policy "Allow update budget scenarios"
on public.budget_scenarios
for update
using (true)
with check (true);

drop policy if exists "Allow delete budget scenarios" on public.budget_scenarios;
create policy "Allow delete budget scenarios"
on public.budget_scenarios
for delete
using (true);

drop policy if exists "Allow read budget lines" on public.budget_lines;
create policy "Allow read budget lines"
on public.budget_lines
for select
using (true);

drop policy if exists "Allow insert budget lines" on public.budget_lines;
create policy "Allow insert budget lines"
on public.budget_lines
for insert
with check (true);

drop policy if exists "Allow update budget lines" on public.budget_lines;
create policy "Allow update budget lines"
on public.budget_lines
for update
using (true)
with check (true);

drop policy if exists "Allow delete budget lines" on public.budget_lines;
create policy "Allow delete budget lines"
on public.budget_lines
for delete
using (true);
