create table if not exists public.budget_expense_entries (
  id bigint generated by default as identity primary key,
  expense_date date not null default current_date,
  category_key text not null,
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  vat_mode text not null default 'without_vat'
    check (vat_mode in ('without_vat', 'with_vat')),
  source text not null default 'manual'
    check (source in ('manual', 'recurring', 'import')),
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists budget_expense_entries_date_idx
  on public.budget_expense_entries (expense_date desc);

create index if not exists budget_expense_entries_category_date_idx
  on public.budget_expense_entries (category_key, expense_date desc);

create or replace function public.set_budget_expense_entries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_budget_expense_entries_updated_at on public.budget_expense_entries;
create trigger trg_budget_expense_entries_updated_at
before update on public.budget_expense_entries
for each row
execute function public.set_budget_expense_entries_updated_at();

alter table public.budget_expense_entries enable row level security;

drop policy if exists "Allow read budget expense entries" on public.budget_expense_entries;
create policy "Allow read budget expense entries"
on public.budget_expense_entries
for select
using (true);

drop policy if exists "Allow insert budget expense entries" on public.budget_expense_entries;
create policy "Allow insert budget expense entries"
on public.budget_expense_entries
for insert
with check (true);

drop policy if exists "Allow update budget expense entries" on public.budget_expense_entries;
create policy "Allow update budget expense entries"
on public.budget_expense_entries
for update
using (true)
with check (true);

drop policy if exists "Allow delete budget expense entries" on public.budget_expense_entries;
create policy "Allow delete budget expense entries"
on public.budget_expense_entries
for delete
using (true);
