create table if not exists public.business_contacts (
  id bigint generated by default as identity primary key,
  contact_type text not null default 'customer'
    check (contact_type in ('customer', 'supplier', 'both')),
  name text not null,
  name_norm text not null,
  company_id text,
  tax_id text,
  contact_name text,
  email text,
  phone text,
  billing_address text,
  delivery_address text,
  default_due_days integer,
  note text,
  active boolean not null default true,
  source text,
  purchase_supplier_id bigint references public.purchase_suppliers (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (contact_type, name_norm)
);

create index if not exists business_contacts_name_idx
  on public.business_contacts (name_norm);

create index if not exists business_contacts_type_idx
  on public.business_contacts (contact_type);

create index if not exists business_contacts_purchase_supplier_idx
  on public.business_contacts (purchase_supplier_id);

alter table public.purchase_suppliers
  add column if not exists company_id text,
  add column if not exists tax_id text,
  add column if not exists address text,
  add column if not exists bank_account text,
  add column if not exists bank_code text,
  add column if not exists iban text,
  add column if not exists default_due_days integer;

create or replace function public.olvend_contact_norm(value text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(
    translate(trim(coalesce(value, '')),
      'ÁÄČÇĎÉĚËÍŇÓÖŘŠŤÚŮÜÝŽáäčçďéěëíňóöřšťúůüýž',
      'AACCDEEEINOORSTUUUYZaaccdeeeinoorstuuuyz'
    ),
    '\s+', ' ', 'g'
  ));
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_business_contacts_updated_at on public.business_contacts;
create trigger trg_business_contacts_updated_at
before update on public.business_contacts
for each row
execute function public.set_updated_at();

alter table public.business_contacts enable row level security;

drop policy if exists "Allow read business contacts" on public.business_contacts;
create policy "Allow read business contacts"
on public.business_contacts
for select
using (true);

drop policy if exists "Allow insert business contacts" on public.business_contacts;
create policy "Allow insert business contacts"
on public.business_contacts
for insert
with check (true);

drop policy if exists "Allow update business contacts" on public.business_contacts;
create policy "Allow update business contacts"
on public.business_contacts
for update
using (true)
with check (true);

insert into public.business_contacts (
  contact_type,
  name,
  name_norm,
  company_id,
  tax_id,
  contact_name,
  email,
  phone,
  billing_address,
  default_due_days,
  note,
  active,
  source,
  purchase_supplier_id
)
select
  'supplier',
  ps.name,
  public.olvend_contact_norm(ps.name),
  ps.company_id,
  ps.tax_id,
  ps.contact_name,
  ps.email,
  ps.phone,
  ps.address,
  ps.default_due_days,
  ps.note,
  ps.active,
  'purchase_suppliers',
  ps.id
from public.purchase_suppliers ps
where trim(coalesce(ps.name, '')) <> ''
on conflict (contact_type, name_norm)
do update set
  name = excluded.name,
  company_id = coalesce(excluded.company_id, public.business_contacts.company_id),
  tax_id = coalesce(excluded.tax_id, public.business_contacts.tax_id),
  contact_name = coalesce(excluded.contact_name, public.business_contacts.contact_name),
  email = coalesce(excluded.email, public.business_contacts.email),
  phone = coalesce(excluded.phone, public.business_contacts.phone),
  billing_address = coalesce(excluded.billing_address, public.business_contacts.billing_address),
  default_due_days = coalesce(excluded.default_due_days, public.business_contacts.default_due_days),
  note = coalesce(excluded.note, public.business_contacts.note),
  active = excluded.active,
  source = excluded.source,
  purchase_supplier_id = excluded.purchase_supplier_id;

insert into public.business_contacts (
  contact_type,
  name,
  name_norm,
  active,
  source
)
select
  'customer',
  trim(sd.customer_name),
  public.olvend_contact_norm(sd.customer_name),
  true,
  'sales_documents'
from public.sales_documents sd
where trim(coalesce(sd.customer_name, '')) <> ''
group by trim(sd.customer_name), public.olvend_contact_norm(sd.customer_name)
on conflict (contact_type, name_norm)
do update set
  name = excluded.name,
  active = true;
