begin;

create table if not exists public.customer_accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  strategic_tier text not null default 'B'
    check (strategic_tier in ('A', 'B', 'C')),
  account_manager_id uuid null references public.employees(id) on delete set null,
  active boolean not null default true,
  note text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.locations
  add column if not exists location_priority text,
  add column if not exists recommended_priority text,
  add column if not exists priority_reviewed_at date,
  add column if not exists priority_note text,
  add column if not exists customer_account_id bigint null references public.customer_accounts(id) on delete set null,
  add column if not exists control_tier text not null default 'B'
    check (control_tier in ('A', 'B', 'C')),
  add column if not exists control_interval_days integer not null default 60,
  add column if not exists control_region text null,
  add column if not exists control_owner_employee_id uuid null references public.employees(id) on delete set null,
  add column if not exists last_control_visit_at timestamptz null,
  add column if not exists next_control_due_at date null,
  add column if not exists control_priority_note text null,
  add column if not exists control_tier_source text not null default 'manual'
    check (control_tier_source in ('manual', 'account_inherited', 'telemetry_recommended')),
  add column if not exists control_tier_recommended text null
    check (control_tier_recommended in ('A', 'B', 'C')),
  add column if not exists control_tier_recalculated_at timestamptz null;

alter table public.locations
  drop constraint if exists locations_location_priority_check;

alter table public.locations
  add constraint locations_location_priority_check
  check (location_priority in ('A', 'B', 'C') or location_priority is null);

alter table public.locations
  drop constraint if exists locations_recommended_priority_check;

alter table public.locations
  add constraint locations_recommended_priority_check
  check (recommended_priority in ('A', 'B', 'C', 'review') or recommended_priority is null);

create table if not exists public.control_campaigns (
  id bigint generated by default as identity primary key,
  customer_account_id bigint null references public.customer_accounts(id) on delete set null,
  name text not null,
  status text not null default 'draft'
    check (status in ('draft', 'active', 'paused', 'done', 'cancelled')),
  goal_kind text not null default 'full_coverage'
    check (goal_kind in ('full_coverage', 'sample_coverage', 'risk_focus')),
  target_coverage_percent integer not null default 100
    check (target_coverage_percent between 1 and 100),
  date_from date not null default current_date,
  date_to date not null default (current_date + interval '90 days')::date,
  required_region_lock boolean not null default true,
  note text null,
  created_by uuid null references public.employees(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.control_campaign_locations (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.control_campaigns(id) on delete cascade,
  location_id bigint not null references public.locations(id) on delete cascade,
  status text not null default 'planned'
    check (status in ('planned', 'in_route', 'visited', 'skipped', 'cancelled')),
  planned_visit_date date null,
  route_plan_id bigint null references public.route_plans(id) on delete set null,
  control_visit_id bigint null,
  note text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (campaign_id, location_id)
);

create table if not exists public.control_visits (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  customer_account_id bigint null references public.customer_accounts(id) on delete set null,
  campaign_id bigint null references public.control_campaigns(id) on delete set null,
  route_plan_id bigint null references public.route_plans(id) on delete set null,
  route_plan_stop_id bigint null references public.route_plan_stops(id) on delete set null,
  planned_date date not null default current_date,
  assigned_employee_id uuid null references public.employees(id) on delete set null,
  operator_employee_id uuid null references public.employees(id) on delete set null,
  status text not null default 'planned'
    check (status in ('planned', 'in_progress', 'done', 'skipped', 'cancelled')),
  result text null
    check (result in ('ok', 'minor_issue', 'operator_action', 'customer_followup', 'service_required')),
  customer_contact_status text null
    check (customer_contact_status in ('contacted', 'not_available', 'not_required')),
  customer_sentiment text null
    check (customer_sentiment in ('satisfied', 'mostly_satisfied', 'not_satisfied')),
  score integer null check (score between 0 and 100),
  started_at timestamptz null,
  completed_at timestamptz null,
  note text null,
  created_by uuid null references public.employees(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.control_campaign_locations
  drop constraint if exists control_campaign_locations_visit_fk;

alter table public.control_campaign_locations
  add constraint control_campaign_locations_visit_fk
  foreign key (control_visit_id) references public.control_visits(id) on delete set null;

create table if not exists public.control_visit_items (
  id bigint generated by default as identity primary key,
  control_visit_id bigint not null references public.control_visits(id) on delete cascade,
  section_key text not null,
  item_key text not null,
  label text not null,
  answer text null
    check (answer in ('ok', 'minor_issue', 'issue', 'not_applicable')),
  requires_note boolean not null default false,
  note text null,
  sort_order integer not null default 1,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.route_plan_stops
  add column if not exists control_visit_id bigint null references public.control_visits(id) on delete set null;

alter table public.route_plan_stops
  drop constraint if exists route_plan_stops_stop_kind_check;

alter table public.route_plan_stops
  add constraint route_plan_stops_stop_kind_check
  check (stop_kind in ('service_request', 'location_check', 'restock', 'manual', 'control_visit'));

create index if not exists customer_accounts_name_idx on public.customer_accounts(name);
create index if not exists customer_accounts_tier_idx on public.customer_accounts(strategic_tier);
create index if not exists locations_control_region_idx on public.locations(control_region);
create index if not exists locations_control_tier_idx on public.locations(control_tier);
create index if not exists locations_next_control_due_idx on public.locations(next_control_due_at);
create index if not exists control_campaigns_status_idx on public.control_campaigns(status);
create index if not exists control_campaign_locations_campaign_idx on public.control_campaign_locations(campaign_id, status);
create index if not exists control_campaign_locations_location_idx on public.control_campaign_locations(location_id);
create index if not exists control_visits_planned_date_idx on public.control_visits(planned_date);
create index if not exists control_visits_location_idx on public.control_visits(location_id);
create index if not exists control_visits_route_idx on public.control_visits(route_plan_id);
create index if not exists control_visit_items_visit_idx on public.control_visit_items(control_visit_id, sort_order);

create or replace function public.touch_control_routes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_customer_accounts_updated_at on public.customer_accounts;
create trigger trg_customer_accounts_updated_at
before update on public.customer_accounts
for each row
execute function public.touch_control_routes_updated_at();

drop trigger if exists trg_control_campaigns_updated_at on public.control_campaigns;
create trigger trg_control_campaigns_updated_at
before update on public.control_campaigns
for each row
execute function public.touch_control_routes_updated_at();

drop trigger if exists trg_control_campaign_locations_updated_at on public.control_campaign_locations;
create trigger trg_control_campaign_locations_updated_at
before update on public.control_campaign_locations
for each row
execute function public.touch_control_routes_updated_at();

drop trigger if exists trg_control_visits_updated_at on public.control_visits;
create trigger trg_control_visits_updated_at
before update on public.control_visits
for each row
execute function public.touch_control_routes_updated_at();

alter table public.customer_accounts enable row level security;
alter table public.control_campaigns enable row level security;
alter table public.control_campaign_locations enable row level security;
alter table public.control_visits enable row level security;
alter table public.control_visit_items enable row level security;

drop policy if exists "Allow read customer accounts" on public.customer_accounts;
create policy "Allow read customer accounts" on public.customer_accounts
for select to authenticated, anon using (true);

drop policy if exists "Allow write customer accounts" on public.customer_accounts;
create policy "Allow write customer accounts" on public.customer_accounts
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read control campaigns" on public.control_campaigns;
create policy "Allow read control campaigns" on public.control_campaigns
for select to authenticated, anon using (true);

drop policy if exists "Allow write control campaigns" on public.control_campaigns;
create policy "Allow write control campaigns" on public.control_campaigns
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read control campaign locations" on public.control_campaign_locations;
create policy "Allow read control campaign locations" on public.control_campaign_locations
for select to authenticated, anon using (true);

drop policy if exists "Allow write control campaign locations" on public.control_campaign_locations;
create policy "Allow write control campaign locations" on public.control_campaign_locations
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read control visits" on public.control_visits;
create policy "Allow read control visits" on public.control_visits
for select to authenticated, anon using (true);

drop policy if exists "Allow write control visits" on public.control_visits;
create policy "Allow write control visits" on public.control_visits
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read control visit items" on public.control_visit_items;
create policy "Allow read control visit items" on public.control_visit_items
for select to authenticated, anon using (true);

drop policy if exists "Allow write control visit items" on public.control_visit_items;
create policy "Allow write control visit items" on public.control_visit_items
for all to authenticated, anon using (true) with check (true);

comment on table public.customer_accounts is 'Obchodni zakaznicke accounty. Velky account muze mit mnoho provozoven.';
comment on column public.locations.control_tier is 'Kontrolni priorita konkretni provozovny. Muze dedit account, ale rozhoduje o planovani navstev.';
comment on table public.control_campaigns is 'Plosne kontrolni kampane pro strategicke zakazniky nebo tematicke kontroly.';
comment on table public.control_visits is 'Planovane a provedene kontrolni navstevy v ramci tras kontrolora.';

commit;
