begin;

lock table public.machine_coffee_containers in share row exclusive mode;

create table if not exists public.machine_cup_capacity_corrections (
  id bigint generated by default as identity primary key,
  correction_key text not null unique,
  container_id bigint not null references public.machine_coffee_containers (id) on delete cascade,
  machine_id bigint not null references public.machines (id) on delete cascade,
  product_sku text not null,
  old_capacity_quantity numeric(12,3),
  new_capacity_quantity numeric(12,3) not null,
  old_current_quantity numeric(12,3),
  new_current_quantity numeric(12,3) not null,
  corrected_at timestamptz not null default now(),
  note text
);

alter table public.machine_cup_capacity_corrections enable row level security;

comment on table public.machine_cup_capacity_corrections is
  'Audit puvodnich a prepocitanych stavu kelimkovych zasobniku pri oprave fyzickych kapacit.';

create temporary table cup_capacity_v23_scope on commit drop as
select
  cc.id as container_id,
  cc.machine_id,
  cc.product_sku,
  cc.capacity_quantity as old_capacity_quantity,
  target.new_capacity_quantity,
  cc.current_quantity as old_current_quantity,
  greatest(
    0::numeric,
    least(
      target.new_capacity_quantity,
      target.new_capacity_quantity
        - greatest(
            0::numeric,
            coalesce(cc.capacity_quantity, target.new_capacity_quantity)
              - coalesce(cc.current_quantity, 0)
          )
    )
  ) as new_current_quantity
from public.machine_coffee_containers cc
join public.machines m on m.id = cc.machine_id
cross join lateral (
  select case
    when lower(concat_ws(' ', m.name, m.model)) ~ '(luce|luxe).*x2'
      and cc.product_sku = '45' then 300::numeric
    when lower(concat_ws(' ', m.name, m.model)) ~ '(luce|luxe).*x2'
      and cc.product_sku = '53' then 250::numeric
    when lower(concat_ws(' ', m.name, m.model)) ~ 'rh\s*fs1|rhfs1'
      and cc.product_sku = '255' then 250::numeric
    else null
  end as new_capacity_quantity
) target
where target.new_capacity_quantity is not null;

do $$
declare
  v_scope_count integer;
begin
  select count(*) into v_scope_count from cup_capacity_v23_scope;
  if v_scope_count <> 60 then
    raise exception 'Cup capacity correction expected 60 containers, found %.', v_scope_count;
  end if;
end;
$$;

insert into public.machine_cup_capacity_corrections (
  correction_key,
  container_id,
  machine_id,
  product_sku,
  old_capacity_quantity,
  new_capacity_quantity,
  old_current_quantity,
  new_current_quantity,
  note
)
select
  'cup-capacity-v23-' || scope.container_id,
  scope.container_id,
  scope.machine_id,
  scope.product_sku,
  scope.old_capacity_quantity,
  scope.new_capacity_quantity,
  scope.old_current_quantity,
  scope.new_current_quantity,
  '2026-08-02: fyzicka kapacita Luce X2 180 ml = 300 ks, velky kelimek SKU 53 = 250 ks; RHFS1 250 ml = 250 ks. Zustatek zachovava dosavadni ubytek od plneho zasobniku.'
from cup_capacity_v23_scope scope
on conflict (correction_key) do nothing;

update public.machine_coffee_containers cc
set
  capacity_quantity = scope.new_capacity_quantity,
  current_quantity = scope.new_current_quantity,
  note = concat_ws(
    ' · ',
    nullif(btrim(cc.note), ''),
    'Kapacita opravena 2. 8. 2026; zustatek prepocitan zachovanim dosavadniho ubytku.'
  )
from cup_capacity_v23_scope scope
where cc.id = scope.container_id
  and (
    cc.capacity_quantity is distinct from scope.new_capacity_quantity
    or cc.current_quantity is distinct from scope.new_current_quantity
  );

do $$
declare
  v_invalid_count integer;
begin
  select count(*)
  into v_invalid_count
  from cup_capacity_v23_scope scope
  join public.machine_coffee_containers cc on cc.id = scope.container_id
  where cc.capacity_quantity is distinct from scope.new_capacity_quantity
     or cc.current_quantity is distinct from scope.new_current_quantity
     or cc.current_quantity < 0
     or cc.current_quantity > cc.capacity_quantity;

  if v_invalid_count <> 0 then
    raise exception 'Cup capacity correction left % invalid containers.', v_invalid_count;
  end if;
end;
$$;

commit;

select
  case
    when lower(concat_ws(' ', m.name, m.model)) ~ 'rh\s*fs1|rhfs1' then 'RHFS1'
    else 'LUCE_X2'
  end as machine_family,
  cc.product_sku,
  min(cc.product_name) as product_name,
  count(*) as container_count,
  min(cc.capacity_quantity) as min_capacity,
  max(cc.capacity_quantity) as max_capacity,
  sum(cc.current_quantity) as current_total,
  count(*) filter (where cc.current_quantity < 0 or cc.current_quantity > cc.capacity_quantity) as invalid_balances
from public.machine_coffee_containers cc
join public.machines m on m.id = cc.machine_id
where (
    lower(concat_ws(' ', m.name, m.model)) ~ '(luce|luxe).*x2'
    and cc.product_sku in ('45', '53')
  ) or (
    lower(concat_ws(' ', m.name, m.model)) ~ 'rh\s*fs1|rhfs1'
    and cc.product_sku = '255'
  )
group by 1, cc.product_sku
order by 1, cc.product_sku;
