begin;

create table if not exists public.mail_accounts (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees(id) on delete cascade,
  email_address text not null,
  display_name text,
  username text not null,
  password_ciphertext text not null,
  imap_host text not null default 'imap.mail.webnode.com',
  imap_port integer not null default 993,
  imap_secure boolean not null default true,
  smtp_host text not null default 'smtp.mail.webnode.com',
  smtp_port integer not null default 465,
  smtp_secure boolean not null default true,
  sync_history_days integer not null default 90,
  sync_folders boolean not null default true,
  sync_deletions boolean not null default true,
  download_attachments boolean not null default false,
  last_sync_at timestamptz,
  last_error text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(employee_id, email_address)
);

create table if not exists public.mail_signatures (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees(id) on delete cascade,
  name text not null,
  html_content text not null default '',
  is_default_new boolean not null default false,
  is_default_reply boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mail_message_index (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.mail_accounts(id) on delete cascade,
  employee_id uuid not null references public.employees(id) on delete cascade,
  folder_path text not null,
  uid bigint not null,
  message_id text,
  subject text,
  sender_name text,
  sender_address text,
  recipients jsonb not null default '[]'::jsonb,
  sent_at timestamptz,
  received_at timestamptz,
  preview_text text,
  is_read boolean not null default false,
  is_flagged boolean not null default false,
  has_attachments boolean not null default false,
  size_bytes bigint,
  linked_entity_type text,
  linked_entity_id text,
  synced_at timestamptz not null default now(),
  unique(account_id, folder_path, uid)
);

create index if not exists mail_message_owner_received_idx
  on public.mail_message_index(employee_id, received_at desc);

create or replace function public.is_mail_owner(target_employee_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.employees
    where id = target_employee_id and auth_user_id = auth.uid() and active is not false
  );
$$;
revoke all on function public.is_mail_owner(uuid) from public;
grant execute on function public.is_mail_owner(uuid) to authenticated;

alter table public.mail_accounts enable row level security;
alter table public.mail_signatures enable row level security;
alter table public.mail_message_index enable row level security;

drop policy if exists "Mail accounts are private" on public.mail_accounts;
revoke all on public.mail_accounts from authenticated, anon;

drop policy if exists "Mail signatures are private" on public.mail_signatures;
create policy "Mail signatures are private" on public.mail_signatures for all to authenticated
  using (public.is_mail_owner(employee_id)) with check (public.is_mail_owner(employee_id));

drop policy if exists "Mail index is private" on public.mail_message_index;
create policy "Mail index is private" on public.mail_message_index for select to authenticated
  using (public.is_mail_owner(employee_id));

create or replace view public.mail_accounts_safe
with (security_invoker=true) as
select id, employee_id, email_address, display_name, username,
       imap_host, imap_port, imap_secure, smtp_host, smtp_port, smtp_secure,
       sync_history_days, sync_folders, sync_deletions, download_attachments,
       last_sync_at, last_error, active, created_at, updated_at
from public.mail_accounts;

revoke all on public.mail_accounts_safe from authenticated, anon;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('mail-signature-assets', 'mail-signature-assets', false, 5242880, array['image/png','image/jpeg','image/gif','image/webp'])
on conflict (id) do nothing;

drop policy if exists "Private signature images read" on storage.objects;
create policy "Private signature images read" on storage.objects for select to authenticated
using (
  bucket_id = 'mail-signature-assets' and exists(
    select 1 from public.employees e
    where e.auth_user_id = auth.uid() and e.id::text = (storage.foldername(name))[1]
  )
);
drop policy if exists "Private signature images insert" on storage.objects;
create policy "Private signature images insert" on storage.objects for insert to authenticated
with check (
  bucket_id = 'mail-signature-assets' and exists(
    select 1 from public.employees e
    where e.auth_user_id = auth.uid() and e.id::text = (storage.foldername(name))[1]
  )
);
drop policy if exists "Private signature images update" on storage.objects;
create policy "Private signature images update" on storage.objects for update to authenticated
using (
  bucket_id = 'mail-signature-assets' and exists(
    select 1 from public.employees e
    where e.auth_user_id = auth.uid() and e.id::text = (storage.foldername(name))[1]
  )
) with check (
  bucket_id = 'mail-signature-assets' and exists(
    select 1 from public.employees e
    where e.auth_user_id = auth.uid() and e.id::text = (storage.foldername(name))[1]
  )
);
drop policy if exists "Private signature images delete" on storage.objects;
create policy "Private signature images delete" on storage.objects for delete to authenticated
using (
  bucket_id = 'mail-signature-assets' and exists(
    select 1 from public.employees e
    where e.auth_user_id = auth.uid() and e.id::text = (storage.foldername(name))[1]
  )
);

commit;
