create table if not exists public.notification_preferences (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete cascade,
  email_enabled boolean not null default true,
  notify_instructions boolean not null default true,
  notify_tasks boolean not null default true,
  notify_service boolean not null default true,
  digest_enabled boolean not null default false,
  digest_hour integer not null default 7
    check (digest_hour between 0 and 23),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint notification_preferences_employee_unique unique (employee_id)
);

create table if not exists public.email_notification_queue (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete cascade,
  kind text not null,
  subject text not null,
  body text not null,
  action_url text,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued', 'sent', 'failed')),
  scheduled_for timestamp with time zone not null default now(),
  sent_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists email_notification_queue_status_idx
  on public.email_notification_queue (status, scheduled_for);

create index if not exists email_notification_queue_employee_idx
  on public.email_notification_queue (employee_id);

create or replace function public.set_notification_preferences_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_email_notification_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.status = 'sent' and new.sent_at is null then
    new.sent_at = now();
  end if;
  if new.status <> 'sent' then
    new.sent_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notification_preferences_updated_at on public.notification_preferences;
create trigger trg_notification_preferences_updated_at
before update on public.notification_preferences
for each row
execute function public.set_notification_preferences_updated_at();

drop trigger if exists trg_email_notification_queue_updated_at on public.email_notification_queue;
create trigger trg_email_notification_queue_updated_at
before update on public.email_notification_queue
for each row
execute function public.set_email_notification_queue_updated_at();

alter table public.notification_preferences enable row level security;
alter table public.email_notification_queue enable row level security;

drop policy if exists "Allow read notification preferences" on public.notification_preferences;
create policy "Allow read notification preferences"
on public.notification_preferences
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert notification preferences" on public.notification_preferences;
create policy "Allow insert notification preferences"
on public.notification_preferences
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update notification preferences" on public.notification_preferences;
create policy "Allow update notification preferences"
on public.notification_preferences
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow read email notification queue" on public.email_notification_queue;
create policy "Allow read email notification queue"
on public.email_notification_queue
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert email notification queue" on public.email_notification_queue;
create policy "Allow insert email notification queue"
on public.email_notification_queue
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update email notification queue" on public.email_notification_queue;
create policy "Allow update email notification queue"
on public.email_notification_queue
for update
to authenticated, anon
using (true)
with check (true);
