create table if not exists public.employee_availability (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees (id) on delete cascade,
  available_date date not null,
  availability_status text not null default 'unknown'
    check (availability_status in ('available', 'unavailable', 'unknown')),
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (employee_id, available_date)
);

create index if not exists employee_availability_employee_date_idx
  on public.employee_availability (employee_id, available_date asc);

create or replace function public.set_employee_availability_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_employee_availability_updated_at on public.employee_availability;

create trigger trg_employee_availability_updated_at
before update on public.employee_availability
for each row
execute function public.set_employee_availability_updated_at();

alter table public.employee_availability enable row level security;

create policy "Allow read employee availability"
on public.employee_availability
for select
to authenticated, anon
using (true);

create policy "Allow insert employee availability"
on public.employee_availability
for insert
to authenticated, anon
with check (true);

create policy "Allow update employee availability"
on public.employee_availability
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow delete employee availability"
on public.employee_availability
for delete
to authenticated, anon
using (true);
