create table if not exists public.location_financial_rules (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations (id) on delete cascade,
  scope_type text not null
    check (scope_type in ('location', 'machine', 'product_group', 'product')),
  settlement_type text not null
    check (settlement_type in ('fixed_amount', 'per_unit', 'commission', 'subsidy')),
  direction text not null
    check (direction in ('to_partner', 'from_partner')),
  amount numeric(12, 2) not null default 0,
  currency text not null default 'CZK',
  unit text,
  periodicity text,
  valid_from date,
  valid_to date,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists location_financial_rules_location_idx
  on public.location_financial_rules (location_id);

create table if not exists public.machine_financial_rules (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  scope_type text not null
    check (scope_type in ('machine', 'product_group', 'product')),
  settlement_type text not null
    check (settlement_type in ('fixed_amount', 'per_unit', 'commission', 'subsidy')),
  direction text not null
    check (direction in ('to_partner', 'from_partner')),
  amount numeric(12, 2) not null default 0,
  currency text not null default 'CZK',
  unit text,
  periodicity text,
  valid_from date,
  valid_to date,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists machine_financial_rules_machine_idx
  on public.machine_financial_rules (machine_id);

create or replace function public.set_financial_rules_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_location_financial_rules_updated_at on public.location_financial_rules;
create trigger trg_location_financial_rules_updated_at
before update on public.location_financial_rules
for each row
execute function public.set_financial_rules_updated_at();

drop trigger if exists trg_machine_financial_rules_updated_at on public.machine_financial_rules;
create trigger trg_machine_financial_rules_updated_at
before update on public.machine_financial_rules
for each row
execute function public.set_financial_rules_updated_at();

alter table public.location_financial_rules enable row level security;
alter table public.machine_financial_rules enable row level security;

create policy "Allow read location financial rules"
on public.location_financial_rules
for select
to authenticated, anon
using (true);

create policy "Allow insert location financial rules"
on public.location_financial_rules
for insert
to authenticated, anon
with check (true);

create policy "Allow update location financial rules"
on public.location_financial_rules
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read machine financial rules"
on public.machine_financial_rules
for select
to authenticated, anon
using (true);

create policy "Allow insert machine financial rules"
on public.machine_financial_rules
for insert
to authenticated, anon
with check (true);

create policy "Allow update machine financial rules"
on public.machine_financial_rules
for update
to authenticated, anon
using (true)
with check (true);
