begin;

alter table public.machine_planogram_slots
  add column if not exists target_units integer,
  add column if not exists replenishment_mode text not null default 'fixed_target',
  add column if not exists pending_product_id bigint references public.products (id) on delete set null,
  add column if not exists pending_product_sku text,
  add column if not exists pending_product_name text,
  add column if not exists pending_price_czk numeric(10,2),
  add column if not exists pending_change_effective_date date,
  add column if not exists pending_change_note text;

update public.machine_planogram_slots
set target_units = capacity_units
where target_units is null;

alter table public.machine_planogram_slots
  drop constraint if exists machine_planogram_slots_replenishment_mode_check;

alter table public.machine_planogram_slots
  add constraint machine_planogram_slots_replenishment_mode_check
  check (replenishment_mode in ('fill_to_capacity', 'fixed_target', 'sales_based'));

create table if not exists public.route_machine_visit_food_fills (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.route_machine_visits (id) on delete cascade,
  visit_item_id bigint references public.route_machine_visit_items (id) on delete cascade,
  machine_id bigint not null references public.machines (id) on delete cascade,
  planogram_slot_id bigint not null references public.machine_planogram_slots (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  product_sku text,
  product_name text,
  quantity integer not null check (quantity > 0),
  expiry_date date,
  sale_price_czk numeric(10,2),
  load_order integer not null default 0,
  stock_reference_id text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists route_machine_visit_food_fills_visit_idx
  on public.route_machine_visit_food_fills (visit_id, planogram_slot_id, load_order);

alter table public.route_machine_visit_food_fills enable row level security;

drop policy if exists "Allow read route food fills" on public.route_machine_visit_food_fills;
create policy "Allow read route food fills" on public.route_machine_visit_food_fills
for select to authenticated, anon using (true);

drop policy if exists "Allow write route food fills" on public.route_machine_visit_food_fills;
create policy "Allow write route food fills" on public.route_machine_visit_food_fills
for all to authenticated, anon using (true) with check (true);

commit;

notify pgrst, 'reload schema';
