-- Temporary bridge for A5Web transaction exports while the official IMA
-- transaction interface is being enabled. Only the three Hanak devices are
-- accepted. Card identifiers are deliberately not stored.

begin;

create table if not exists public.ima_a5_sales_imports (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  transaction_id text,
  device_uid text not null,
  device_acronym text,
  machine_id bigint references public.machines (id) on delete set null,
  planogram_slot_id bigint references public.machine_planogram_slots (id) on delete set null,
  selection_code text not null,
  customer_selection_code text,
  product_name text,
  quantity numeric(12,3) not null default 1,
  unit_price_czk numeric(10,2),
  payment_method text,
  source_event_at timestamptz not null,
  status text not null check (status in ('applied','unmatched_machine','unmatched_slot','ignored_device')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ima_a5_sales_imports_event_idx
  on public.ima_a5_sales_imports (source_event_at desc);

create index if not exists ima_a5_sales_imports_machine_idx
  on public.ima_a5_sales_imports (machine_id, source_event_at desc);

alter table public.ima_a5_sales_imports enable row level security;

drop policy if exists "Allow read IMA A5 sales imports" on public.ima_a5_sales_imports;
create policy "Allow read IMA A5 sales imports"
on public.ima_a5_sales_imports
for select
to authenticated
using (public.security_active_employee());

create or replace function public.apply_ima_a5_sale(
  p_event_key text,
  p_transaction_id text,
  p_device_uid text,
  p_device_acronym text,
  p_selection_code text,
  p_product_name text,
  p_quantity numeric,
  p_unit_price_czk numeric,
  p_payment_method text,
  p_source_event_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_machine public.machines%rowtype;
  v_slot public.machine_planogram_slots%rowtype;
  v_existing_status text;
  v_quantity numeric := greatest(coalesce(p_quantity, 1), 0);
  v_unit_price numeric;
  v_total numeric;
  v_cash_quantity numeric := 0;
  v_cashless_quantity numeric := 0;
  v_unknown_quantity numeric := 0;
  v_payment text := lower(trim(coalesce(p_payment_method, '')));
  v_selection_raw text := trim(coalesce(p_selection_code, ''));
  -- A5 can set bit 15 in the vend number. 32792 therefore means selection 24.
  v_selection text := case
    when trim(coalesce(p_selection_code, '')) ~ '^\d+$'
     and trim(p_selection_code)::bigint between 32768 and 65535
      then (trim(p_selection_code)::bigint - 32768)::text
    else trim(coalesce(p_selection_code, ''))
  end;
  v_next_units numeric;
  v_next_fill numeric;
begin
  if nullif(trim(coalesce(p_event_key, '')), '') is null
     or nullif(trim(coalesce(p_device_uid, '')), '') is null
     or nullif(v_selection, '') is null
     or p_source_event_at is null then
    raise exception 'IMA A5 import is missing an event key, device UID, selection or timestamp.';
  end if;

  if trim(p_device_uid) not in ('635456','635457','635458') then
    insert into public.ima_a5_sales_imports (
      event_key, transaction_id, device_uid, device_acronym, selection_code,
      product_name, quantity, unit_price_czk, payment_method, source_event_at,
      status, note
    ) values (
      trim(p_event_key), nullif(trim(p_transaction_id), ''), trim(p_device_uid),
      nullif(trim(p_device_acronym), ''), v_selection,
      nullif(trim(p_product_name), ''), v_quantity, p_unit_price_czk,
      nullif(trim(p_payment_method), ''), p_source_event_at,
      'ignored_device', 'Dočasný import je povolen pouze pro terminály Hanák.'
    ) on conflict (event_key) do nothing;
    return jsonb_build_object('status','ignored_device','device_uid',trim(p_device_uid));
  end if;

  select status into v_existing_status
  from public.ima_a5_sales_imports
  where event_key = trim(p_event_key);
  if v_existing_status = 'applied' then
    return jsonb_build_object('status','duplicate','event_key',trim(p_event_key));
  end if;

  select machine.* into v_machine
  from public.machine_external_links link
  join public.machines machine on machine.id = link.machine_id
  where upper(link.provider) = 'IMA'
    and link.external_machine_id = trim(p_device_uid)
    and link.telemetry_enabled is true
    and machine.active is true
  order by link.id desc
  limit 1;

  if not found then
    insert into public.ima_a5_sales_imports (
      event_key, transaction_id, device_uid, device_acronym, selection_code,
      product_name, quantity, unit_price_czk, payment_method, source_event_at,
      status, note, updated_at
    ) values (
      trim(p_event_key), nullif(trim(p_transaction_id), ''), trim(p_device_uid),
      nullif(trim(p_device_acronym), ''), v_selection,
      nullif(trim(p_product_name), ''), v_quantity, p_unit_price_czk,
      nullif(trim(p_payment_method), ''), p_source_event_at,
      'unmatched_machine', 'Aktivní vazba IMA terminálu nebyla nalezena.', now()
    ) on conflict (event_key) do update set
      status=excluded.status, note=excluded.note, updated_at=now();
    return jsonb_build_object('status','unmatched_machine','device_uid',trim(p_device_uid));
  end if;

  select slot.* into v_slot
  from public.machine_planogram_slots slot
  where slot.machine_id = v_machine.id
    and slot.active is true
    and (
      trim(coalesce(slot.telemetry_key, '')) = v_selection
      or trim(slot.slot_code) = v_selection
      or trim(coalesce(slot.customer_selection_code, '')) = v_selection
    )
  order by
    case when trim(coalesce(slot.telemetry_key, '')) = v_selection then 0
         when trim(slot.slot_code) = v_selection then 1 else 2 end,
    slot.id
  limit 1
  for update;

  if not found then
    insert into public.ima_a5_sales_imports (
      event_key, transaction_id, device_uid, device_acronym, machine_id,
      selection_code, product_name, quantity, unit_price_czk, payment_method,
      source_event_at, status, note, updated_at
    ) values (
      trim(p_event_key), nullif(trim(p_transaction_id), ''), trim(p_device_uid),
      nullif(trim(p_device_acronym), ''), v_machine.id, v_selection,
      nullif(trim(p_product_name), ''), v_quantity, p_unit_price_czk,
      nullif(trim(p_payment_method), ''), p_source_event_at,
      'unmatched_slot', 'Volba z IMA nebyla nalezena v aktivním plánogramu.', now()
    ) on conflict (event_key) do update set
      machine_id=excluded.machine_id, status=excluded.status,
      note=excluded.note, updated_at=now();
    return jsonb_build_object('status','unmatched_slot','machine_id',v_machine.id,'selection',v_selection,'raw_selection',v_selection_raw);
  end if;

  if v_quantity <= 0 then
    return jsonb_build_object('status','ignored_quantity','quantity',v_quantity);
  end if;

  v_unit_price := coalesce(p_unit_price_czk, v_slot.customer_price_czk, v_slot.price_czk, v_slot.dex_price_czk, 0);
  v_total := round(v_unit_price * v_quantity, 2);

  if v_payment ~ '(hotov|cash|mincov|f0)' then
    v_cash_quantity := v_quantity;
  elsif v_payment ~ '(emv|kart|card|bezkont|online)' then
    v_cashless_quantity := v_quantity;
  else
    v_unknown_quantity := v_quantity;
  end if;

  insert into public.ima_a5_sales_imports (
    event_key, transaction_id, device_uid, device_acronym, machine_id,
    planogram_slot_id, selection_code, customer_selection_code, product_name,
    quantity, unit_price_czk, payment_method, source_event_at, status, note,
    updated_at
  ) values (
    trim(p_event_key), nullif(trim(p_transaction_id), ''), trim(p_device_uid),
    nullif(trim(p_device_acronym), ''), v_machine.id, v_slot.id,
    v_selection, v_slot.customer_selection_code,
    coalesce(nullif(trim(p_product_name), ''), v_slot.product_name),
    v_quantity, v_unit_price, nullif(trim(p_payment_method), ''),
    p_source_event_at, 'applied', 'Provizorní import z A5Web bez údajů o platební kartě.', now()
  ) on conflict (event_key) do update set
    transaction_id=excluded.transaction_id,
    device_acronym=excluded.device_acronym,
    machine_id=excluded.machine_id,
    planogram_slot_id=excluded.planogram_slot_id,
    selection_code=excluded.selection_code,
    customer_selection_code=excluded.customer_selection_code,
    product_name=excluded.product_name,
    quantity=excluded.quantity,
    unit_price_czk=excluded.unit_price_czk,
    payment_method=excluded.payment_method,
    source_event_at=excluded.source_event_at,
    status='applied', note=excluded.note, updated_at=now();

  if lower(coalesce(v_machine.machine_type, '')) = 'snack'
     and v_slot.current_units is not null then
    v_next_units := greatest(0, v_slot.current_units - v_quantity);
    v_next_fill := case when coalesce(v_slot.capacity_units,0) > 0
      then round((v_next_units / v_slot.capacity_units) * 100, 2) else null end;
    update public.machine_planogram_slots
    set current_units = v_next_units,
        fill_percent = v_next_fill,
        desired_units = case when target_units is null then desired_units
          else greatest(0, target_units - v_next_units)::integer end,
        updated_at = now()
    where id = v_slot.id;
  end if;

  insert into public.telemetry_sales_events (
    provider, ingest_id, machine_id, planogram_slot_id, selection_code,
    product_name, product_sku, quantity, cash_quantity, cashless_quantity,
    unknown_payment_quantity, unit_price_czk, total_amount_czk, cash_amount_czk,
    cashless_amount_czk, unknown_payment_amount_czk, source_event_at,
    source_event_key, source_location_name, source_machine_name
  ) values (
    'IMA-A5', null, v_machine.id, v_slot.id, v_slot.slot_code,
    coalesce(nullif(trim(p_product_name), ''), v_slot.product_name), v_slot.product_sku,
    v_quantity, v_cash_quantity, v_cashless_quantity, v_unknown_quantity,
    v_unit_price, v_total,
    case when v_cash_quantity > 0 then v_total else null end,
    case when v_cashless_quantity > 0 then v_total else null end,
    case when v_unknown_quantity > 0 then v_total else null end,
    p_source_event_at, trim(p_event_key), null, nullif(trim(p_device_acronym), '')
  ) on conflict (provider, source_event_key, event_part) where source_event_key is not null do nothing;

  insert into public.machine_telemetry_state (
    machine_id, provider, last_seen_at, connectivity_status, counters_payload, updated_at
  ) values (
    v_machine.id, 'IMA-A5', p_source_event_at, 'online',
    jsonb_build_object(
      'temporary_a5_sync', true,
      'device_uid', trim(p_device_uid),
      'last_transaction_id', nullif(trim(p_transaction_id), ''),
      'last_selection_code', v_selection,
      'last_raw_selection_code', v_selection_raw,
      'last_event_key', trim(p_event_key)
    ), now()
  ) on conflict (machine_id, provider) do update set
    last_seen_at = greatest(public.machine_telemetry_state.last_seen_at, excluded.last_seen_at),
    connectivity_status = 'online', counters_payload = excluded.counters_payload,
    updated_at = now();

  return jsonb_build_object(
    'status','applied', 'machine_id',v_machine.id, 'slot_id',v_slot.id,
    'selection',v_slot.slot_code, 'customer_selection',v_slot.customer_selection_code,
    'previous_units',v_slot.current_units, 'next_units',v_next_units
  );
end;
$$;

revoke all on function public.apply_ima_a5_sale(
  text,text,text,text,text,text,numeric,numeric,text,timestamptz
) from public, anon, authenticated;

grant execute on function public.apply_ima_a5_sale(
  text,text,text,text,text,text,numeric,numeric,text,timestamptz
) to service_role;

commit;

notify pgrst, 'reload schema';
