create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text unique,
  ean text,
  product_category text not null
    check (product_category in (
      'beverage_ready',
      'snack_ready',
      'food_ready',
      'ingredient',
      'consumable',
      'service_material',
      'spare_part'
    )),
  usage_type text not null
    check (usage_type in (
      'direct_sale',
      'recipe_consumption',
      'internal_consumption',
      'service_use'
    )),
  base_unit text not null default 'ks',
  vat_rate numeric(5,2),
  purchase_price numeric(12,2),
  sale_price numeric(12,2),
  shelf_life_days integer,
  expiry_tracking_mode text not null default 'none'
    check (expiry_tracking_mode in ('none', 'best_before', 'use_by')),
  expiry_warning_days integer not null default 0,
  requires_batch_tracking boolean not null default false,
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists products_category_idx
  on public.products (product_category);

create index if not exists products_usage_type_idx
  on public.products (usage_type);

create index if not exists products_active_idx
  on public.products (active);

create table if not exists public.product_packages (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  package_name text not null,
  units_per_package numeric(12,3) not null check (units_per_package > 0),
  package_barcode text,
  is_default boolean not null default false,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (product_id, package_name)
);

create index if not exists product_packages_product_idx
  on public.product_packages (product_id);

create table if not exists public.stock_locations (
  id bigint generated by default as identity primary key,
  location_type text not null
    check (location_type in ('warehouse', 'vehicle', 'employee', 'machine', 'machine_slot')),
  name text not null,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  employee_id uuid references public.employees (id) on delete set null,
  machine_id bigint references public.machines (id) on delete set null,
  planogram_slot_id bigint references public.machine_planogram_slots (id) on delete set null,
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists stock_locations_type_idx
  on public.stock_locations (location_type);

create index if not exists stock_locations_vehicle_idx
  on public.stock_locations (vehicle_id);

create index if not exists stock_locations_machine_idx
  on public.stock_locations (machine_id);

create table if not exists public.inventory_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  lot_code text,
  best_before_date date,
  use_by_date date,
  received_at timestamp with time zone,
  supplier_name text,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists inventory_batches_product_idx
  on public.inventory_batches (product_id);

create index if not exists inventory_batches_best_before_idx
  on public.inventory_batches (best_before_date);

create index if not exists inventory_batches_use_by_idx
  on public.inventory_batches (use_by_date);

create table if not exists public.stock_location_balances (
  id bigint generated by default as identity primary key,
  stock_location_id bigint not null references public.stock_locations (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  batch_id bigint references public.inventory_batches (id) on delete set null,
  quantity_on_hand numeric(12,3) not null default 0,
  reserved_quantity numeric(12,3) not null default 0,
  updated_at timestamp with time zone not null default now(),
  unique (stock_location_id, product_id, batch_id)
);

create index if not exists stock_location_balances_location_idx
  on public.stock_location_balances (stock_location_id);

create index if not exists stock_location_balances_product_idx
  on public.stock_location_balances (product_id);

create table if not exists public.stock_movements_v13 (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete restrict,
  batch_id bigint references public.inventory_batches (id) on delete set null,
  from_stock_location_id bigint references public.stock_locations (id) on delete set null,
  to_stock_location_id bigint references public.stock_locations (id) on delete set null,
  movement_type text not null
    check (movement_type in (
      'receipt',
      'transfer',
      'load_vehicle',
      'fill_machine',
      'sale',
      'consumption',
      'return',
      'adjustment',
      'waste'
    )),
  quantity_base_units numeric(12,3) not null check (quantity_base_units > 0),
  package_id bigint references public.product_packages (id) on delete set null,
  package_count numeric(12,3),
  unit_price numeric(12,2),
  reference_type text,
  reference_id text,
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now()
);

create index if not exists stock_movements_v13_product_idx
  on public.stock_movements_v13 (product_id);

create index if not exists stock_movements_v13_from_idx
  on public.stock_movements_v13 (from_stock_location_id);

create index if not exists stock_movements_v13_to_idx
  on public.stock_movements_v13 (to_stock_location_id);

create index if not exists stock_movements_v13_batch_idx
  on public.stock_movements_v13 (batch_id);

create table if not exists public.replenishment_profiles (
  id bigint generated by default as identity primary key,
  stock_location_id bigint not null references public.stock_locations (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  min_quantity numeric(12,3) not null default 0,
  target_quantity numeric(12,3) not null default 0,
  reorder_multiple_package_id bigint references public.product_packages (id) on delete set null,
  reorder_only_full_packages boolean not null default false,
  consider_expiry boolean not null default true,
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (stock_location_id, product_id)
);

create index if not exists replenishment_profiles_location_idx
  on public.replenishment_profiles (stock_location_id);

create table if not exists public.pick_list_drafts (
  id bigint generated by default as identity primary key,
  draft_type text not null
    check (draft_type in ('vehicle_restock', 'warehouse_restock')),
  source_stock_location_id bigint references public.stock_locations (id) on delete set null,
  target_stock_location_id bigint references public.stock_locations (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  attendance_day_id bigint references public.attendance_days (id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft', 'reviewed', 'approved', 'picked', 'cancelled')),
  generated_reason text,
  generated_at timestamp with time zone not null default now(),
  reviewed_at timestamp with time zone,
  approved_at timestamp with time zone,
  note text
);

create index if not exists pick_list_drafts_status_idx
  on public.pick_list_drafts (status);

create index if not exists pick_list_drafts_vehicle_idx
  on public.pick_list_drafts (vehicle_id);

create table if not exists public.pick_list_draft_items (
  id bigint generated by default as identity primary key,
  pick_list_draft_id bigint not null references public.pick_list_drafts (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  suggested_quantity_base_units numeric(12,3) not null default 0,
  suggested_package_id bigint references public.product_packages (id) on delete set null,
  suggested_package_count numeric(12,3),
  approved_quantity_base_units numeric(12,3),
  approved_package_id bigint references public.product_packages (id) on delete set null,
  approved_package_count numeric(12,3),
  current_quantity numeric(12,3),
  min_quantity numeric(12,3),
  target_quantity numeric(12,3),
  reason_code text not null
    check (reason_code in (
      'below_min',
      'target_restock',
      'route_need',
      'sales_trend',
      'expiry_risk',
      'expired_stock',
      'warehouse_shortage'
    )),
  reason_detail text,
  note text,
  created_at timestamp with time zone not null default now()
);

create index if not exists pick_list_draft_items_draft_idx
  on public.pick_list_draft_items (pick_list_draft_id);

create index if not exists pick_list_draft_items_product_idx
  on public.pick_list_draft_items (product_id);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  machine_id bigint references public.machines (id) on delete cascade,
  machine_type text,
  selection_code text not null,
  name text not null,
  sale_price numeric(12,2),
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists recipes_machine_idx
  on public.recipes (machine_id);

create table if not exists public.recipe_items (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  quantity numeric(12,3) not null check (quantity > 0),
  unit text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists recipe_items_recipe_idx
  on public.recipe_items (recipe_id);

create table if not exists public.sales_documents (
  id bigint generated by default as identity primary key,
  document_type text not null
    check (document_type in ('invoice', 'cash_receipt', 'credit_note')),
  customer_name text,
  issued_at timestamp with time zone not null default now(),
  currency text not null default 'CZK',
  total_amount numeric(12,2),
  status text not null default 'draft'
    check (status in ('draft', 'issued', 'cancelled', 'paid')),
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.sales_document_items (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.sales_documents (id) on delete cascade,
  product_id bigint references public.products (id) on delete set null,
  quantity numeric(12,3) not null,
  unit_price numeric(12,2) not null,
  vat_rate numeric(5,2),
  source_type text,
  source_id text,
  created_at timestamp with time zone not null default now()
);

create index if not exists sales_document_items_document_idx
  on public.sales_document_items (document_id);

create or replace function public.set_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_product_packages_updated_at on public.product_packages;
create trigger trg_product_packages_updated_at
before update on public.product_packages
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_stock_locations_updated_at on public.stock_locations;
create trigger trg_stock_locations_updated_at
before update on public.stock_locations
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_inventory_batches_updated_at on public.inventory_batches;
create trigger trg_inventory_batches_updated_at
before update on public.inventory_batches
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_replenishment_profiles_updated_at on public.replenishment_profiles;
create trigger trg_replenishment_profiles_updated_at
before update on public.replenishment_profiles
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_recipes_updated_at on public.recipes;
create trigger trg_recipes_updated_at
before update on public.recipes
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_sales_documents_updated_at on public.sales_documents;
create trigger trg_sales_documents_updated_at
before update on public.sales_documents
for each row
execute function public.set_updated_at_column();

alter table public.products enable row level security;
alter table public.product_packages enable row level security;
alter table public.stock_locations enable row level security;
alter table public.inventory_batches enable row level security;
alter table public.stock_location_balances enable row level security;
alter table public.stock_movements_v13 enable row level security;
alter table public.replenishment_profiles enable row level security;
alter table public.pick_list_drafts enable row level security;
alter table public.pick_list_draft_items enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_items enable row level security;
alter table public.sales_documents enable row level security;
alter table public.sales_document_items enable row level security;

create policy "Allow read products"
on public.products
for select
to authenticated, anon
using (true);

create policy "Allow insert products"
on public.products
for insert
to authenticated, anon
with check (true);

create policy "Allow update products"
on public.products
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read product packages"
on public.product_packages
for select
to authenticated, anon
using (true);

create policy "Allow insert product packages"
on public.product_packages
for insert
to authenticated, anon
with check (true);

create policy "Allow update product packages"
on public.product_packages
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read stock locations"
on public.stock_locations
for select
to authenticated, anon
using (true);

create policy "Allow insert stock locations"
on public.stock_locations
for insert
to authenticated, anon
with check (true);

create policy "Allow update stock locations"
on public.stock_locations
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read inventory batches"
on public.inventory_batches
for select
to authenticated, anon
using (true);

create policy "Allow insert inventory batches"
on public.inventory_batches
for insert
to authenticated, anon
with check (true);

create policy "Allow update inventory batches"
on public.inventory_batches
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read stock balances"
on public.stock_location_balances
for select
to authenticated, anon
using (true);

create policy "Allow insert stock balances"
on public.stock_location_balances
for insert
to authenticated, anon
with check (true);

create policy "Allow update stock balances"
on public.stock_location_balances
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read stock movements v13"
on public.stock_movements_v13
for select
to authenticated, anon
using (true);

create policy "Allow insert stock movements v13"
on public.stock_movements_v13
for insert
to authenticated, anon
with check (true);

create policy "Allow read replenishment profiles"
on public.replenishment_profiles
for select
to authenticated, anon
using (true);

create policy "Allow insert replenishment profiles"
on public.replenishment_profiles
for insert
to authenticated, anon
with check (true);

create policy "Allow update replenishment profiles"
on public.replenishment_profiles
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read pick list drafts"
on public.pick_list_drafts
for select
to authenticated, anon
using (true);

create policy "Allow insert pick list drafts"
on public.pick_list_drafts
for insert
to authenticated, anon
with check (true);

create policy "Allow update pick list drafts"
on public.pick_list_drafts
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read pick list draft items"
on public.pick_list_draft_items
for select
to authenticated, anon
using (true);

create policy "Allow insert pick list draft items"
on public.pick_list_draft_items
for insert
to authenticated, anon
with check (true);

create policy "Allow update pick list draft items"
on public.pick_list_draft_items
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read recipes"
on public.recipes
for select
to authenticated, anon
using (true);

create policy "Allow insert recipes"
on public.recipes
for insert
to authenticated, anon
with check (true);

create policy "Allow update recipes"
on public.recipes
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read recipe items"
on public.recipe_items
for select
to authenticated, anon
using (true);

create policy "Allow insert recipe items"
on public.recipe_items
for insert
to authenticated, anon
with check (true);

create policy "Allow update recipe items"
on public.recipe_items
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read sales documents"
on public.sales_documents
for select
to authenticated, anon
using (true);

create policy "Allow insert sales documents"
on public.sales_documents
for insert
to authenticated, anon
with check (true);

create policy "Allow update sales documents"
on public.sales_documents
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read sales document items"
on public.sales_document_items
for select
to authenticated, anon
using (true);

create policy "Allow insert sales document items"
on public.sales_document_items
for insert
to authenticated, anon
with check (true);

create policy "Allow update sales document items"
on public.sales_document_items
for update
to authenticated, anon
using (true)
with check (true);
