create table if not exists public.inventory_audits (
  id bigint generated by default as identity primary key,
  audit_date date not null,
  scope_type text not null default 'all'
    check (scope_type in ('all', 'warehouse', 'vehicle', 'automaty')),
  stock_location_id bigint references public.stock_locations (id) on delete set null,
  responsible_name text,
  note text,
  status text not null default 'closed'
    check (status in ('draft', 'closed', 'cancelled')),
  book_quantity_total numeric(14,3) not null default 0,
  counted_quantity_total numeric(14,3) not null default 0,
  difference_quantity_total numeric(14,3) not null default 0,
  difference_value_total numeric(14,2) not null default 0,
  created_by uuid references public.employees (id) on delete set null,
  closed_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists inventory_audits_date_idx
  on public.inventory_audits (audit_date);

create index if not exists inventory_audits_location_idx
  on public.inventory_audits (stock_location_id);

create table if not exists public.inventory_audit_items (
  id bigint generated by default as identity primary key,
  audit_id bigint not null references public.inventory_audits (id) on delete cascade,
  stock_location_id bigint references public.stock_locations (id) on delete set null,
  product_id bigint not null references public.products (id) on delete restrict,
  batch_id bigint references public.inventory_batches (id) on delete set null,
  book_quantity numeric(14,3) not null default 0,
  counted_quantity numeric(14,3) not null default 0,
  difference_quantity numeric(14,3) not null default 0,
  unit_cost numeric(12,2),
  difference_value numeric(14,2) not null default 0,
  note text,
  movement_id bigint references public.stock_movements_v13 (id) on delete set null,
  created_at timestamp with time zone not null default now()
);

create index if not exists inventory_audit_items_audit_idx
  on public.inventory_audit_items (audit_id);

create index if not exists inventory_audit_items_product_idx
  on public.inventory_audit_items (product_id);

drop trigger if exists trg_inventory_audits_updated_at on public.inventory_audits;
create trigger trg_inventory_audits_updated_at
before update on public.inventory_audits
for each row
execute function public.set_updated_at_column();

alter table public.inventory_audits enable row level security;
alter table public.inventory_audit_items enable row level security;

drop policy if exists "Allow read inventory audits" on public.inventory_audits;
create policy "Allow read inventory audits"
on public.inventory_audits
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert inventory audits" on public.inventory_audits;
create policy "Allow insert inventory audits"
on public.inventory_audits
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update inventory audits" on public.inventory_audits;
create policy "Allow update inventory audits"
on public.inventory_audits
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow read inventory audit items" on public.inventory_audit_items;
create policy "Allow read inventory audit items"
on public.inventory_audit_items
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert inventory audit items" on public.inventory_audit_items;
create policy "Allow insert inventory audit items"
on public.inventory_audit_items
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update inventory audit items" on public.inventory_audit_items;
create policy "Allow update inventory audit items"
on public.inventory_audit_items
for update
to authenticated, anon
using (true)
with check (true);
