create table if not exists public.stock_items (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text,
  category text,
  unit text not null default 'ks',
  warehouse_id bigint references public.warehouses (id) on delete set null,
  machine_id bigint references public.machines (id) on delete set null,
  min_quantity numeric(12, 2) not null default 0,
  current_quantity numeric(12, 2) not null default 0,
  note text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists stock_items_warehouse_idx
  on public.stock_items (warehouse_id);

create index if not exists stock_items_machine_idx
  on public.stock_items (machine_id);

create index if not exists stock_items_active_idx
  on public.stock_items (active);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  stock_item_id bigint not null references public.stock_items (id) on delete cascade,
  movement_type text not null
    check (movement_type in ('in', 'out', 'adjustment', 'transfer')),
  quantity_delta numeric(12, 2) not null,
  unit text,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  machine_id bigint references public.machines (id) on delete set null,
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now()
);

create index if not exists stock_movements_item_idx
  on public.stock_movements (stock_item_id);

create index if not exists stock_movements_warehouse_idx
  on public.stock_movements (warehouse_id);

create index if not exists stock_movements_machine_idx
  on public.stock_movements (machine_id);

create or replace function public.set_stock_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_stock_items_updated_at on public.stock_items;

create trigger trg_stock_items_updated_at
before update on public.stock_items
for each row
execute function public.set_stock_items_updated_at();

create or replace function public.apply_stock_movement()
returns trigger
language plpgsql
as $$
begin
  update public.stock_items
  set current_quantity = coalesce(current_quantity, 0) + coalesce(new.quantity_delta, 0),
      updated_at = now()
  where id = new.stock_item_id;
  return new;
end;
$$;

drop trigger if exists trg_apply_stock_movement on public.stock_movements;

create trigger trg_apply_stock_movement
after insert on public.stock_movements
for each row
execute function public.apply_stock_movement();

alter table public.stock_items enable row level security;
alter table public.stock_movements enable row level security;

create policy "Allow read stock items"
on public.stock_items
for select
to authenticated, anon
using (true);

create policy "Allow insert stock items"
on public.stock_items
for insert
to authenticated, anon
with check (true);

create policy "Allow update stock items"
on public.stock_items
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read stock movements"
on public.stock_movements
for select
to authenticated, anon
using (true);

create policy "Allow insert stock movements"
on public.stock_movements
for insert
to authenticated, anon
with check (true);
