alter table public.inventory_audit_items
  add column if not exists counted_package_id bigint references public.product_packages (id) on delete set null,
  add column if not exists counted_package_count numeric(14,3) not null default 0,
  add column if not exists counted_loose_quantity numeric(14,3) not null default 0;

create table if not exists public.inventory_audit_expiry_counts (
  id bigint generated by default as identity primary key,
  audit_item_id bigint not null references public.inventory_audit_items (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  package_id bigint references public.product_packages (id) on delete set null,
  package_count numeric(14,3) not null default 0 check (package_count >= 0),
  loose_quantity numeric(14,3) not null default 0 check (loose_quantity >= 0),
  quantity_base_units numeric(14,3) not null check (quantity_base_units >= 0),
  expiry_date date,
  expiry_unknown boolean not null default false,
  lot_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expiry_date is not null or expiry_unknown = true)
);

create index if not exists inventory_audit_expiry_counts_item_idx
  on public.inventory_audit_expiry_counts (audit_item_id);

create index if not exists inventory_audit_expiry_counts_expiry_idx
  on public.inventory_audit_expiry_counts (expiry_date);

drop trigger if exists trg_inventory_audit_expiry_counts_updated_at on public.inventory_audit_expiry_counts;
create trigger trg_inventory_audit_expiry_counts_updated_at
before update on public.inventory_audit_expiry_counts
for each row execute function public.set_updated_at_column();

alter table public.inventory_audit_expiry_counts enable row level security;

drop policy if exists "Allow read inventory audit expiry counts" on public.inventory_audit_expiry_counts;
create policy "Allow read inventory audit expiry counts"
on public.inventory_audit_expiry_counts for select to authenticated, anon using (true);

drop policy if exists "Allow insert inventory audit expiry counts" on public.inventory_audit_expiry_counts;
create policy "Allow insert inventory audit expiry counts"
on public.inventory_audit_expiry_counts for insert to authenticated, anon with check (true);

drop policy if exists "Allow update inventory audit expiry counts" on public.inventory_audit_expiry_counts;
create policy "Allow update inventory audit expiry counts"
on public.inventory_audit_expiry_counts for update to authenticated, anon using (true) with check (true);

drop policy if exists "Allow delete inventory audit expiry counts" on public.inventory_audit_expiry_counts;
create policy "Allow delete inventory audit expiry counts"
on public.inventory_audit_expiry_counts for delete to authenticated, anon using (true);
