create table if not exists public.loading_sessions (
  id bigint generated by default as identity primary key,
  attendance_day_id bigint references public.attendance_days (id) on delete set null,
  employee_id uuid not null references public.employees (id) on delete cascade,
  vehicle_id bigint not null references public.vehicles (id) on delete cascade,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  route_plan_id bigint,
  session_date date not null,
  status text not null default 'open'
    check (status in ('open', 'closed')),
  loading_completed_at timestamp with time zone,
  unloading_started_at timestamp with time zone,
  unloading_completed_at timestamp with time zone,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists loading_sessions_employee_date_idx
  on public.loading_sessions (employee_id, session_date desc);

create index if not exists loading_sessions_vehicle_date_idx
  on public.loading_sessions (vehicle_id, session_date desc);

create index if not exists loading_sessions_status_idx
  on public.loading_sessions (status, session_date desc);

create unique index if not exists loading_sessions_attendance_day_unique
  on public.loading_sessions (attendance_day_id)
  where attendance_day_id is not null;

create table if not exists public.loading_session_items (
  id bigint generated by default as identity primary key,
  loading_session_id bigint not null references public.loading_sessions (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  loaded_quantity numeric(12,3) not null default 0,
  returned_quantity numeric(12,3) not null default 0,
  waste_quantity numeric(12,3) not null default 0,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (loading_session_id, product_id)
);

create index if not exists loading_session_items_session_idx
  on public.loading_session_items (loading_session_id);

create index if not exists loading_session_items_product_idx
  on public.loading_session_items (product_id);

create or replace function public.set_loading_sessions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_loading_sessions_updated_at on public.loading_sessions;
create trigger trg_loading_sessions_updated_at
before update on public.loading_sessions
for each row
execute function public.set_loading_sessions_updated_at();

drop trigger if exists trg_loading_session_items_updated_at on public.loading_session_items;
create trigger trg_loading_session_items_updated_at
before update on public.loading_session_items
for each row
execute function public.set_loading_sessions_updated_at();

alter table public.loading_sessions enable row level security;
alter table public.loading_session_items enable row level security;

drop policy if exists "Allow read loading sessions" on public.loading_sessions;
create policy "Allow read loading sessions"
on public.loading_sessions
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert loading sessions" on public.loading_sessions;
create policy "Allow insert loading sessions"
on public.loading_sessions
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update loading sessions" on public.loading_sessions;
create policy "Allow update loading sessions"
on public.loading_sessions
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow read loading session items" on public.loading_session_items;
create policy "Allow read loading session items"
on public.loading_session_items
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert loading session items" on public.loading_session_items;
create policy "Allow insert loading session items"
on public.loading_session_items
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update loading session items" on public.loading_session_items;
create policy "Allow update loading session items"
on public.loading_session_items
for update
to authenticated, anon
using (true)
with check (true);
