create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  city text,
  address text,
  customer_name text,
  contact_person text,
  contact_phone text,
  service_window text,
  route_note text,
  vendsoft_location_id text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists locations_name_idx
  on public.locations (name);

create index if not exists locations_city_idx
  on public.locations (city);

create index if not exists locations_active_idx
  on public.locations (active);

create or replace function public.set_locations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_locations_updated_at on public.locations;

create trigger trg_locations_updated_at
before update on public.locations
for each row
execute function public.set_locations_updated_at();

alter table public.locations enable row level security;

create policy "Allow read locations"
on public.locations
for select
to authenticated, anon
using (true);

create policy "Allow insert locations"
on public.locations
for insert
to authenticated, anon
with check (true);

create policy "Allow update locations"
on public.locations
for update
to authenticated, anon
using (true)
with check (true);
