create sequence if not exists public.machine_evidence_number_seq;

create table if not exists public.machines (
  id bigint generated by default as identity primary key,
  location_id bigint references public.locations (id) on delete set null,
  name text not null,
  machine_type text not null,
  brand text,
  model text,
  serial_number text,
  evidence_number bigint default nextval('public.machine_evidence_number_seq'),
  status text not null default 'ok'
    check (status in ('ok', 'service_needed', 'offline', 'installing', 'removed')),
  active boolean not null default true,
  note text,
  qr_token text not null unique,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.machines
  add column if not exists evidence_number bigint;

alter table public.machines
  alter column evidence_number set default nextval('public.machine_evidence_number_seq');

create index if not exists machines_location_idx
  on public.machines (location_id);

create index if not exists machines_type_idx
  on public.machines (machine_type);

create index if not exists machines_active_idx
  on public.machines (active);

create index if not exists machines_status_idx
  on public.machines (status);

create index if not exists machines_serial_idx
  on public.machines (serial_number);

create unique index if not exists machines_evidence_number_uidx
  on public.machines (evidence_number)
  where evidence_number is not null;

create table if not exists public.machine_service_rules (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  service_frequency text,
  fill_frequency text,
  last_service_at timestamp with time zone,
  last_fill_at timestamp with time zone,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (machine_id)
);

create index if not exists machine_service_rules_machine_idx
  on public.machine_service_rules (machine_id);

create or replace function public.set_machines_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_machines_updated_at on public.machines;

create trigger trg_machines_updated_at
before update on public.machines
for each row
execute function public.set_machines_updated_at();

create or replace function public.set_machine_service_rules_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_machine_service_rules_updated_at on public.machine_service_rules;

create trigger trg_machine_service_rules_updated_at
before update on public.machine_service_rules
for each row
execute function public.set_machine_service_rules_updated_at();

alter table public.machines enable row level security;
alter table public.machine_service_rules enable row level security;

create policy "Allow read machines"
on public.machines
for select
to authenticated, anon
using (true);

create policy "Allow insert machines"
on public.machines
for insert
to authenticated, anon
with check (true);

create policy "Allow update machines"
on public.machines
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read machine service rules"
on public.machine_service_rules
for select
to authenticated, anon
using (true);

create policy "Allow insert machine service rules"
on public.machine_service_rules
for insert
to authenticated, anon
with check (true);

create policy "Allow update machine service rules"
on public.machine_service_rules
for update
to authenticated, anon
using (true)
with check (true);
