create table if not exists public.machine_transfers (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  from_location_id bigint references public.locations (id) on delete set null,
  to_location_id bigint references public.locations (id) on delete set null,
  transfer_kind text not null default 'relocation'
    check (transfer_kind in ('relocation', 'storage')),
  from_status text,
  to_status text,
  from_active boolean,
  to_active boolean,
  transferred_at timestamp with time zone not null default now(),
  transferred_by text,
  note text,
  created_at timestamp with time zone not null default now()
);

create index if not exists machine_transfers_machine_idx
  on public.machine_transfers (machine_id, transferred_at desc);

create index if not exists machine_transfers_from_location_idx
  on public.machine_transfers (from_location_id);

create index if not exists machine_transfers_to_location_idx
  on public.machine_transfers (to_location_id);

alter table public.machine_transfers enable row level security;

create policy "Allow read machine transfers"
on public.machine_transfers
for select
to authenticated, anon
using (true);

create policy "Allow insert machine transfers"
on public.machine_transfers
for insert
to authenticated, anon
with check (true);

