create table if not exists public.machine_coffee_containers (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  container_code text not null,
  product_id bigint references public.products (id) on delete set null,
  product_sku text,
  product_name text not null,
  capacity_quantity numeric(12,3),
  current_quantity numeric(12,3),
  unit text not null default 'g',
  refill_package_quantity numeric(12,3),
  refill_package_unit text,
  min_refill_quantity numeric(12,3),
  sort_order integer not null default 0,
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (machine_id, container_code)
);

create table if not exists public.machine_coffee_buttons (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  selection_code text not null,
  product_id bigint references public.products (id) on delete set null,
  product_sku text,
  product_name text not null,
  sale_price_czk numeric(10,2),
  customer_price_czk numeric(10,2),
  settlement_type text not null default 'none',
  settlement_amount_czk numeric(10,2) not null default 0,
  settlement_partner text,
  settlement_billing_enabled boolean not null default false,
  settlement_note text,
  planned_product_name text,
  planned_product_sku text,
  planned_price_czk numeric(10,2),
  substitution_policy text not null default 'exact',
  allowed_substitutes text,
  operator_instruction text,
  last_counter integer,
  grid_column integer,
  grid_row_from_bottom integer,
  sort_order integer not null default 0,
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (machine_id, selection_code)
);

create table if not exists public.machine_coffee_recipe_items (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  coffee_button_id bigint references public.machine_coffee_buttons (id) on delete cascade,
  coffee_container_id bigint references public.machine_coffee_containers (id) on delete set null,
  product_id bigint references public.products (id) on delete set null,
  container_code text,
  ingredient_name text,
  quantity_per_vend numeric(12,4) not null default 0,
  unit text not null default 'g',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists machine_coffee_containers_machine_idx
  on public.machine_coffee_containers (machine_id, sort_order);

create index if not exists machine_coffee_buttons_machine_idx
  on public.machine_coffee_buttons (machine_id, sort_order);

alter table public.machine_coffee_containers add column if not exists product_id bigint references public.products (id) on delete set null;
alter table public.machine_coffee_buttons add column if not exists product_id bigint references public.products (id) on delete set null;
alter table public.machine_coffee_recipe_items add column if not exists product_id bigint references public.products (id) on delete set null;

create index if not exists machine_coffee_containers_product_idx
  on public.machine_coffee_containers (product_id);

create index if not exists machine_coffee_buttons_product_idx
  on public.machine_coffee_buttons (product_id);

alter table public.machine_coffee_buttons add column if not exists customer_price_czk numeric(10,2);
alter table public.machine_coffee_buttons add column if not exists settlement_type text not null default 'none';
alter table public.machine_coffee_buttons add column if not exists settlement_amount_czk numeric(10,2) not null default 0;
alter table public.machine_coffee_buttons add column if not exists settlement_partner text;
alter table public.machine_coffee_buttons add column if not exists settlement_billing_enabled boolean not null default false;
alter table public.machine_coffee_buttons add column if not exists settlement_note text;
alter table public.machine_coffee_buttons add column if not exists planned_product_name text;
alter table public.machine_coffee_buttons add column if not exists planned_product_sku text;
alter table public.machine_coffee_buttons add column if not exists planned_price_czk numeric(10,2);
alter table public.machine_coffee_buttons add column if not exists substitution_policy text not null default 'exact';
alter table public.machine_coffee_buttons add column if not exists allowed_substitutes text;
alter table public.machine_coffee_buttons add column if not exists operator_instruction text;

create index if not exists machine_coffee_recipe_items_button_idx
  on public.machine_coffee_recipe_items (coffee_button_id, sort_order);

create or replace function public.set_machine_coffee_planogram_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_machine_coffee_containers_updated_at on public.machine_coffee_containers;
create trigger trg_machine_coffee_containers_updated_at
before update on public.machine_coffee_containers
for each row
execute function public.set_machine_coffee_planogram_updated_at();

drop trigger if exists trg_machine_coffee_buttons_updated_at on public.machine_coffee_buttons;
create trigger trg_machine_coffee_buttons_updated_at
before update on public.machine_coffee_buttons
for each row
execute function public.set_machine_coffee_planogram_updated_at();

drop trigger if exists trg_machine_coffee_recipe_items_updated_at on public.machine_coffee_recipe_items;
create trigger trg_machine_coffee_recipe_items_updated_at
before update on public.machine_coffee_recipe_items
for each row
execute function public.set_machine_coffee_planogram_updated_at();

alter table public.machine_coffee_containers enable row level security;
alter table public.machine_coffee_buttons enable row level security;
alter table public.machine_coffee_recipe_items enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_containers' and policyname = 'Allow read machine coffee containers') then
    create policy "Allow read machine coffee containers" on public.machine_coffee_containers for select to authenticated, anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_containers' and policyname = 'Allow insert machine coffee containers') then
    create policy "Allow insert machine coffee containers" on public.machine_coffee_containers for insert to authenticated, anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_containers' and policyname = 'Allow update machine coffee containers') then
    create policy "Allow update machine coffee containers" on public.machine_coffee_containers for update to authenticated, anon using (true) with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_buttons' and policyname = 'Allow read machine coffee buttons') then
    create policy "Allow read machine coffee buttons" on public.machine_coffee_buttons for select to authenticated, anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_buttons' and policyname = 'Allow insert machine coffee buttons') then
    create policy "Allow insert machine coffee buttons" on public.machine_coffee_buttons for insert to authenticated, anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_buttons' and policyname = 'Allow update machine coffee buttons') then
    create policy "Allow update machine coffee buttons" on public.machine_coffee_buttons for update to authenticated, anon using (true) with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_recipe_items' and policyname = 'Allow read machine coffee recipe items') then
    create policy "Allow read machine coffee recipe items" on public.machine_coffee_recipe_items for select to authenticated, anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_recipe_items' and policyname = 'Allow insert machine coffee recipe items') then
    create policy "Allow insert machine coffee recipe items" on public.machine_coffee_recipe_items for insert to authenticated, anon with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'machine_coffee_recipe_items' and policyname = 'Allow update machine coffee recipe items') then
    create policy "Allow update machine coffee recipe items" on public.machine_coffee_recipe_items for update to authenticated, anon using (true) with check (true);
  end if;
end;
$$;
