alter table public.machine_planogram_slots
  add column if not exists settlement_type text not null default 'none'
    check (settlement_type in ('none', 'subsidy_receivable', 'partner_fee_payable')),
  add column if not exists settlement_amount_czk numeric(10,2) not null default 0,
  add column if not exists settlement_partner text,
  add column if not exists settlement_billing_enabled boolean not null default false,
  add column if not exists settlement_note text;

update public.machine_planogram_slots
set
  settlement_type = case
    when coalesce(subsidy_amount_czk, 0) > 0 then 'subsidy_receivable'
    else settlement_type
  end,
  settlement_amount_czk = case
    when coalesce(subsidy_amount_czk, 0) > 0 then subsidy_amount_czk
    else settlement_amount_czk
  end,
  settlement_partner = coalesce(settlement_partner, subsidy_payer),
  settlement_billing_enabled = settlement_billing_enabled or coalesce(subsidy_billing_enabled, false),
  settlement_note = coalesce(settlement_note, subsidy_note)
where coalesce(subsidy_amount_czk, 0) > 0;

create index if not exists machine_planogram_slots_settlement_idx
  on public.machine_planogram_slots (machine_id, settlement_type, settlement_billing_enabled)
  where settlement_type <> 'none';

create table if not exists public.telemetry_financial_settlements (
  id bigint generated by default as identity primary key,
  provider text not null,
  ingest_id bigint references public.telemetry_dex_ingests (id) on delete set null,
  machine_id bigint not null references public.machines (id) on delete cascade,
  planogram_slot_id bigint not null references public.machine_planogram_slots (id) on delete cascade,
  selection_code text not null,
  product_name text,
  product_sku text,
  settlement_type text not null
    check (settlement_type in ('subsidy_receivable', 'partner_fee_payable')),
  direction text not null
    check (direction in ('receivable', 'payable')),
  quantity numeric(12,3) not null,
  amount_per_unit_czk numeric(10,2) not null,
  total_amount_czk numeric(12,2) not null,
  customer_price_czk numeric(10,2),
  partner text,
  billing_enabled boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'invoiced', 'paid', 'cancelled')),
  source_event_at timestamp with time zone not null,
  note text,
  created_at timestamp with time zone not null default now(),
  unique (provider, ingest_id, machine_id, planogram_slot_id, selection_code, settlement_type)
);

create index if not exists telemetry_financial_settlements_machine_idx
  on public.telemetry_financial_settlements (machine_id, source_event_at desc);

create index if not exists telemetry_financial_settlements_status_idx
  on public.telemetry_financial_settlements (status, source_event_at desc);

alter table public.telemetry_financial_settlements enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_financial_settlements'
      and policyname = 'Allow read telemetry financial settlements'
  ) then
    create policy "Allow read telemetry financial settlements"
    on public.telemetry_financial_settlements
    for select
    to authenticated, anon
    using (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_financial_settlements'
      and policyname = 'Allow insert telemetry financial settlements'
  ) then
    create policy "Allow insert telemetry financial settlements"
    on public.telemetry_financial_settlements
    for insert
    to authenticated, anon
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_financial_settlements'
      and policyname = 'Allow update telemetry financial settlements'
  ) then
    create policy "Allow update telemetry financial settlements"
    on public.telemetry_financial_settlements
    for update
    to authenticated, anon
    using (true)
    with check (true);
  end if;
end;
$$;
