create table if not exists public.machine_planogram_slots (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  slot_code text not null,
  product_name text not null,
  product_sku text,
  price_czk numeric(10,2),
  capacity_units integer,
  current_units integer,
  fill_percent numeric(5,2),
  active boolean not null default true,
  sort_order integer not null default 0,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (machine_id, slot_code)
);

create index if not exists machine_planogram_slots_machine_idx
  on public.machine_planogram_slots (machine_id, sort_order asc, slot_code asc);

create or replace function public.set_machine_planogram_slots_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_machine_planogram_slots_updated_at on public.machine_planogram_slots;

create trigger trg_machine_planogram_slots_updated_at
before update on public.machine_planogram_slots
for each row
execute function public.set_machine_planogram_slots_updated_at();

alter table public.machine_planogram_slots enable row level security;

create policy "Allow read machine planogram slots"
on public.machine_planogram_slots
for select
to authenticated, anon
using (true);

create policy "Allow insert machine planogram slots"
on public.machine_planogram_slots
for insert
to authenticated, anon
with check (true);

create policy "Allow update machine planogram slots"
on public.machine_planogram_slots
for update
to authenticated, anon
using (true)
with check (true);
