create table if not exists public.machine_manual_counter_readings (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  visit_id bigint references public.route_machine_visits (id) on delete set null,
  route_plan_id bigint references public.route_plans (id) on delete set null,
  route_plan_stop_id bigint references public.route_plan_stops (id) on delete set null,
  reading_at timestamptz not null default now(),
  revenue_counter_czk numeric(12,2) not null default 0,
  portion_counter numeric(12,3) not null default 0,
  previous_reading_id bigint references public.machine_manual_counter_readings (id) on delete set null,
  previous_revenue_counter_czk numeric(12,2),
  previous_portion_counter numeric(12,3),
  revenue_delta_czk numeric(12,2) not null default 0,
  portion_delta numeric(12,3) not null default 0,
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (visit_id)
);

alter table public.route_machine_cash_reports
  add column if not exists manual_counter_reading_id bigint references public.machine_manual_counter_readings (id) on delete set null,
  add column if not exists manual_revenue_counter_czk numeric(12,2),
  add column if not exists manual_portion_counter numeric(12,3);

create index if not exists machine_manual_counter_readings_machine_idx
  on public.machine_manual_counter_readings (machine_id, reading_at desc);

create index if not exists machine_manual_counter_readings_visit_idx
  on public.machine_manual_counter_readings (visit_id);

create or replace function public.set_machine_manual_counter_readings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_machine_manual_counter_readings_updated_at on public.machine_manual_counter_readings;
create trigger trg_machine_manual_counter_readings_updated_at
before update on public.machine_manual_counter_readings
for each row
execute function public.set_machine_manual_counter_readings_updated_at();

alter table public.machine_manual_counter_readings enable row level security;

drop policy if exists "Allow read machine manual counter readings" on public.machine_manual_counter_readings;
create policy "Allow read machine manual counter readings" on public.machine_manual_counter_readings
for select to authenticated using (true);

drop policy if exists "Allow write machine manual counter readings" on public.machine_manual_counter_readings;
create policy "Allow write machine manual counter readings" on public.machine_manual_counter_readings
for all to authenticated using (true) with check (true);
