create table if not exists public.mobile_stock_requests (
  id bigint generated by default as identity primary key,
  request_type text not null
    check (request_type in (
      'vehicle_order',
      'vehicle_load',
      'vehicle_unload',
      'vehicle_sale',
      'vehicle_return',
      'vehicle_writeoff'
    )),
  status text not null default 'draft'
    check (status in (
      'draft',
      'requested',
      'picking',
      'ready',
      'confirmed',
      'cancelled'
    )),
  employee_id uuid references public.employees (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  attendance_day_id bigint references public.attendance_days (id) on delete set null,
  loading_session_id bigint references public.loading_sessions (id) on delete set null,
  source_stock_location_id bigint references public.stock_locations (id) on delete set null,
  target_stock_location_id bigint references public.stock_locations (id) on delete set null,
  requested_for_date date not null default current_date,
  prepared_by uuid references public.employees (id) on delete set null,
  prepared_at timestamp with time zone,
  confirmed_by uuid references public.employees (id) on delete set null,
  confirmed_at timestamp with time zone,
  source_document_number text,
  import_file_name text,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists mobile_stock_requests_status_idx
  on public.mobile_stock_requests (status, requested_for_date desc);

create index if not exists mobile_stock_requests_employee_idx
  on public.mobile_stock_requests (employee_id, requested_for_date desc);

create index if not exists mobile_stock_requests_vehicle_idx
  on public.mobile_stock_requests (vehicle_id, requested_for_date desc);

create index if not exists mobile_stock_requests_warehouse_idx
  on public.mobile_stock_requests (warehouse_id, requested_for_date desc);

create table if not exists public.mobile_stock_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.mobile_stock_requests (id) on delete cascade,
  product_id bigint references public.products (id) on delete set null,
  product_name text,
  sku text,
  unit text,
  requested_quantity numeric(12,3) not null default 0,
  prepared_quantity numeric(12,3),
  confirmed_quantity numeric(12,3),
  waste_reason text
    check (waste_reason in ('expired', 'damaged', 'opened', 'lost', 'other') or waste_reason is null),
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists mobile_stock_request_items_request_idx
  on public.mobile_stock_request_items (request_id);

create index if not exists mobile_stock_request_items_product_idx
  on public.mobile_stock_request_items (product_id);

create table if not exists public.mobile_service_followups (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests (id) on delete cascade,
  employee_id uuid references public.employees (id) on delete set null,
  attendance_day_id bigint references public.attendance_days (id) on delete set null,
  followup_reason text not null,
  next_required_at timestamp with time zone not null,
  escalation_level integer not null default 1,
  acknowledged_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists mobile_service_followups_request_idx
  on public.mobile_service_followups (service_request_id, next_required_at desc);

create index if not exists mobile_service_followups_employee_idx
  on public.mobile_service_followups (employee_id, acknowledged_at, next_required_at);

create or replace function public.set_mobile_workflows_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_mobile_stock_requests_updated_at on public.mobile_stock_requests;
create trigger trg_mobile_stock_requests_updated_at
before update on public.mobile_stock_requests
for each row
execute function public.set_mobile_workflows_updated_at();

drop trigger if exists trg_mobile_stock_request_items_updated_at on public.mobile_stock_request_items;
create trigger trg_mobile_stock_request_items_updated_at
before update on public.mobile_stock_request_items
for each row
execute function public.set_mobile_workflows_updated_at();

drop trigger if exists trg_mobile_service_followups_updated_at on public.mobile_service_followups;
create trigger trg_mobile_service_followups_updated_at
before update on public.mobile_service_followups
for each row
execute function public.set_mobile_workflows_updated_at();

alter table public.mobile_stock_requests enable row level security;
alter table public.mobile_stock_request_items enable row level security;
alter table public.mobile_service_followups enable row level security;

drop policy if exists "Allow read mobile stock requests" on public.mobile_stock_requests;
create policy "Allow read mobile stock requests"
on public.mobile_stock_requests
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert mobile stock requests" on public.mobile_stock_requests;
create policy "Allow insert mobile stock requests"
on public.mobile_stock_requests
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update mobile stock requests" on public.mobile_stock_requests;
create policy "Allow update mobile stock requests"
on public.mobile_stock_requests
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow read mobile stock request items" on public.mobile_stock_request_items;
create policy "Allow read mobile stock request items"
on public.mobile_stock_request_items
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert mobile stock request items" on public.mobile_stock_request_items;
create policy "Allow insert mobile stock request items"
on public.mobile_stock_request_items
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update mobile stock request items" on public.mobile_stock_request_items;
create policy "Allow update mobile stock request items"
on public.mobile_stock_request_items
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow read mobile service followups" on public.mobile_service_followups;
create policy "Allow read mobile service followups"
on public.mobile_service_followups
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert mobile service followups" on public.mobile_service_followups;
create policy "Allow insert mobile service followups"
on public.mobile_service_followups
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update mobile service followups" on public.mobile_service_followups;
create policy "Allow update mobile service followups"
on public.mobile_service_followups
for update
to authenticated, anon
using (true)
with check (true);
