create table if not exists public.route_machine_visits (
  id bigint generated by default as identity primary key,
  client_uuid uuid not null default gen_random_uuid(),
  route_plan_id bigint references public.route_plans (id) on delete set null,
  route_plan_stop_id bigint references public.route_plan_stops (id) on delete set null,
  machine_id bigint not null references public.machines (id) on delete cascade,
  employee_id uuid references public.employees (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  visit_date date not null default current_date,
  machine_kind text not null default 'food'
    check (machine_kind in ('food', 'coffee', 'other')),
  status text not null default 'draft'
    check (status in ('draft', 'arrived', 'completed', 'skipped', 'sync_error')),
  telemetry_provider text,
  telemetry_external_machine_id text,
  telemetry_last_seen_at timestamptz,
  telemetry_snapshot jsonb not null default '{}'::jsonb,
  arrived_at timestamptz,
  completed_at timestamptz,
  skipped_at timestamptz,
  skip_reason text,
  operator_note text,
  offline_created_at timestamptz,
  synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_uuid)
);

create table if not exists public.route_machine_visit_items (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.route_machine_visits (id) on delete cascade,
  client_uuid uuid not null default gen_random_uuid(),
  machine_id bigint not null references public.machines (id) on delete cascade,
  item_kind text not null default 'food_slot'
    check (item_kind in ('food_slot', 'coffee_container', 'coffee_button', 'service_item')),
  planogram_slot_id bigint references public.machine_planogram_slots (id) on delete set null,
  coffee_container_id bigint references public.machine_coffee_containers (id) on delete set null,
  coffee_button_id bigint references public.machine_coffee_buttons (id) on delete set null,
  physical_position_label text,
  telemetry_key text,
  planned_product_id bigint references public.products (id) on delete set null,
  planned_product_sku text,
  planned_product_name text,
  actual_product_id bigint references public.products (id) on delete set null,
  actual_product_sku text,
  actual_product_name text,
  sale_price_czk numeric(10,2),
  system_current_quantity numeric(12,3),
  actual_before_quantity numeric(12,3),
  suggested_add_quantity numeric(12,3),
  actual_add_quantity numeric(12,3) not null default 0,
  removed_quantity numeric(12,3) not null default 0,
  final_quantity numeric(12,3),
  capacity_quantity numeric(12,3),
  unit text not null default 'ks',
  issue_type text not null default 'none'
    check (issue_type in ('none', 'substitution', 'expired', 'shaken', 'damaged', 'missing_stock', 'telemetry_mismatch', 'other')),
  substitution_reason text,
  operator_note text,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_uuid)
);

create table if not exists public.route_machine_visit_checks (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.route_machine_visits (id) on delete cascade,
  check_key text not null,
  label text not null,
  required boolean not null default true,
  status text not null default 'pending'
    check (status in ('pending', 'done', 'not_applicable')),
  assigned_payload jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  operator_note text,
  created_at timestamptz not null default now(),
  unique (visit_id, check_key)
);

create table if not exists public.route_machine_cash_reports (
  id bigint generated by default as identity primary key,
  visit_id bigint not null references public.route_machine_visits (id) on delete cascade,
  machine_id bigint not null references public.machines (id) on delete cascade,
  expected_cash_czk numeric(12,2),
  expected_card_czk numeric(12,2),
  expected_total_czk numeric(12,2),
  operator_bag_label text,
  operator_collected_confirmed boolean not null default false,
  operator_collected_at timestamptz,
  supervisor_counted_cash_czk numeric(12,2),
  supervisor_counted_by uuid references public.employees (id) on delete set null,
  supervisor_counted_at timestamptz,
  difference_cash_czk numeric(12,2)
    generated always as (
      case
        when expected_cash_czk is null or supervisor_counted_cash_czk is null then null
        else supervisor_counted_cash_czk - expected_cash_czk
      end
    ) stored,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (visit_id)
);

create index if not exists route_machine_visits_route_idx
  on public.route_machine_visits (route_plan_id, visit_date, status);

create index if not exists route_machine_visits_machine_idx
  on public.route_machine_visits (machine_id, visit_date desc);

create index if not exists route_machine_visit_items_visit_idx
  on public.route_machine_visit_items (visit_id, item_kind);

create index if not exists route_machine_cash_reports_machine_idx
  on public.route_machine_cash_reports (machine_id, created_at desc);

create or replace function public.set_mobile_route_execution_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_route_machine_visits_updated_at on public.route_machine_visits;
create trigger trg_route_machine_visits_updated_at
before update on public.route_machine_visits
for each row
execute function public.set_mobile_route_execution_updated_at();

drop trigger if exists trg_route_machine_visit_items_updated_at on public.route_machine_visit_items;
create trigger trg_route_machine_visit_items_updated_at
before update on public.route_machine_visit_items
for each row
execute function public.set_mobile_route_execution_updated_at();

drop trigger if exists trg_route_machine_cash_reports_updated_at on public.route_machine_cash_reports;
create trigger trg_route_machine_cash_reports_updated_at
before update on public.route_machine_cash_reports
for each row
execute function public.set_mobile_route_execution_updated_at();

alter table public.route_machine_visits enable row level security;
alter table public.route_machine_visit_items enable row level security;
alter table public.route_machine_visit_checks enable row level security;
alter table public.route_machine_cash_reports enable row level security;

drop policy if exists "Allow read route machine visits" on public.route_machine_visits;
create policy "Allow read route machine visits" on public.route_machine_visits
for select to authenticated, anon using (true);

drop policy if exists "Allow write route machine visits" on public.route_machine_visits;
create policy "Allow write route machine visits" on public.route_machine_visits
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read route machine visit items" on public.route_machine_visit_items;
create policy "Allow read route machine visit items" on public.route_machine_visit_items
for select to authenticated, anon using (true);

drop policy if exists "Allow write route machine visit items" on public.route_machine_visit_items;
create policy "Allow write route machine visit items" on public.route_machine_visit_items
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read route machine visit checks" on public.route_machine_visit_checks;
create policy "Allow read route machine visit checks" on public.route_machine_visit_checks
for select to authenticated, anon using (true);

drop policy if exists "Allow write route machine visit checks" on public.route_machine_visit_checks;
create policy "Allow write route machine visit checks" on public.route_machine_visit_checks
for all to authenticated, anon using (true) with check (true);

drop policy if exists "Allow read route machine cash reports" on public.route_machine_cash_reports;
create policy "Allow read route machine cash reports" on public.route_machine_cash_reports
for select to authenticated, anon using (true);

drop policy if exists "Allow write route machine cash reports" on public.route_machine_cash_reports;
create policy "Allow write route machine cash reports" on public.route_machine_cash_reports
for all to authenticated, anon using (true) with check (true);
