-- OLVEND v39: průběžný přepočet mobilní trasy a schvalované nejeté zastávky.
create extension if not exists pgcrypto;

create table if not exists public.route_skip_approvers (
  employee_id uuid primary key references public.employees(id) on delete cascade,
  priority integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.route_skip_approvers(employee_id, priority, active)
select id, 10, true
from public.employees
where lower(email) = 'puncochar.m@olmika.cz'
on conflict (employee_id) do update set priority = excluded.priority, active = true;

create table if not exists public.route_stop_skip_requests (
  id uuid primary key default gen_random_uuid(),
  route_plan_id bigint not null references public.route_plans(id) on delete cascade,
  route_plan_stop_id bigint not null references public.route_plan_stops(id) on delete cascade,
  operator_employee_id uuid not null references public.employees(id) on delete restrict,
  approver_employee_id uuid not null references public.employees(id) on delete restrict,
  reason text not null check (reason in ('opening_hours','time_shortage','location_closed','no_access','machine_unavailable','other')),
  note text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  approval_token_hash text not null,
  requested_at timestamptz not null default now(),
  email_sent_at timestamptz,
  email_delivery_id text,
  mail_error text,
  decided_at timestamptz,
  decision_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists route_stop_skip_requests_one_pending_plan_idx
  on public.route_stop_skip_requests(route_plan_id)
  where status = 'pending';
create index if not exists route_stop_skip_requests_operator_idx
  on public.route_stop_skip_requests(operator_employee_id, requested_at desc);
create unique index if not exists route_stop_skip_requests_token_idx
  on public.route_stop_skip_requests(approval_token_hash);

create table if not exists public.route_mobile_recalculations (
  id bigint generated by default as identity primary key,
  route_plan_id bigint not null references public.route_plans(id) on delete cascade,
  employee_id uuid references public.employees(id) on delete set null,
  trigger_key text not null,
  previous_stop_ids bigint[] not null,
  ordered_stop_ids bigint[] not null,
  provider text not null default 'google_routes',
  baseline_distance_meters integer,
  distance_meters integer,
  baseline_duration_seconds integer,
  duration_seconds integer,
  reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(route_plan_id, trigger_key)
);

alter table public.route_skip_approvers enable row level security;
alter table public.route_stop_skip_requests enable row level security;
alter table public.route_mobile_recalculations enable row level security;
revoke all on public.route_skip_approvers from anon, authenticated;
revoke all on public.route_stop_skip_requests from anon, authenticated;
revoke all on public.route_mobile_recalculations from anon, authenticated;

create or replace function public.set_route_skip_request_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists trg_route_skip_request_updated_at on public.route_stop_skip_requests;
create trigger trg_route_skip_request_updated_at before update on public.route_stop_skip_requests
for each row execute function public.set_route_skip_request_updated_at();

create or replace function public.guard_route_stop_skip_approval_v39()
returns trigger language plpgsql set search_path = public as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' and current_user not in ('postgres','supabase_admin') then
    if exists(select 1 from public.route_stop_skip_requests r where r.route_plan_id = new.route_plan_id and r.status = 'pending') then
      raise exception 'Trasa čeká na schválení nejeté zastávky.';
    end if;
    if new.status = 'skipped' and old.status is distinct from 'skipped'
       and not exists(select 1 from public.route_stop_skip_requests r where r.route_plan_stop_id = new.id and r.status = 'approved') then
      raise exception 'Nejetou zastávku musí nejdřív schválit vedoucí.';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists trg_guard_route_stop_skip_approval_v39 on public.route_plan_stops;
create trigger trg_guard_route_stop_skip_approval_v39 before update on public.route_plan_stops
for each row execute function public.guard_route_stop_skip_approval_v39();

create or replace function public.guard_route_plan_pending_skip_v39()
returns trigger language plpgsql set search_path = public as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' and current_user not in ('postgres','supabase_admin')
     and exists(select 1 from public.route_stop_skip_requests r where r.route_plan_id = new.id and r.status = 'pending')
     and (new.execution_status is distinct from old.execution_status or new.completed_at is distinct from old.completed_at) then
    raise exception 'Trasu nelze uzavřít, dokud čeká žádost o nejetí.';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_guard_route_plan_pending_skip_v39 on public.route_plans;
create trigger trg_guard_route_plan_pending_skip_v39 before update on public.route_plans
for each row execute function public.guard_route_plan_pending_skip_v39();

create or replace function public.guard_route_visit_pending_skip_v39()
returns trigger language plpgsql set search_path = public as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' and current_user not in ('postgres','supabase_admin')
     and new.route_plan_id is not null
     and exists(select 1 from public.route_stop_skip_requests r where r.route_plan_id = new.route_plan_id and r.status = 'pending') then
    raise exception 'Další automat se odemkne až po rozhodnutí o nejeté zastávce.';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_guard_route_visit_pending_skip_v39 on public.route_machine_visits;
create trigger trg_guard_route_visit_pending_skip_v39 before insert or update on public.route_machine_visits
for each row execute function public.guard_route_visit_pending_skip_v39();

create or replace function public.get_my_route_skip_requests_v39(p_route_plan_id bigint)
returns table(
  id uuid,
  route_plan_id bigint,
  route_plan_stop_id bigint,
  reason text,
  note text,
  status text,
  requested_at timestamptz,
  email_sent_at timestamptz,
  decided_at timestamptz,
  decision_note text,
  approver_name text
)
language plpgsql security definer set search_path = public
as $$
declare
  v_employee_id uuid;
begin
  select e.id into v_employee_id
  from public.employees e
  where e.auth_user_id = auth.uid() and e.active is true;
  if v_employee_id is null then raise exception 'Aktivní zaměstnanec nebyl nalezen.'; end if;
  if not exists(select 1 from public.route_plans p where p.id = p_route_plan_id and p.planned_employee_id = v_employee_id) then
    raise exception 'Trasa není přiřazena přihlášenému operátorovi.';
  end if;
  return query
  select r.id, r.route_plan_id, r.route_plan_stop_id, r.reason, r.note, r.status,
         r.requested_at, r.email_sent_at, r.decided_at, r.decision_note,
         trim(concat_ws(' ', a.name, a.surname)) as approver_name
  from public.route_stop_skip_requests r
  join public.employees a on a.id = r.approver_employee_id
  where r.route_plan_id = p_route_plan_id and r.operator_employee_id = v_employee_id
  order by r.requested_at desc;
end;
$$;
revoke all on function public.get_my_route_skip_requests_v39(bigint) from public, anon;
grant execute on function public.get_my_route_skip_requests_v39(bigint) to authenticated;

create or replace function public.cancel_my_route_skip_request_v39(p_request_id uuid)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare v_employee_id uuid;
begin
  select id into v_employee_id from public.employees where auth_user_id = auth.uid() and active is true;
  update public.route_stop_skip_requests
  set status = 'cancelled', decided_at = now(), decision_note = 'Zrušeno operátorem.'
  where id = p_request_id and operator_employee_id = v_employee_id and status = 'pending';
  return found;
end;
$$;
revoke all on function public.cancel_my_route_skip_request_v39(uuid) from public, anon;
grant execute on function public.cancel_my_route_skip_request_v39(uuid) to authenticated;

create or replace function public.apply_mobile_route_recalculation_v39(
  p_route_plan_id bigint,
  p_ordered_stop_ids bigint[],
  p_trigger_key text,
  p_metadata jsonb
)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_employee_id uuid;
  v_open_ids bigint[];
  v_closed_ids bigint[];
  v_id bigint;
  v_order integer := 0;
begin
  select id into v_employee_id from public.employees where auth_user_id = auth.uid() and active is true;
  if v_employee_id is null then raise exception 'Aktivní zaměstnanec nebyl nalezen.'; end if;
  perform 1 from public.route_plans where id = p_route_plan_id and planned_employee_id = v_employee_id for update;
  if not found then raise exception 'Trasa není přiřazena přihlášenému operátorovi.'; end if;
  if exists(select 1 from public.route_stop_skip_requests where route_plan_id = p_route_plan_id and status = 'pending') then
    raise exception 'Trasa čeká na schválení nejeté zastávky.';
  end if;

  select coalesce(array_agg(id order by stop_order), '{}'::bigint[]) into v_closed_ids
  from public.route_plan_stops
  where route_plan_id = p_route_plan_id and (status in ('done','completed','skipped') or completed_at is not null or skipped_at is not null);
  select coalesce(array_agg(id order by stop_order), '{}'::bigint[]) into v_open_ids
  from public.route_plan_stops
  where route_plan_id = p_route_plan_id and not (status in ('done','completed','skipped') or completed_at is not null or skipped_at is not null);

  if cardinality(v_open_ids) <> cardinality(coalesce(p_ordered_stop_ids, '{}'::bigint[]))
     or exists(select 1 from unnest(v_open_ids) x where not (x = any(p_ordered_stop_ids)))
     or exists(select 1 from unnest(p_ordered_stop_ids) x where not (x = any(v_open_ids))) then
    raise exception 'Pořadí neodpovídá aktuálně otevřeným zastávkám.';
  end if;

  update public.route_plan_stops set stop_order = stop_order + 1000000 where route_plan_id = p_route_plan_id;
  foreach v_id in array v_closed_ids loop
    v_order := v_order + 1;
    update public.route_plan_stops set stop_order = v_order where id = v_id;
  end loop;
  foreach v_id in array p_ordered_stop_ids loop
    v_order := v_order + 1;
    update public.route_plan_stops set stop_order = v_order where id = v_id;
  end loop;

  update public.route_plans
  set route_payload = jsonb_set(coalesce(route_payload, '{}'::jsonb), '{mobile_recalculation}', coalesce(p_metadata, '{}'::jsonb), true)
  where id = p_route_plan_id;

  insert into public.route_mobile_recalculations(
    route_plan_id, employee_id, trigger_key, previous_stop_ids, ordered_stop_ids, provider,
    baseline_distance_meters, distance_meters, baseline_duration_seconds, duration_seconds, reason, payload
  ) values (
    p_route_plan_id, v_employee_id, p_trigger_key, v_open_ids, p_ordered_stop_ids,
    coalesce(p_metadata->>'provider','google_routes'),
    nullif(p_metadata->>'baseline_distance_meters','')::integer,
    nullif(p_metadata->>'distance_meters','')::integer,
    nullif(p_metadata->>'baseline_duration_seconds','')::integer,
    nullif(p_metadata->>'duration_seconds','')::integer,
    p_metadata->>'reason', coalesce(p_metadata, '{}'::jsonb)
  ) on conflict(route_plan_id, trigger_key) do nothing;

  return jsonb_build_object('ok', true, 'ordered_stop_ids', p_ordered_stop_ids);
end;
$$;
revoke all on function public.apply_mobile_route_recalculation_v39(bigint,bigint[],text,jsonb) from public, anon;
grant execute on function public.apply_mobile_route_recalculation_v39(bigint,bigint[],text,jsonb) to authenticated;

create or replace function public.decide_route_stop_skip_v39(p_token text, p_decision text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_request public.route_stop_skip_requests%rowtype;
  v_stop public.route_plan_stops%rowtype;
  v_visit public.route_machine_visits%rowtype;
  v_now timestamptz := now();
begin
  if p_decision not in ('approve','reject') then raise exception 'Neplatné rozhodnutí.'; end if;
  select * into v_request from public.route_stop_skip_requests
  where approval_token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex') for update;
  if not found then raise exception 'Schvalovací odkaz není platný.'; end if;
  if v_request.status <> 'pending' then
    return jsonb_build_object('ok', true, 'status', v_request.status, 'already_decided', true);
  end if;
  if p_decision = 'reject' then
    update public.route_stop_skip_requests set status='rejected', decided_at=v_now, decision_note='Žádost byla zamítnuta.' where id=v_request.id;
    return jsonb_build_object('ok', true, 'status', 'rejected', 'route_plan_id', v_request.route_plan_id);
  end if;

  select * into v_stop from public.route_plan_stops where id=v_request.route_plan_stop_id for update;
  if not found or v_stop.route_plan_id <> v_request.route_plan_id then raise exception 'Zastávka už není dostupná.'; end if;
  if v_stop.status in ('done','completed','skipped') or v_stop.completed_at is not null or v_stop.skipped_at is not null then
    raise exception 'Zastávka už byla uzavřena.';
  end if;
  select * into v_visit from public.route_machine_visits
  where route_plan_stop_id=v_stop.id order by created_at desc limit 1 for update;
  if v_visit.id is not null and (
    exists(select 1 from public.route_machine_visit_items where visit_id=v_visit.id and accepted_at is not null)
    or exists(select 1 from public.route_machine_visit_checks where visit_id=v_visit.id and status='done')
    or exists(select 1 from public.route_machine_cash_reports where visit_id=v_visit.id)
    or exists(select 1 from public.machine_manual_counter_readings where visit_id=v_visit.id)
  ) then raise exception 'U automatu už je uložená práce; zastávku nelze schválit jako nejetou.'; end if;

  if v_visit.id is null then
    insert into public.route_machine_visits(route_plan_id,route_plan_stop_id,machine_id,employee_id,vehicle_id,visit_date,machine_kind,status,skipped_at,skip_reason,operator_note,offline_created_at,synced_at)
    select v_request.route_plan_id,v_stop.id,v_stop.machine_id,v_request.operator_employee_id,p.vehicle_id,p.planning_date,
           case when lower(coalesce(m.machine_type,m.name,'')) like any(array['%coffee%','%ká%','%kav%']) then 'coffee'
                when lower(coalesce(m.machine_type,m.name,'')) like any(array['%food%','%snack%','%baget%']) then 'food' else 'other' end,
           'skipped',v_now,v_request.reason,v_request.note,v_now,v_now
    from public.route_plans p left join public.machines m on m.id=v_stop.machine_id where p.id=v_request.route_plan_id;
  else
    update public.route_machine_visits set status='skipped',work_phase='picklist',food_preparation='{}'::jsonb,arrived_at=null,
      skipped_at=v_now,skip_reason=v_request.reason,operator_note=v_request.note,synced_at=v_now where id=v_visit.id;
  end if;
  update public.route_plan_stops set status='skipped',arrived_at=null,skipped_at=v_now where id=v_stop.id;
  update public.route_stop_skip_requests set status='approved',decided_at=v_now,decision_note='Nejetí schváleno.' where id=v_request.id;
  return jsonb_build_object('ok',true,'status','approved','route_plan_id',v_request.route_plan_id,'route_plan_stop_id',v_stop.id);
end;
$$;
revoke all on function public.decide_route_stop_skip_v39(text,text) from public, anon, authenticated;
grant execute on function public.decide_route_stop_skip_v39(text,text) to service_role;

comment on table public.route_stop_skip_requests is 'Žádosti operátorů o nejetí zastávky; další práce je blokována do rozhodnutí.';
comment on table public.route_mobile_recalculations is 'Audit každého průběžného přepočtu zbývající části mobilní trasy.';
