create table if not exists public.operational_requests (
  id bigint generated by default as identity primary key,
  request_kind text not null
    check (request_kind in ('equipment', 'vehicle_service', 'partner_delivery')),
  status text not null default 'new'
    check (status in (
      'new',
      'in_progress',
      'warehouse_queue',
      'picking',
      'ready',
      'billing_ready',
      'invoiced',
      'completed',
      'cancelled'
    )),
  title text not null,
  note text,
  need_timing text,
  employee_id uuid references public.employees (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  business_contact_id bigint references public.business_contacts (id) on delete set null,
  assigned_to uuid references public.employees (id) on delete set null,
  issued_by uuid references public.employees (id) on delete set null,
  issued_at timestamp with time zone,
  invoiced_at timestamp with time zone,
  invoice_id bigint,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists operational_requests_status_idx
  on public.operational_requests (status, created_at desc);

create index if not exists operational_requests_employee_idx
  on public.operational_requests (employee_id, created_at desc);

create index if not exists operational_requests_kind_idx
  on public.operational_requests (request_kind, status);

create index if not exists operational_requests_partner_idx
  on public.operational_requests (business_contact_id, created_at desc);

create table if not exists public.operational_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.operational_requests (id) on delete cascade,
  product_id bigint references public.products (id) on delete set null,
  product_name text not null,
  sku text,
  unit text not null default 'ks',
  requested_quantity numeric(12,3) not null default 0 check (requested_quantity >= 0),
  issued_quantity numeric(12,3) check (issued_quantity is null or issued_quantity >= 0),
  unit_price_without_vat numeric(12,2),
  vat_rate numeric(5,2),
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists operational_request_items_request_idx
  on public.operational_request_items (request_id);

create index if not exists operational_request_items_product_idx
  on public.operational_request_items (product_id);

create or replace function public.set_operational_requests_updated_at_v18()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_operational_requests_updated_at_v18 on public.operational_requests;
create trigger trg_operational_requests_updated_at_v18
before update on public.operational_requests
for each row
execute function public.set_operational_requests_updated_at_v18();

drop trigger if exists trg_operational_request_items_updated_at_v18 on public.operational_request_items;
create trigger trg_operational_request_items_updated_at_v18
before update on public.operational_request_items
for each row
execute function public.set_operational_requests_updated_at_v18();

alter table public.operational_requests enable row level security;
alter table public.operational_request_items enable row level security;

drop policy if exists "Allow read operational requests" on public.operational_requests;
create policy "Allow read operational requests"
on public.operational_requests for select
to authenticated
using (true);

drop policy if exists "Allow insert operational requests" on public.operational_requests;
create policy "Allow insert operational requests"
on public.operational_requests for insert
to authenticated
with check (true);

drop policy if exists "Allow update operational requests" on public.operational_requests;
create policy "Allow update operational requests"
on public.operational_requests for update
to authenticated
using (true)
with check (true);

drop policy if exists "Allow read operational request items" on public.operational_request_items;
create policy "Allow read operational request items"
on public.operational_request_items for select
to authenticated
using (true);

drop policy if exists "Allow insert operational request items" on public.operational_request_items;
create policy "Allow insert operational request items"
on public.operational_request_items for insert
to authenticated
with check (true);

drop policy if exists "Allow update operational request items" on public.operational_request_items;
create policy "Allow update operational request items"
on public.operational_request_items for update
to authenticated
using (true)
with check (true);

create or replace function public.create_operational_request_v18(
  p_request jsonb,
  p_items jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.operational_requests%rowtype;
  v_item jsonb;
  v_employee_id uuid;
begin
  if p_request is null or jsonb_typeof(p_request) <> 'object' then
    raise exception 'Chybí data požadavku.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Položky požadavku musí být pole.';
  end if;

  select id into v_employee_id
  from public.employees
  where auth_user_id = auth.uid()
  limit 1;

  if v_employee_id is null then
    raise exception 'Přihlášený účet není spojen se zaměstnancem.';
  end if;

  insert into public.operational_requests (
    request_kind,
    status,
    title,
    note,
    need_timing,
    employee_id,
    vehicle_id,
    warehouse_id,
    business_contact_id
  ) values (
    nullif(p_request->>'request_kind', ''),
    coalesce(nullif(p_request->>'status', ''), 'new'),
    nullif(p_request->>'title', ''),
    nullif(p_request->>'note', ''),
    nullif(p_request->>'need_timing', ''),
    v_employee_id,
    nullif(p_request->>'vehicle_id', '')::bigint,
    nullif(p_request->>'warehouse_id', '')::bigint,
    nullif(p_request->>'business_contact_id', '')::bigint
  )
  returning * into v_request;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    insert into public.operational_request_items (
      request_id,
      product_id,
      product_name,
      sku,
      unit,
      requested_quantity,
      unit_price_without_vat,
      vat_rate,
      note
    ) values (
      v_request.id,
      nullif(v_item->>'product_id', '')::bigint,
      nullif(v_item->>'product_name', ''),
      nullif(v_item->>'sku', ''),
      coalesce(nullif(v_item->>'unit', ''), 'ks'),
      coalesce(nullif(v_item->>'requested_quantity', '')::numeric, 0),
      nullif(v_item->>'unit_price_without_vat', '')::numeric,
      nullif(v_item->>'vat_rate', '')::numeric,
      nullif(v_item->>'note', '')
    );
  end loop;

  if v_request.request_kind = 'partner_delivery' and not exists (
    select 1 from public.operational_request_items where request_id = v_request.id and requested_quantity > 0
  ) then
    raise exception 'Dodávka partnerovi musí obsahovat alespoň jednu položku.';
  end if;

  return jsonb_build_object('id', v_request.id, 'status', v_request.status);
end;
$$;

create or replace function public.confirm_partner_delivery_issue_v18(
  p_request_id bigint,
  p_items jsonb,
  p_employee_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.operational_requests%rowtype;
  v_item_json jsonb;
  v_item public.operational_request_items%rowtype;
  v_location_id bigint;
  v_quantity numeric(12,3);
  v_remaining numeric(12,3);
  v_take numeric(12,3);
  v_total numeric(14,3) := 0;
  v_value numeric(14,2) := 0;
  v_balance record;
  v_reference_id text;
  v_current_employee public.employees%rowtype;
begin
  if p_request_id is null then
    raise exception 'Chybí identifikátor požadavku.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Položky výdeje musí být pole.';
  end if;

  select * into v_current_employee
  from public.employees
  where auth_user_id = auth.uid()
  limit 1;

  if v_current_employee.id is null then
    raise exception 'Přihlášený účet není spojen se zaměstnancem.';
  end if;
  if not (
    lower(coalesce(v_current_employee.role, '')) like '%sklad%'
    or lower(coalesce(v_current_employee.role, '')) like '%admin%'
    or lower(coalesce(v_current_employee.role, '')) like '%manaž%'
    or lower(coalesce(v_current_employee.role, '')) like '%manaz%'
    or lower(coalesce(v_current_employee.role, '')) like '%manager%'
    or lower(coalesce(v_current_employee.role, '')) like '%vedouc%'
    or lower(coalesce(v_current_employee.role, '')) like '%majitel%'
  ) then
    raise exception 'Skladový výdej může potvrdit pouze sklad nebo vedení.';
  end if;
  if p_employee_id is not null and p_employee_id <> v_current_employee.id then
    raise exception 'Výdej nelze zapsat za jiného zaměstnance.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('partner-delivery:' || p_request_id::text, 0));

  select *
  into v_request
  from public.operational_requests
  where id = p_request_id
  for update;

  if v_request.id is null then
    raise exception 'Požadavek #% neexistuje.', p_request_id;
  end if;
  if v_request.request_kind <> 'partner_delivery' then
    raise exception 'Požadavek #% není dodávka partnerovi.', p_request_id;
  end if;
  if v_request.status in ('billing_ready', 'invoiced') then
    return jsonb_build_object(
      'request_id', p_request_id,
      'status', v_request.status,
      'skipped', true
    );
  end if;
  if v_request.status = 'cancelled' then
    raise exception 'Zrušený požadavek nelze vyskladnit.';
  end if;

  select sl.id
  into v_location_id
  from public.stock_locations sl
  left join public.warehouses w on w.id = sl.warehouse_id
  where sl.location_type = 'warehouse'
    and sl.active = true
    and (v_request.warehouse_id is null or sl.warehouse_id = v_request.warehouse_id)
    and upper(coalesce(w.code, '')) <> 'AUTOMATY'
  order by
    case when sl.warehouse_id = v_request.warehouse_id then 0 else 1 end,
    sl.id
  limit 1;

  if v_location_id is null then
    raise exception 'Pro požadavek není nalezen aktivní sklad.';
  end if;

  v_reference_id := 'partner-delivery:' || p_request_id::text;

  for v_item_json in
    select value from jsonb_array_elements(p_items)
  loop
    select *
    into v_item
    from public.operational_request_items
    where id = nullif(v_item_json->>'item_id', '')::bigint
      and request_id = p_request_id
    for update;

    if v_item.id is null then
      raise exception 'Položka výdeje nepatří k požadavku #%.' , p_request_id;
    end if;
    if v_item.product_id is null then
      raise exception 'Položka % není napojena na produkt.', v_item.product_name;
    end if;

    v_quantity := coalesce(nullif(v_item_json->>'issued_quantity', '')::numeric, 0);
    if v_quantity < 0 then
      raise exception 'Vydané množství nesmí být záporné.';
    end if;

    update public.operational_request_items
    set issued_quantity = round(v_quantity, 3)
    where id = v_item.id;

    if v_quantity = 0 then
      continue;
    end if;

    v_remaining := v_quantity;
    for v_balance in
      select
        slb.id,
        slb.batch_id,
        slb.quantity_on_hand,
        coalesce(ib.use_by_date, ib.best_before_date) as expiry_date
      from public.stock_location_balances slb
      left join public.inventory_batches ib on ib.id = slb.batch_id
      where slb.stock_location_id = v_location_id
        and slb.product_id = v_item.product_id
        and slb.quantity_on_hand > 0
      order by
        coalesce(ib.use_by_date, ib.best_before_date) asc nulls last,
        slb.id
      for update of slb
    loop
      exit when v_remaining <= 0;
      v_take := least(v_remaining, v_balance.quantity_on_hand);

      update public.stock_location_balances
      set
        quantity_on_hand = round((quantity_on_hand - v_take)::numeric, 3),
        updated_at = now()
      where id = v_balance.id;

      insert into public.stock_movements_v13 (
        product_id,
        batch_id,
        from_stock_location_id,
        to_stock_location_id,
        movement_type,
        quantity_base_units,
        unit_price,
        reference_type,
        reference_id,
        note,
        created_by
      ) values (
        v_item.product_id,
        v_balance.batch_id,
        v_location_id,
        null,
        'sale',
        v_take,
        v_item.unit_price_without_vat,
        'operational_partner_delivery',
        v_reference_id,
        'Dodávka partnerovi: ' || v_request.title,
        v_current_employee.id
      );

      v_remaining := round((v_remaining - v_take)::numeric, 3);
    end loop;

    if v_remaining > 0.0001 then
      raise exception 'Nedostatek zásoby: % (požadováno %, chybí %).',
        v_item.product_name,
        v_quantity,
        v_remaining;
    end if;

    v_total := v_total + v_quantity;
    v_value := v_value + round((v_quantity * coalesce(v_item.unit_price_without_vat, 0))::numeric, 2);
  end loop;

  if v_total <= 0 then
    raise exception 'Pro výdej musí být potvrzena alespoň jedna položka.';
  end if;

  update public.operational_requests
  set
    status = 'billing_ready',
    issued_by = v_current_employee.id,
    issued_at = now(),
    updated_at = now()
  where id = p_request_id;

  return jsonb_build_object(
    'request_id', p_request_id,
    'status', 'billing_ready',
    'issued_quantity', round(v_total, 3),
    'value_without_vat', round(v_value, 2),
    'stock_location_id', v_location_id
  );
end;
$$;

grant select, insert, update on public.operational_requests to authenticated;
grant select, insert, update on public.operational_request_items to authenticated;
grant usage, select on sequence public.operational_requests_id_seq to authenticated;
grant usage, select on sequence public.operational_request_items_id_seq to authenticated;
revoke all on function public.create_operational_request_v18(jsonb, jsonb) from public, anon;
revoke all on function public.confirm_partner_delivery_issue_v18(bigint, jsonb, uuid) from public, anon;
grant execute on function public.create_operational_request_v18(jsonb, jsonb) to authenticated;
grant execute on function public.confirm_partner_delivery_issue_v18(bigint, jsonb, uuid) to authenticated;

comment on table public.operational_requests is
  'Provozní požadavky z mobilu včetně dodávek partnerům, které po výdeji přecházejí k fakturaci.';

comment on function public.confirm_partner_delivery_issue_v18(bigint, jsonb, uuid) is
  'Atomicky odečte skutečně vydané zboží ze skladu metodou FEFO a předá partnerovu dodávku k fakturaci.';
