begin;

create table if not exists public.operator_territory_assignments (
  location_id bigint primary key references public.locations(id) on delete cascade,
  primary_employee_id uuid references public.employees(id) on delete set null,
  backup_employee_id uuid references public.employees(id) on delete set null,
  assignment_scope text not null default 'location'
    check (assignment_scope in ('location', 'machines')),
  selected_machine_ids bigint[] not null default '{}',
  effective_from date not null default current_date,
  locked boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.operator_territory_assignment_history (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  primary_employee_id uuid references public.employees(id) on delete set null,
  backup_employee_id uuid references public.employees(id) on delete set null,
  assignment_scope text not null,
  selected_machine_ids bigint[] not null default '{}',
  effective_from date not null,
  note text,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null
);

alter table public.operator_territory_assignments enable row level security;
alter table public.operator_territory_assignment_history enable row level security;

drop policy if exists operator_territories_read on public.operator_territory_assignments;
create policy operator_territories_read
on public.operator_territory_assignments for select
to authenticated using (true);

drop policy if exists operator_territories_manage on public.operator_territory_assignments;
create policy operator_territories_manage
on public.operator_territory_assignments for all
to authenticated
using (public.has_manager_access())
with check (public.has_manager_access());

drop policy if exists operator_territory_history_read on public.operator_territory_assignment_history;
create policy operator_territory_history_read
on public.operator_territory_assignment_history for select
to authenticated using (public.has_manager_access());

create or replace function public.save_operator_territory_assignment(
  p_location_id bigint,
  p_primary_employee_id uuid,
  p_backup_employee_id uuid,
  p_assignment_scope text,
  p_selected_machine_ids bigint[] default '{}',
  p_effective_from date default current_date,
  p_note text default null
) returns public.operator_territory_assignments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.operator_territory_assignments;
  v_machine_ids bigint[] := coalesce(p_selected_machine_ids, '{}');
begin
  if not public.has_manager_access() then
    raise exception 'Tuto změnu může uložit pouze manažer.' using errcode = '42501';
  end if;
  if p_assignment_scope not in ('location', 'machines') then
    raise exception 'Neplatný rozsah přiřazení.';
  end if;
  if p_primary_employee_id = p_backup_employee_id and p_primary_employee_id is not null then
    raise exception 'Hlavní operátor a náhradník musí být různí.';
  end if;
  if p_assignment_scope = 'machines' then
    if cardinality(v_machine_ids) = 0 then
      raise exception 'Vyberte alespoň jeden automat.';
    end if;
    if exists (
      select 1 from unnest(v_machine_ids) machine_id
      where not exists (
        select 1 from public.machines m
        where m.id = machine_id and m.location_id = p_location_id and m.active is distinct from false
      )
    ) then
      raise exception 'Vybrané automaty nepatří do této lokality.';
    end if;
  else
    v_machine_ids := '{}';
  end if;

  insert into public.operator_territory_assignments (
    location_id, primary_employee_id, backup_employee_id, assignment_scope,
    selected_machine_ids, effective_from, locked, note, updated_at, updated_by
  ) values (
    p_location_id, p_primary_employee_id, p_backup_employee_id, p_assignment_scope,
    v_machine_ids, coalesce(p_effective_from, current_date), true, nullif(trim(p_note), ''), now(), auth.uid()
  )
  on conflict (location_id) do update set
    primary_employee_id = excluded.primary_employee_id,
    backup_employee_id = excluded.backup_employee_id,
    assignment_scope = excluded.assignment_scope,
    selected_machine_ids = excluded.selected_machine_ids,
    effective_from = excluded.effective_from,
    locked = true,
    note = excluded.note,
    updated_at = now(),
    updated_by = auth.uid()
  returning * into v_row;

  insert into public.operator_territory_assignment_history (
    location_id, primary_employee_id, backup_employee_id, assignment_scope,
    selected_machine_ids, effective_from, note, changed_by
  ) values (
    v_row.location_id, v_row.primary_employee_id, v_row.backup_employee_id,
    v_row.assignment_scope, v_row.selected_machine_ids, v_row.effective_from,
    v_row.note, auth.uid()
  );
  return v_row;
end;
$$;

grant select on public.operator_territory_assignments to authenticated;
grant select on public.operator_territory_assignment_history to authenticated;
grant execute on function public.save_operator_territory_assignment(bigint, uuid, uuid, text, bigint[], date, text) to authenticated;

insert into public.operator_territory_assignments (
  location_id, primary_employee_id, backup_employee_id, assignment_scope,
  selected_machine_ids, effective_from, locked, note
)
select ranked.location_id,
       (array_agg(ranked.employee_id order by ranked.rank_no))[1],
       (array_agg(ranked.employee_id order by ranked.rank_no))[2],
       'location', '{}', current_date, true,
       'Výchozí přiřazení podle četnosti tras za posledních 90 dní.'
from (
  select counts.location_id, counts.employee_id,
         row_number() over (partition by counts.location_id order by counts.visits desc, counts.employee_id) as rank_no
  from (
    select stops.location_id, plans.planned_employee_id as employee_id, count(*) as visits
    from public.route_plan_stops stops
    join public.route_plans plans on plans.id = stops.route_plan_id
    join public.locations locations on locations.id = stops.location_id
    join public.employees employees on employees.id = plans.planned_employee_id
    where plans.planning_date >= current_date - 90
      and plans.execution_status is distinct from 'cancelled'
      and stops.location_id is not null
      and locations.active is distinct from false
      and employees.active is distinct from false
    group by stops.location_id, plans.planned_employee_id
  ) counts
) ranked
where ranked.rank_no <= 2
group by ranked.location_id
on conflict (location_id) do nothing;

commit;
