-- Reusable monthly preparation of partner subsidy invoices and email evidence.
create table if not exists public.partner_billing_profiles (
  id bigint generated by default as identity primary key,
  location_id bigint not null unique references public.locations (id) on delete cascade,
  business_contact_id bigint references public.business_contacts (id) on delete set null,
  device_label text not null,
  invoice_description_template text not null default 'Úhrada za umístění zařízení {device} - {month}/{year}',
  vat_rate numeric(5,2) not null default 21,
  rounding_mode text not null default 'integer'
    check (rounding_mode in ('none', 'integer', 'tenth')),
  customer_order_number text,
  email_recipient text,
  attachment_mode text not null default 'optional'
    check (attachment_mode in ('automatic', 'optional', 'none')),
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists partner_billing_profiles_contact_idx
  on public.partner_billing_profiles (business_contact_id);

drop trigger if exists trg_partner_billing_profiles_updated_at on public.partner_billing_profiles;
create trigger trg_partner_billing_profiles_updated_at
before update on public.partner_billing_profiles
for each row execute function public.set_updated_at();

alter table public.partner_billing_profiles enable row level security;

drop policy if exists "Allow read partner billing profiles" on public.partner_billing_profiles;
create policy "Allow read partner billing profiles"
on public.partner_billing_profiles for select to authenticated using (true);

drop policy if exists "Allow insert partner billing profiles" on public.partner_billing_profiles;
create policy "Allow insert partner billing profiles"
on public.partner_billing_profiles for insert to authenticated with check (true);

drop policy if exists "Allow update partner billing profiles" on public.partner_billing_profiles;
create policy "Allow update partner billing profiles"
on public.partner_billing_profiles for update to authenticated using (true) with check (true);

-- AVE terms recovered from the already issued May and June invoices.
insert into public.location_financial_rules (
  location_id, scope_type, settlement_type, direction, amount, currency,
  unit, periodicity, valid_from, note
)
select
  17, 'location', 'subsidy', 'from_partner', 3, 'CZK',
  'porce', 'monthly', date '2026-01-01',
  'Doplatek 3 Kč za každou vydanou porci; ověřeno podle faktur za 5/2026 a 6/2026.'
where not exists (
  select 1
  from public.location_financial_rules rule
  where rule.location_id = 17
    and rule.direction = 'from_partner'
    and rule.settlement_type in ('subsidy', 'per_unit')
    and coalesce(rule.valid_to, date '9999-12-31') >= date '2026-01-01'
);

insert into public.partner_billing_profiles (
  location_id, business_contact_id, device_label, invoice_description_template,
  vat_rate, rounding_mode, customer_order_number, email_recipient,
  attachment_mode, active
)
values (
  17, 7, 'X2 E', 'Úhrada za umístění zařízení {device} - {month}/{year}',
  21, 'integer', 'C08450040694', 'breclav@ave.cz',
  'automatic', true
)
on conflict (location_id) do update set
  business_contact_id = excluded.business_contact_id,
  device_label = excluded.device_label,
  invoice_description_template = excluded.invoice_description_template,
  vat_rate = excluded.vat_rate,
  rounding_mode = excluded.rounding_mode,
  customer_order_number = excluded.customer_order_number,
  email_recipient = excluded.email_recipient,
  attachment_mode = excluded.attachment_mode,
  active = true,
  updated_at = now();
