-- Obedy Blucina: OLVEND sends monthly evidence, the partner invoices OLVEND.

begin;

alter table public.partner_billing_profiles
  add column if not exists billing_direction text not null default 'from_partner',
  add column if not exists rate_includes_vat boolean not null default false;

alter table public.partner_billing_profiles
  drop constraint if exists partner_billing_profiles_billing_direction_check;

alter table public.partner_billing_profiles
  add constraint partner_billing_profiles_billing_direction_check
  check (billing_direction in ('from_partner', 'to_partner'));

create table if not exists public.partner_settlement_reports (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations (id) on delete cascade,
  business_contact_id bigint references public.business_contacts (id) on delete set null,
  billing_direction text not null check (billing_direction in ('from_partner', 'to_partner')),
  period_month date not null,
  quantity numeric(14,3) not null default 0,
  unit_gross_rate numeric(12,4) not null default 0,
  vat_rate numeric(5,2) not null default 21,
  net_amount numeric(14,2) not null default 0,
  vat_amount numeric(14,2) not null default 0,
  gross_amount numeric(14,2) not null default 0,
  recipient_email text,
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'invoiced', 'failed', 'cancelled')),
  sent_at timestamp with time zone,
  invoice_received_at timestamp with time zone,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (location_id, period_month, billing_direction)
);

drop trigger if exists trg_partner_settlement_reports_updated_at on public.partner_settlement_reports;
create trigger trg_partner_settlement_reports_updated_at
before update on public.partner_settlement_reports
for each row execute function public.set_updated_at();

alter table public.partner_settlement_reports enable row level security;

drop policy if exists "Allow read partner settlement reports" on public.partner_settlement_reports;
create policy "Allow read partner settlement reports"
on public.partner_settlement_reports for select to authenticated using (true);

drop policy if exists "Allow insert partner settlement reports" on public.partner_settlement_reports;
create policy "Allow insert partner settlement reports"
on public.partner_settlement_reports for insert to authenticated with check (true);

drop policy if exists "Allow update partner settlement reports" on public.partner_settlement_reports;
create policy "Allow update partner settlement reports"
on public.partner_settlement_reports for update to authenticated using (true) with check (true);

insert into public.business_contacts (
  contact_type, name, name_norm, company_id, tax_id, contact_name, email, phone,
  billing_address, default_due_days, note, active, source
)
values (
  'supplier',
  'Obědy Blučina - Pavel Šťastný',
  public.olvend_contact_norm('Obědy Blučina - Pavel Šťastný'),
  '42313848',
  'CZ7105293877',
  'Pavel Šťastný',
  'pav.stastny@volny.cz',
  '+420 775 343 230',
  'Sokolská 30, 664 56 Blučina',
  14,
  'Partner vystavuje fakturu OLVENDu podle měsíčního podkladu z automatu EV 117.',
  true,
  'partner_payable_obedy_blucina'
)
on conflict (contact_type, name_norm) do update set
  company_id = excluded.company_id,
  tax_id = excluded.tax_id,
  contact_name = excluded.contact_name,
  email = excluded.email,
  phone = excluded.phone,
  billing_address = excluded.billing_address,
  default_due_days = excluded.default_due_days,
  note = excluded.note,
  active = true,
  source = excluded.source,
  updated_at = now();

insert into public.location_financial_rules (
  location_id, scope_type, settlement_type, direction, amount, currency,
  unit, periodicity, valid_from, note
)
select
  70, 'location', 'per_unit', 'to_partner', 5, 'CZK',
  'porce', 'monthly', date '2026-08-01',
  'Partner fakturuje OLVENDu 5 Kč včetně 21% DPH za každou vydanou porci.'
where not exists (
  select 1
  from public.location_financial_rules rule
  where rule.location_id = 70
    and rule.direction = 'to_partner'
    and rule.settlement_type = 'per_unit'
    and coalesce(rule.valid_to, date '9999-12-31') >= date '2026-08-01'
);

insert into public.partner_billing_profiles (
  location_id, business_contact_id, device_label, invoice_description_template,
  vat_rate, unit_vat_rate, billing_scope, billing_direction, rate_includes_vat,
  quantity_label, quantity_unit, fixed_monthly_amount, fixed_vat_rate,
  rounding_mode, email_recipient, attachment_mode, billing_data_complete_from,
  billing_data_note, active
)
select
  70,
  contact.id,
  'Luce X2 I · EV 117',
  'Podklad pro fakturaci provozu zařízení {device} - {month}/{year}',
  21,
  21,
  'all_sales',
  'to_partner',
  true,
  'Vydané porce',
  'porcí',
  0,
  21,
  'none',
  'pav.stastny@volny.cz',
  'automatic',
  date '2026-08-01',
  'OLVEND odesílá měsíční podklad; partner následně vystaví fakturu OLVENDu.',
  true
from public.business_contacts contact
where contact.contact_type = 'supplier'
  and contact.name_norm = public.olvend_contact_norm('Obědy Blučina - Pavel Šťastný')
on conflict (location_id) do update set
  business_contact_id = excluded.business_contact_id,
  device_label = excluded.device_label,
  invoice_description_template = excluded.invoice_description_template,
  vat_rate = excluded.vat_rate,
  unit_vat_rate = excluded.unit_vat_rate,
  billing_scope = excluded.billing_scope,
  billing_direction = excluded.billing_direction,
  rate_includes_vat = excluded.rate_includes_vat,
  quantity_label = excluded.quantity_label,
  quantity_unit = excluded.quantity_unit,
  fixed_monthly_amount = excluded.fixed_monthly_amount,
  fixed_vat_rate = excluded.fixed_vat_rate,
  rounding_mode = excluded.rounding_mode,
  email_recipient = excluded.email_recipient,
  attachment_mode = excluded.attachment_mode,
  billing_data_complete_from = excluded.billing_data_complete_from,
  billing_data_note = excluded.billing_data_note,
  active = true,
  updated_at = now();

commit;

select
  profile.location_id,
  contact.name partner,
  contact.company_id,
  contact.tax_id,
  profile.billing_direction,
  profile.rate_includes_vat,
  rule.amount gross_rate,
  profile.unit_vat_rate,
  profile.email_recipient
from public.partner_billing_profiles profile
join public.business_contacts contact on contact.id = profile.business_contact_id
join public.location_financial_rules rule
  on rule.location_id = profile.location_id
 and rule.direction = profile.billing_direction
where profile.location_id = 70;
