alter table public.employees
  add column if not exists bonus_eligible boolean not null default false;

comment on column public.employees.bonus_eligible is
  'Zaměstnanec má nárok na rovný podíl z měsíčního fondu prémií.';

create or replace function public.has_payroll_access()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.employees
    where auth_user_id = auth.uid()
      and active is not false
      and lower(coalesce(role, '')) in ('admin', 'manager')
  );
$$;

revoke all on function public.has_payroll_access() from public;
grant execute on function public.has_payroll_access() to authenticated;

create table if not exists public.payroll_month_entries (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees (id) on delete cascade,
  period_month date not null,
  carry_out_minutes integer not null default 0,
  export_included boolean not null default true,
  note text,
  updated_at timestamp with time zone not null default now(),
  unique (employee_id, period_month),
  check (date_trunc('month', period_month)::date = period_month)
);

alter table public.payroll_month_entries enable row level security;
drop policy if exists "Allow read payroll month entries" on public.payroll_month_entries;
drop policy if exists "Allow insert payroll month entries" on public.payroll_month_entries;
drop policy if exists "Allow update payroll month entries" on public.payroll_month_entries;
create policy "Allow read payroll month entries" on public.payroll_month_entries for select to authenticated using (public.has_payroll_access());
create policy "Allow insert payroll month entries" on public.payroll_month_entries for insert to authenticated with check (public.has_payroll_access());
create policy "Allow update payroll month entries" on public.payroll_month_entries for update to authenticated using (public.has_payroll_access()) with check (public.has_payroll_access());

create table if not exists public.payroll_absence_overrides (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees (id) on delete cascade,
  absence_date date not null,
  request_id bigint references public.hr_requests (id) on delete set null,
  absence_type text not null,
  minutes integer not null default 0,
  paid boolean not null default true,
  note text,
  updated_at timestamp with time zone not null default now(),
  unique (employee_id, absence_date, absence_type),
  check (minutes >= 0 and minutes <= 1440)
);

alter table public.payroll_absence_overrides enable row level security;
drop policy if exists "Allow read payroll absence overrides" on public.payroll_absence_overrides;
drop policy if exists "Allow insert payroll absence overrides" on public.payroll_absence_overrides;
drop policy if exists "Allow update payroll absence overrides" on public.payroll_absence_overrides;
drop policy if exists "Allow delete payroll absence overrides" on public.payroll_absence_overrides;
create policy "Allow read payroll absence overrides" on public.payroll_absence_overrides for select to authenticated using (public.has_payroll_access());
create policy "Allow insert payroll absence overrides" on public.payroll_absence_overrides for insert to authenticated with check (public.has_payroll_access());
create policy "Allow update payroll absence overrides" on public.payroll_absence_overrides for update to authenticated using (public.has_payroll_access()) with check (public.has_payroll_access());
create policy "Allow delete payroll absence overrides" on public.payroll_absence_overrides for delete to authenticated using (public.has_payroll_access());

create table if not exists public.payroll_settings (
  id smallint primary key default 1 check (id = 1),
  accountant_email text,
  bonus_rate numeric(7,4) not null default 1,
  updated_at timestamp with time zone not null default now()
);

insert into public.payroll_settings(id) values (1) on conflict (id) do nothing;
alter table public.payroll_settings enable row level security;
drop policy if exists "Allow read payroll settings" on public.payroll_settings;
drop policy if exists "Allow insert payroll settings" on public.payroll_settings;
drop policy if exists "Allow update payroll settings" on public.payroll_settings;
create policy "Allow read payroll settings" on public.payroll_settings for select to authenticated using (public.has_payroll_access());
create policy "Allow insert payroll settings" on public.payroll_settings for insert to authenticated with check (public.has_payroll_access());
create policy "Allow update payroll settings" on public.payroll_settings for update to authenticated using (public.has_payroll_access()) with check (public.has_payroll_access());
