begin;

create table if not exists public.payroll_payslips (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete cascade,
  period_month date not null,
  file_path text,
  file_name text,
  mime_type text,
  file_size_bytes bigint,
  general_message text,
  status text not null default 'draft',
  published_at timestamp with time zone,
  published_by uuid references public.employees(id) on delete set null,
  read_at timestamp with time zone,
  created_by uuid references public.employees(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique(employee_id, period_month),
  check (date_trunc('month', period_month)::date = period_month),
  check (status in ('draft', 'published', 'archived')),
  check (status <> 'published' or file_path is not null),
  check (file_size_bytes is null or file_size_bytes >= 0)
);

create table if not exists public.payroll_payslip_items (
  id bigint generated by default as identity primary key,
  payslip_id bigint not null references public.payroll_payslips(id) on delete cascade,
  item_type text not null,
  title text not null,
  amount numeric(14,2) not null default 0,
  explanation text,
  source_type text,
  source_id text,
  source_label text,
  agreement_confirmed boolean not null default false,
  included boolean not null default true,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  check (item_type in ('bonus', 'deduction', 'information')),
  check (item_type <> 'deduction' or included is false or agreement_confirmed is true),
  check (amount >= 0)
);

create index if not exists payroll_payslips_employee_period_idx
  on public.payroll_payslips(employee_id, period_month desc);
create index if not exists payroll_payslips_status_idx
  on public.payroll_payslips(status, period_month desc);
create index if not exists payroll_payslip_items_payslip_idx
  on public.payroll_payslip_items(payslip_id, display_order, id);
create unique index if not exists payroll_payslip_items_source_unique_idx
  on public.payroll_payslip_items(payslip_id, item_type, source_type, source_id)
  where source_id is not null;

comment on table public.payroll_payslips is
  'Soukromé měsíční výplatnice zaměstnanců. Zveřejněný záznam může číst pouze daný zaměstnanec a mzdová role.';
comment on column public.payroll_payslip_items.agreement_confirmed is
  'U srážky potvrzuje evidenci právního podkladu, zejména dohody o srážkách ze mzdy. Bez potvrzení nelze výplatnici zveřejnit.';

alter table public.payroll_payslips enable row level security;
alter table public.payroll_payslip_items enable row level security;

grant select, insert, update, delete on public.payroll_payslips to authenticated;
grant select, insert, update, delete on public.payroll_payslip_items to authenticated;
grant usage, select on sequence public.payroll_payslips_id_seq to authenticated;
grant usage, select on sequence public.payroll_payslip_items_id_seq to authenticated;

drop policy if exists "Payroll administrators read payslips" on public.payroll_payslips;
create policy "Payroll administrators read payslips"
on public.payroll_payslips for select to authenticated
using (public.has_payroll_access());

drop policy if exists "Employees read own published payslips" on public.payroll_payslips;
create policy "Employees read own published payslips"
on public.payroll_payslips for select to authenticated
using (
  status = 'published'
  and exists (
    select 1 from public.employees employee
    where employee.id = payroll_payslips.employee_id
      and employee.auth_user_id = auth.uid()
      and employee.active is not false
  )
);

drop policy if exists "Payroll administrators insert payslips" on public.payroll_payslips;
create policy "Payroll administrators insert payslips"
on public.payroll_payslips for insert to authenticated
with check (public.has_payroll_access());

drop policy if exists "Payroll administrators update payslips" on public.payroll_payslips;
create policy "Payroll administrators update payslips"
on public.payroll_payslips for update to authenticated
using (public.has_payroll_access())
with check (public.has_payroll_access());

drop policy if exists "Payroll administrators delete payslips" on public.payroll_payslips;
create policy "Payroll administrators delete payslips"
on public.payroll_payslips for delete to authenticated
using (public.has_payroll_access());

drop policy if exists "Payroll readers read payslip items" on public.payroll_payslip_items;
create policy "Payroll readers read payslip items"
on public.payroll_payslip_items for select to authenticated
using (
  public.has_payroll_access()
  or exists (
    select 1
    from public.payroll_payslips payslip
    join public.employees employee on employee.id = payslip.employee_id
    where payslip.id = payroll_payslip_items.payslip_id
      and payslip.status = 'published'
      and employee.auth_user_id = auth.uid()
      and employee.active is not false
  )
);

drop policy if exists "Payroll administrators insert payslip items" on public.payroll_payslip_items;
create policy "Payroll administrators insert payslip items"
on public.payroll_payslip_items for insert to authenticated
with check (public.has_payroll_access());

drop policy if exists "Payroll administrators update payslip items" on public.payroll_payslip_items;
create policy "Payroll administrators update payslip items"
on public.payroll_payslip_items for update to authenticated
using (public.has_payroll_access())
with check (public.has_payroll_access());

drop policy if exists "Payroll administrators delete payslip items" on public.payroll_payslip_items;
create policy "Payroll administrators delete payslip items"
on public.payroll_payslip_items for delete to authenticated
using (public.has_payroll_access());

create or replace function public.can_read_payroll_file(p_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_payroll_access()
    or exists (
      select 1
      from public.payroll_payslips payslip
      join public.employees employee on employee.id = payslip.employee_id
      where payslip.file_path = p_path
        and payslip.status = 'published'
        and employee.auth_user_id = auth.uid()
        and employee.active is not false
    );
$$;

revoke all on function public.can_read_payroll_file(text) from public;
grant execute on function public.can_read_payroll_file(text) to authenticated;

create or replace function public.acknowledge_my_payslip(p_payslip_id bigint)
returns timestamp with time zone
language plpgsql
security definer
set search_path = public
as $$
declare
  v_read_at timestamp with time zone;
begin
  update public.payroll_payslips payslip
  set read_at = coalesce(payslip.read_at, now()), updated_at = now()
  where payslip.id = p_payslip_id
    and payslip.status = 'published'
    and exists (
      select 1 from public.employees employee
      where employee.id = payslip.employee_id
        and employee.auth_user_id = auth.uid()
        and employee.active is not false
    )
  returning payslip.read_at into v_read_at;

  if v_read_at is null then
    raise exception 'Výplatnice není dostupná přihlášenému zaměstnanci.';
  end if;
  return v_read_at;
end;
$$;

revoke all on function public.acknowledge_my_payslip(bigint) from public;
grant execute on function public.acknowledge_my_payslip(bigint) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('payroll-payslips', 'payroll-payslips', false, 10485760, array['application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Payroll readers access private PDFs" on storage.objects;
create policy "Payroll readers access private PDFs"
on storage.objects for select to authenticated
using (bucket_id = 'payroll-payslips' and public.can_read_payroll_file(name));

drop policy if exists "Payroll administrators upload private PDFs" on storage.objects;
create policy "Payroll administrators upload private PDFs"
on storage.objects for insert to authenticated
with check (bucket_id = 'payroll-payslips' and public.has_payroll_access());

drop policy if exists "Payroll administrators replace private PDFs" on storage.objects;
create policy "Payroll administrators replace private PDFs"
on storage.objects for update to authenticated
using (bucket_id = 'payroll-payslips' and public.has_payroll_access())
with check (bucket_id = 'payroll-payslips' and public.has_payroll_access());

drop policy if exists "Payroll administrators delete private PDFs" on storage.objects;
create policy "Payroll administrators delete private PDFs"
on storage.objects for delete to authenticated
using (bucket_id = 'payroll-payslips' and public.has_payroll_access());

commit;

notify pgrst, 'reload schema';
