begin;

create table if not exists public.meeting_calendar_settings (
  id smallint primary key default 1 check (id = 1),
  manager_employee_id uuid not null references public.employees(id),
  slot_minutes integer not null default 30 check (slot_minutes in (30,45,60)),
  buffer_minutes integer not null default 15 check (buffer_minutes between 0 and 60),
  min_notice_hours integer not null default 24 check (min_notice_hours between 0 and 336),
  updated_at timestamptz not null default now()
);

insert into public.meeting_calendar_settings (id, manager_employee_id)
select 1, id from public.employees
where active is not false and lower(coalesce(name,'')) = 'michal' and lower(coalesce(surname,'')) like 'pun%'
order by created_at limit 1
on conflict (id) do nothing;

create table if not exists public.manager_calendar_blocks (
  id bigint generated by default as identity primary key,
  manager_employee_id uuid not null references public.employees(id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  block_type text not null default 'external_meeting' check (block_type in ('external_meeting','travel','doctor','focus','private','other')),
  note text,
  private boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.employee_meetings (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id),
  manager_employee_id uuid not null references public.employees(id),
  direction text not null check (direction in ('employee_request','manager_invitation')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  meeting_mode text not null default 'in_person' check (meeting_mode in ('in_person','phone','video')),
  topic text not null default 'work' check (topic in ('work','pay_bonus','operations','evaluation','personal','other')),
  message text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','reschedule_requested','cancelled')),
  response_note text,
  created_by_employee_id uuid not null references public.employees(id),
  responded_by_employee_id uuid references public.employees(id),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create index if not exists manager_calendar_blocks_time_idx on public.manager_calendar_blocks(manager_employee_id, starts_at, ends_at);
create index if not exists employee_meetings_time_idx on public.employee_meetings(manager_employee_id, starts_at, ends_at);
create index if not exists employee_meetings_employee_idx on public.employee_meetings(employee_id, starts_at desc);

create or replace function public.current_employee_id()
returns uuid language sql stable security definer set search_path=public as $$
  select id from public.employees where auth_user_id=auth.uid() and active is not false order by created_at limit 1
$$;

create or replace function public.has_manager_access()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.employees where auth_user_id=auth.uid() and active is not false and lower(coalesce(role,'')) in ('admin','manager'))
$$;

revoke all on function public.current_employee_id() from public;
revoke all on function public.has_manager_access() from public;
grant execute on function public.current_employee_id(), public.has_manager_access() to authenticated;

alter table public.meeting_calendar_settings enable row level security;
alter table public.manager_calendar_blocks enable row level security;
alter table public.employee_meetings enable row level security;

drop policy if exists meeting_settings_manager on public.meeting_calendar_settings;
create policy meeting_settings_manager on public.meeting_calendar_settings for all to authenticated using (public.has_manager_access()) with check (public.has_manager_access());
drop policy if exists calendar_blocks_manager on public.manager_calendar_blocks;
create policy calendar_blocks_manager on public.manager_calendar_blocks for all to authenticated using (public.has_manager_access()) with check (public.has_manager_access());
drop policy if exists meetings_read_own_or_manager on public.employee_meetings;
create policy meetings_read_own_or_manager on public.employee_meetings for select to authenticated using (public.has_manager_access() or employee_id=public.current_employee_id());
drop policy if exists meetings_insert_own_or_manager on public.employee_meetings;
create policy meetings_insert_own_or_manager on public.employee_meetings for insert to authenticated with check (
  public.has_manager_access()
);
drop policy if exists meetings_update_own_or_manager on public.employee_meetings;
create policy meetings_update_own_or_manager on public.employee_meetings for update to authenticated using (public.has_manager_access()) with check (public.has_manager_access());

create or replace function public.my_meeting_slots(p_from date, p_to date)
returns table(slot_start timestamptz, slot_end timestamptz)
language sql stable security definer set search_path=public as $$
  with cfg as (
    select * from public.meeting_calendar_settings where id=1
  ), office as (
    select d.plan_date,
      (d.plan_date + coalesce(d.planned_start,time '08:00')) at time zone 'Europe/Prague' as office_start,
      (d.plan_date + coalesce(d.planned_end,time '16:00')) at time zone 'Europe/Prague' as office_end,
      c.*
    from public.shift_plan_days d cross join cfg c
    where d.employee_id=c.manager_employee_id and d.status='published'
      and d.shift_type='manager_office' and d.plan_date between p_from and p_to
  ), candidates as (
    select o.manager_employee_id,
      g as slot_start, g + make_interval(mins=>o.slot_minutes) as slot_end,
      o.buffer_minutes, o.min_notice_hours
    from office o cross join lateral generate_series(o.office_start, o.office_end-make_interval(mins=>o.slot_minutes), make_interval(mins=>o.slot_minutes+o.buffer_minutes)) g
  )
  select c.slot_start,c.slot_end from candidates c
  where c.slot_start >= now()+make_interval(hours=>c.min_notice_hours)
    and not exists(select 1 from public.manager_calendar_blocks b where b.manager_employee_id=c.manager_employee_id and tstzrange(b.starts_at,b.ends_at,'[)') && tstzrange(c.slot_start,c.slot_end,'[)'))
    and not exists(select 1 from public.employee_meetings m where m.manager_employee_id=c.manager_employee_id and m.status in ('pending','approved') and tstzrange(m.starts_at,m.ends_at,'[)') && tstzrange(c.slot_start,c.slot_end,'[)'))
    and not exists(select 1 from public.route_plans r where r.planned_employee_id=c.manager_employee_id and r.planning_date=(c.slot_start at time zone 'Europe/Prague')::date and r.execution_status not in ('cancelled') and tstzrange((r.planning_date+r.planned_departure_time) at time zone 'Europe/Prague', ((r.planning_date+r.planned_departure_time)+make_interval(mins=>coalesce(r.estimated_drive_minutes,0)+coalesce(r.estimated_service_minutes,0))) at time zone 'Europe/Prague','[)') && tstzrange(c.slot_start,c.slot_end,'[)'))
  order by c.slot_start
$$;

revoke all on function public.my_meeting_slots(date,date) from public;
grant execute on function public.my_meeting_slots(date,date) to authenticated;

create or replace function public.request_my_meeting(
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_meeting_mode text default 'in_person',
  p_topic text default 'work',
  p_message text default null
)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  v_employee uuid := public.current_employee_id();
  v_manager uuid;
  v_id bigint;
begin
  if v_employee is null then raise exception 'Zaměstnanec není propojený s účtem.'; end if;
  select manager_employee_id into v_manager from public.meeting_calendar_settings where id=1;
  if v_manager is null then raise exception 'Kalendář manažera není nastavený.'; end if;
  if p_ends_at <= p_starts_at then raise exception 'Neplatný čas schůzky.'; end if;
  if not exists(select 1 from public.my_meeting_slots((p_starts_at at time zone 'Europe/Prague')::date,(p_starts_at at time zone 'Europe/Prague')::date) s where s.slot_start=p_starts_at and s.slot_end=p_ends_at) then
    raise exception 'Termín už není dostupný. Vyber jiný.';
  end if;
  insert into public.employee_meetings(employee_id,manager_employee_id,direction,starts_at,ends_at,meeting_mode,topic,message,created_by_employee_id)
  values(v_employee,v_manager,'employee_request',p_starts_at,p_ends_at,p_meeting_mode,p_topic,nullif(trim(p_message),''),v_employee)
  returning id into v_id;
  return v_id;
end $$;

create or replace function public.respond_to_my_meeting(p_meeting_id bigint,p_status text,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_employee uuid := public.current_employee_id();
begin
  if p_status not in ('approved','rejected','reschedule_requested') then raise exception 'Neplatná odpověď.'; end if;
  update public.employee_meetings
  set status=p_status,response_note=nullif(trim(p_note),''),responded_by_employee_id=v_employee,responded_at=now(),updated_at=now()
  where id=p_meeting_id and employee_id=v_employee and direction='manager_invitation' and status='pending';
  if not found then raise exception 'Pozvánku už nelze změnit.'; end if;
end $$;

revoke all on function public.request_my_meeting(timestamptz,timestamptz,text,text,text), public.respond_to_my_meeting(bigint,text,text) from public;
grant execute on function public.request_my_meeting(timestamptz,timestamptz,text,text,text), public.respond_to_my_meeting(bigint,text,text) to authenticated;

create or replace function public.my_bonus_summary(p_period date default date_trunc('month',current_date)::date)
returns jsonb language sql stable security definer set search_path=public as $$
  with params as (
    select greatest(date '2026-08-01',date_trunc('month',p_period)::date) from_date,
      (date_trunc('month',p_period)+interval '1 month')::date to_date,
      public.current_employee_id() employee_id
  ), eligible_events as (
    select ev.*
    from public.telemetry_sales_events ev, params p
    where ev.source_event_at >= p.from_date::timestamp at time zone 'Europe/Prague'
      and ev.source_event_at < p.to_date::timestamp at time zone 'Europe/Prague'
      and not (lower(coalesce(ev.provider,''))='vendsoft' and exists(select 1 from public.telemetry_sales_events direct where direct.machine_id=ev.machine_id and lower(coalesce(direct.provider,''))='ima'))
  ), attributed as (
    select ev.*, visit.employee_id,
      coalesce(ev.total_amount_czk,0) + case when coalesce(slot.settlement_billing_enabled,false) then coalesce(slot.settlement_amount_czk,0)*coalesce(ev.quantity,0) else 0 end revenue
    from eligible_events ev
    left join public.machine_planogram_slots slot on slot.id=ev.planogram_slot_id
    left join lateral (
      select v.employee_id from public.route_machine_visits v
      where v.machine_id=ev.machine_id and v.status='completed' and v.employee_id is not null and v.completed_at<=ev.source_event_at
      order by v.completed_at desc limit 1
    ) visit on true
  ), own as (
    select coalesce(sum(revenue),0) revenue,count(distinct machine_id) machines from attributed,params where attributed.employee_id=params.employee_id
  ), deductions as (
    select coalesce(sum(abs(a.bonus_impact_amount)),0) amount from public.inventory_audits a,params p
    where a.assigned_employee_id=p.employee_id and a.responsibility_status='operator' and a.status='closed'
      and a.bonus_impact_amount is not null and coalesce(a.bonus_period,date_trunc('month',a.audit_date)::date)=p.from_date
  ), visits as (
    select count(*) count from public.route_machine_visits v,params p where v.employee_id=p.employee_id and v.status='completed' and v.completed_at>=p.from_date::timestamp at time zone 'Europe/Prague' and v.completed_at<p.to_date::timestamp at time zone 'Europe/Prague'
  ), calc as (
    select p.from_date period,own.revenue,own.machines,visits.count visits,deductions.amount deductions,coalesce((select bonus_rate from public.payroll_settings where id=1),1) rate
    from params p,own,deductions,visits
  )
  select jsonb_build_object('period',period,'bonus_before_adjustments',round(revenue*rate/100,2),'deductions',round(deductions,2),'quality_bonus',0,'total',greatest(0,round(revenue*rate/100-deductions,2)),'visits',visits,'machines',machines,'is_final',period<date_trunc('month',current_date)::date,'updated_at',now()) from calc
$$;

create or replace function public.manager_bonus_month(p_period date)
returns table(employee_id uuid, employee_name text, attributed_revenue numeric, bonus_before_adjustments numeric, deductions numeric, quality_bonus numeric, total numeric, visits bigint)
language sql stable security definer set search_path=public as $$
  with params as (select greatest(date '2026-08-01',date_trunc('month',p_period)::date) from_date,(date_trunc('month',p_period)+interval '1 month')::date to_date),
  events as (
    select ev.* from public.telemetry_sales_events ev,params p where ev.source_event_at>=p.from_date::timestamp at time zone 'Europe/Prague' and ev.source_event_at<p.to_date::timestamp at time zone 'Europe/Prague'
      and not (lower(coalesce(ev.provider,''))='vendsoft' and exists(select 1 from public.telemetry_sales_events direct where direct.machine_id=ev.machine_id and lower(coalesce(direct.provider,''))='ima'))
  ), attributed as (
    select visit.employee_id,coalesce(ev.total_amount_czk,0)+case when coalesce(slot.settlement_billing_enabled,false) then coalesce(slot.settlement_amount_czk,0)*coalesce(ev.quantity,0) else 0 end revenue
    from events ev left join public.machine_planogram_slots slot on slot.id=ev.planogram_slot_id
    left join lateral (select v.employee_id from public.route_machine_visits v where v.machine_id=ev.machine_id and v.status='completed' and v.employee_id is not null and v.completed_at<=ev.source_event_at order by v.completed_at desc limit 1) visit on true
  ), revenue as (select employee_id,coalesce(sum(revenue),0) amount from attributed where employee_id is not null group by employee_id),
  deduction as (select a.assigned_employee_id employee_id,coalesce(sum(abs(a.bonus_impact_amount)),0) amount from public.inventory_audits a,params p where a.responsibility_status='operator' and a.status='closed' and a.bonus_impact_amount is not null and coalesce(a.bonus_period,date_trunc('month',a.audit_date)::date)=p.from_date group by a.assigned_employee_id),
  visit_counts as (select v.employee_id,count(*) count from public.route_machine_visits v,params p where v.status='completed' and v.completed_at>=p.from_date::timestamp at time zone 'Europe/Prague' and v.completed_at<p.to_date::timestamp at time zone 'Europe/Prague' group by v.employee_id),
  settings as (select coalesce((select bonus_rate from public.payroll_settings where id=1),1) rate)
  select e.id,concat_ws(' ',e.name,e.surname),round(coalesce(r.amount,0),2),round(coalesce(r.amount,0)*s.rate/100,2),round(coalesce(d.amount,0),2),0::numeric,greatest(0,round(coalesce(r.amount,0)*s.rate/100-coalesce(d.amount,0),2)),coalesce(v.count,0)
  from public.employees e cross join settings s left join revenue r on r.employee_id=e.id left join deduction d on d.employee_id=e.id left join visit_counts v on v.employee_id=e.id
  where e.active is not false and e.bonus_eligible and public.has_manager_access()
  order by e.surname,e.name
$$;

revoke all on function public.my_bonus_summary(date), public.manager_bonus_month(date) from public;
grant execute on function public.my_bonus_summary(date), public.manager_bonus_month(date) to authenticated;

commit;
