create table if not exists public.supplier_product_mappings (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.purchase_suppliers (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  supplier_item_code text not null,
  ean text,
  supplier_item_name text,
  invoice_unit_code text,
  base_units_per_invoice_unit numeric(12,6) not null default 1,
  last_unit_price numeric(12,2),
  last_seen_at timestamp with time zone,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (supplier_id, supplier_item_code)
);

create index if not exists supplier_product_mappings_supplier_idx
  on public.supplier_product_mappings (supplier_id);

create index if not exists supplier_product_mappings_product_idx
  on public.supplier_product_mappings (product_id);

create index if not exists supplier_product_mappings_ean_idx
  on public.supplier_product_mappings (ean);

drop trigger if exists trg_supplier_product_mappings_updated_at on public.supplier_product_mappings;
create trigger trg_supplier_product_mappings_updated_at
before update on public.supplier_product_mappings
for each row
execute function public.set_purchase_updated_at();

alter table public.supplier_product_mappings enable row level security;

drop policy if exists "Allow read supplier product mappings" on public.supplier_product_mappings;
create policy "Allow read supplier product mappings"
on public.supplier_product_mappings
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert supplier product mappings" on public.supplier_product_mappings;
create policy "Allow insert supplier product mappings"
on public.supplier_product_mappings
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update supplier product mappings" on public.supplier_product_mappings;
create policy "Allow update supplier product mappings"
on public.supplier_product_mappings
for update
to authenticated, anon
using (true)
with check (true);
