create table if not exists public.purchase_recurring_orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.purchase_suppliers (id) on delete restrict,
  pilot_scope text not null default 'general'
    check (pilot_scope in ('general', 'bagette')),
  active boolean not null default true,
  order_weekdays smallint[] not null default '{}',
  delivery_weekdays smallint[] not null default '{}',
  lead_time_days integer not null default 0,
  weekday_reserve_quantity numeric(12,3) not null default 0,
  friday_target_quantity numeric(12,3) not null default 0,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.purchase_recurring_order_items (
  id bigint generated by default as identity primary key,
  recurring_order_id bigint not null references public.purchase_recurring_orders (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  active boolean not null default true,
  base_order_quantity numeric(12,3) not null default 0,
  order_quantity_by_weekday jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (recurring_order_id, product_id)
);

create index if not exists purchase_recurring_orders_supplier_idx
  on public.purchase_recurring_orders (supplier_id);

create index if not exists purchase_recurring_order_items_order_idx
  on public.purchase_recurring_order_items (recurring_order_id);

create index if not exists purchase_recurring_order_items_product_idx
  on public.purchase_recurring_order_items (product_id);

alter table public.purchase_orders
  add column if not exists recurring_order_id bigint references public.purchase_recurring_orders (id) on delete set null;

alter table public.purchase_order_items
  add column if not exists recurring_order_item_id bigint references public.purchase_recurring_order_items (id) on delete set null;

drop trigger if exists trg_purchase_recurring_orders_updated_at on public.purchase_recurring_orders;
create trigger trg_purchase_recurring_orders_updated_at
before update on public.purchase_recurring_orders
for each row
execute function public.set_purchase_updated_at();

drop trigger if exists trg_purchase_recurring_order_items_updated_at on public.purchase_recurring_order_items;
create trigger trg_purchase_recurring_order_items_updated_at
before update on public.purchase_recurring_order_items
for each row
execute function public.set_purchase_updated_at();

alter table public.purchase_recurring_orders enable row level security;
alter table public.purchase_recurring_order_items enable row level security;

drop policy if exists "Allow read purchase recurring orders" on public.purchase_recurring_orders;
create policy "Allow read purchase recurring orders"
on public.purchase_recurring_orders
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert purchase recurring orders" on public.purchase_recurring_orders;
create policy "Allow insert purchase recurring orders"
on public.purchase_recurring_orders
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update purchase recurring orders" on public.purchase_recurring_orders;
create policy "Allow update purchase recurring orders"
on public.purchase_recurring_orders
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow delete purchase recurring orders" on public.purchase_recurring_orders;
create policy "Allow delete purchase recurring orders"
on public.purchase_recurring_orders
for delete
to authenticated, anon
using (true);

drop policy if exists "Allow read purchase recurring order items" on public.purchase_recurring_order_items;
create policy "Allow read purchase recurring order items"
on public.purchase_recurring_order_items
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert purchase recurring order items" on public.purchase_recurring_order_items;
create policy "Allow insert purchase recurring order items"
on public.purchase_recurring_order_items
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update purchase recurring order items" on public.purchase_recurring_order_items;
create policy "Allow update purchase recurring order items"
on public.purchase_recurring_order_items
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow delete purchase recurring order items" on public.purchase_recurring_order_items;
create policy "Allow delete purchase recurring order items"
on public.purchase_recurring_order_items
for delete
to authenticated, anon
using (true);
