create table if not exists public.purchase_suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_name text,
  email text,
  phone text,
  active boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (name)
);

create table if not exists public.purchase_product_profiles (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.purchase_suppliers (id) on delete restrict,
  product_id bigint not null references public.products (id) on delete cascade,
  pilot_scope text not null default 'general'
    check (pilot_scope in ('general', 'bagette')),
  active boolean not null default true,
  reorder_enabled boolean not null default true,
  order_weekdays smallint[] not null default '{}',
  delivery_weekdays smallint[] not null default '{}',
  lead_time_days integer not null default 0,
  base_order_quantity numeric(12,3) not null default 0,
  min_order_quantity numeric(12,3) not null default 0,
  order_multiple_quantity numeric(12,3) not null default 1,
  safety_stock_quantity numeric(12,3) not null default 0,
  target_cover_days integer not null default 2,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (supplier_id, product_id, pilot_scope)
);

create index if not exists purchase_product_profiles_product_idx
  on public.purchase_product_profiles (product_id);

create index if not exists purchase_product_profiles_supplier_idx
  on public.purchase_product_profiles (supplier_id);

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.purchase_suppliers (id) on delete restrict,
  order_scope text not null default 'general'
    check (order_scope in ('general', 'bagette_pilot')),
  status text not null default 'draft'
    check (status in ('draft', 'ordered', 'received', 'cancelled')),
  order_date date not null default current_date,
  delivery_date date,
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists purchase_orders_supplier_idx
  on public.purchase_orders (supplier_id);

create index if not exists purchase_orders_status_idx
  on public.purchase_orders (status);

create index if not exists purchase_orders_delivery_date_idx
  on public.purchase_orders (delivery_date);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  ordered_quantity numeric(12,3) not null default 0,
  received_quantity numeric(12,3) not null default 0,
  unit_cost numeric(12,2),
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (purchase_order_id, product_id)
);

create index if not exists purchase_order_items_product_idx
  on public.purchase_order_items (product_id);

create or replace view public.purchase_product_recommendations_v13 as
with profile_base as (
  select
    ppp.id as profile_id,
    ppp.product_id,
    ppp.supplier_id,
    ppp.pilot_scope,
    ppp.active,
    ppp.reorder_enabled,
    ppp.order_weekdays,
    ppp.delivery_weekdays,
    ppp.lead_time_days,
    ppp.base_order_quantity,
    ppp.min_order_quantity,
    ppp.order_multiple_quantity,
    ppp.safety_stock_quantity,
    ppp.target_cover_days,
    ppp.note as profile_note,
    pr.name as product_name,
    pr.base_unit,
    ps.name as supplier_name
  from public.purchase_product_profiles ppp
  join public.products pr on pr.id = ppp.product_id
  join public.purchase_suppliers ps on ps.id = ppp.supplier_id
  where ppp.active = true
),
stock_totals as (
  select
    slb.product_id,
    sum(case when sl.location_type = 'warehouse' then slb.quantity_on_hand else 0 end) as warehouse_qty,
    sum(case when sl.location_type = 'vehicle' then slb.quantity_on_hand else 0 end) as vehicle_qty,
    sum(case when sl.location_type in ('warehouse', 'vehicle') then slb.quantity_on_hand else 0 end) as available_qty
  from public.stock_location_balances slb
  join public.stock_locations sl on sl.id = slb.stock_location_id
  where sl.active = true
  group by slb.product_id
),
usage_14d as (
  select
    sm.product_id,
    sum(case when sm.movement_type = 'load_vehicle' then sm.quantity_base_units else 0 end) as load_qty,
    sum(case when sm.movement_type = 'return' and tsl.location_type = 'warehouse' then sm.quantity_base_units else 0 end) as return_qty,
    sum(case when sm.movement_type = 'waste' then sm.quantity_base_units else 0 end) as waste_qty
  from public.stock_movements_v13 sm
  left join public.stock_locations tsl on tsl.id = sm.to_stock_location_id
  where sm.created_at >= now() - interval '14 days'
  group by sm.product_id
),
incoming_orders as (
  select
    poi.product_id,
    sum(greatest(poi.ordered_quantity - poi.received_quantity, 0)) as incoming_qty,
    min(po.delivery_date) filter (where po.delivery_date >= current_date) as next_delivery_date
  from public.purchase_order_items poi
  join public.purchase_orders po on po.id = poi.purchase_order_id
  where po.status in ('draft', 'ordered')
    and (po.delivery_date is null or po.delivery_date >= current_date)
  group by poi.product_id
),
calculated as (
  select
    pb.*,
    coalesce(st.warehouse_qty, 0) as warehouse_qty,
    coalesce(st.vehicle_qty, 0) as vehicle_qty,
    coalesce(st.available_qty, 0) as available_qty,
    coalesce(io.incoming_qty, 0) as incoming_qty,
    io.next_delivery_date,
    greatest(coalesce(u.load_qty, 0) - coalesce(u.return_qty, 0) - coalesce(u.waste_qty, 0), 0) as estimated_usage_14d,
    round(greatest(coalesce(u.load_qty, 0) - coalesce(u.return_qty, 0) - coalesce(u.waste_qty, 0), 0) / 14.0, 3) as avg_daily_usage_14d
  from profile_base pb
  left join stock_totals st on st.product_id = pb.product_id
  left join usage_14d u on u.product_id = pb.product_id
  left join incoming_orders io on io.product_id = pb.product_id
),
recommended as (
  select
    c.*,
    round(case
      when c.avg_daily_usage_14d <= 0 then 0
      else (c.avg_daily_usage_14d * greatest(c.target_cover_days, 1)) + c.safety_stock_quantity - (c.available_qty + c.incoming_qty)
    end, 3) as raw_recommended_qty
  from calculated c
)
select
  r.profile_id,
  r.product_id,
  r.product_name,
  r.base_unit,
  r.supplier_id,
  r.supplier_name,
  r.pilot_scope,
  r.reorder_enabled,
  r.order_weekdays,
  r.delivery_weekdays,
  r.lead_time_days,
  r.base_order_quantity,
  r.min_order_quantity,
  r.order_multiple_quantity,
  r.safety_stock_quantity,
  r.target_cover_days,
  r.warehouse_qty,
  r.vehicle_qty,
  r.available_qty,
  r.incoming_qty,
  r.next_delivery_date,
  r.estimated_usage_14d,
  r.avg_daily_usage_14d,
  case
    when r.avg_daily_usage_14d <= 0 then null
    else round(r.available_qty / nullif(r.avg_daily_usage_14d, 0), 1)
  end as estimated_days_cover,
  greatest(
    case
      when r.raw_recommended_qty <= 0 then 0
      when coalesce(r.order_multiple_quantity, 0) <= 0 then r.raw_recommended_qty
      else ceil(r.raw_recommended_qty / r.order_multiple_quantity) * r.order_multiple_quantity
    end,
    case
      when r.raw_recommended_qty > 0 then r.min_order_quantity
      else 0
    end
  ) as recommended_order_qty,
  r.profile_note
from recommended r;

create or replace function public.set_purchase_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_purchase_suppliers_updated_at on public.purchase_suppliers;
create trigger trg_purchase_suppliers_updated_at
before update on public.purchase_suppliers
for each row
execute function public.set_purchase_updated_at();

drop trigger if exists trg_purchase_product_profiles_updated_at on public.purchase_product_profiles;
create trigger trg_purchase_product_profiles_updated_at
before update on public.purchase_product_profiles
for each row
execute function public.set_purchase_updated_at();

drop trigger if exists trg_purchase_orders_updated_at on public.purchase_orders;
create trigger trg_purchase_orders_updated_at
before update on public.purchase_orders
for each row
execute function public.set_purchase_updated_at();

drop trigger if exists trg_purchase_order_items_updated_at on public.purchase_order_items;
create trigger trg_purchase_order_items_updated_at
before update on public.purchase_order_items
for each row
execute function public.set_purchase_updated_at();

alter table public.purchase_suppliers enable row level security;
alter table public.purchase_product_profiles enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

create policy "Allow read purchase suppliers"
on public.purchase_suppliers
for select
to authenticated, anon
using (true);

create policy "Allow insert purchase suppliers"
on public.purchase_suppliers
for insert
to authenticated, anon
with check (true);

create policy "Allow update purchase suppliers"
on public.purchase_suppliers
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read purchase product profiles"
on public.purchase_product_profiles
for select
to authenticated, anon
using (true);

create policy "Allow insert purchase product profiles"
on public.purchase_product_profiles
for insert
to authenticated, anon
with check (true);

create policy "Allow update purchase product profiles"
on public.purchase_product_profiles
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read purchase orders"
on public.purchase_orders
for select
to authenticated, anon
using (true);

create policy "Allow insert purchase orders"
on public.purchase_orders
for insert
to authenticated, anon
with check (true);

create policy "Allow update purchase orders"
on public.purchase_orders
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read purchase order items"
on public.purchase_order_items
for select
to authenticated, anon
using (true);

create policy "Allow insert purchase order items"
on public.purchase_order_items
for insert
to authenticated, anon
with check (true);

create policy "Allow update purchase order items"
on public.purchase_order_items
for update
to authenticated, anon
using (true)
with check (true);
