-- Automatický příjem fresh sortimentu ze stálých dodávek.
-- Úloha běží každou hodinu, ale zpracuje příjem pouze mezi 00:00–00:59
-- v časové zóně Europe/Prague. Opakované spuštění je bezpečné.

alter table public.purchase_recurring_orders
  add column if not exists auto_receive_enabled boolean not null default false,
  add column if not exists auto_receive_stock_location_id bigint references public.stock_locations(id) on delete restrict,
  add column if not exists shelf_life_days integer not null default 8
    check (shelf_life_days between 0 and 3650);

create table if not exists public.purchase_recurring_auto_receipts (
  id bigint generated by default as identity primary key,
  recurring_order_id bigint not null references public.purchase_recurring_orders(id) on delete restrict,
  delivery_date date not null,
  expiry_date date not null,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete restrict,
  stock_location_id bigint not null references public.stock_locations(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (recurring_order_id, delivery_date)
);

alter table public.purchase_recurring_auto_receipts enable row level security;

drop policy if exists "Allow read recurring auto receipts" on public.purchase_recurring_auto_receipts;
create policy "Allow read recurring auto receipts"
on public.purchase_recurring_auto_receipts
for select
to authenticated, anon
using (true);

create or replace function public.auto_receive_recurring_fresh_orders(p_delivery_date date default null)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_prague_now timestamp := timezone('Europe/Prague', clock_timestamp());
  v_delivery_date date := coalesce(p_delivery_date, timezone('Europe/Prague', clock_timestamp())::date);
  v_iso_day integer;
  v_order public.purchase_recurring_orders%rowtype;
  v_item record;
  v_purchase_order_id bigint;
  v_batch_id bigint;
  v_quantity numeric(12,3);
  v_expiry_date date;
  v_created_orders integer := 0;
  v_created_items integer := 0;
  v_movements jsonb;
begin
  if p_delivery_date is null and extract(hour from v_prague_now) <> 0 then
    return jsonb_build_object('created_orders', 0, 'created_items', 0, 'skipped', 'outside_midnight_hour');
  end if;

  v_iso_day := extract(isodow from v_delivery_date)::integer;
  perform pg_advisory_xact_lock(hashtextextended('recurring-fresh-auto-receipt:' || v_delivery_date::text, 0));

  for v_order in
    select recurring.*
    from public.purchase_recurring_orders recurring
    where recurring.active
      and recurring.auto_receive_enabled
      and recurring.auto_receive_stock_location_id is not null
      and v_iso_day = any(recurring.delivery_weekdays)
    order by recurring.id
  loop
    if exists (
      select 1
      from public.purchase_recurring_auto_receipts receipt
      where receipt.recurring_order_id = v_order.id
        and receipt.delivery_date = v_delivery_date
    ) then
      continue;
    end if;

    v_expiry_date := v_delivery_date + v_order.shelf_life_days;
    v_purchase_order_id := null;

    -- Generátor stálých objednávek už může mít pro tento den připravený návrh.
    -- Při příjmu ho použijeme a jeho řádky níže nahradíme množstvím platným
    -- pro konkrétní den; v seznamu tak nevznikne druhý duplicitní doklad.
    select purchase.id
      into v_purchase_order_id
    from public.purchase_orders purchase
    where purchase.recurring_order_id = v_order.id
      and purchase.delivery_date = v_delivery_date
      and purchase.status in ('draft', 'ordered')
    order by purchase.id desc
    limit 1
    for update;

    if v_purchase_order_id is null then
      insert into public.purchase_orders (
        supplier_id,
        recurring_order_id,
        order_scope,
        status,
        order_date,
        delivery_date,
        received_at,
        received_stock_location_id,
        note
      ) values (
        v_order.supplier_id,
        v_order.id,
        case when v_order.pilot_scope = 'bagette' then 'bagette_pilot' else 'general' end,
        'received',
        v_delivery_date - greatest(v_order.lead_time_days, 0),
        v_delivery_date,
        timezone('Europe/Prague', v_delivery_date::timestamp),
        v_order.auto_receive_stock_location_id,
        format('Automatický příjem ze stálé dodávky. Expirace %s.', to_char(v_expiry_date, 'DD.MM.YYYY'))
      ) returning id into v_purchase_order_id;
    else
      update public.purchase_orders
      set supplier_id = v_order.supplier_id,
          order_scope = case when v_order.pilot_scope = 'bagette' then 'bagette_pilot' else 'general' end,
          status = 'received',
          order_date = v_delivery_date - greatest(v_order.lead_time_days, 0),
          received_at = timezone('Europe/Prague', v_delivery_date::timestamp),
          received_stock_location_id = v_order.auto_receive_stock_location_id,
          note = format('Automatický příjem ze stálé dodávky. Expirace %s.', to_char(v_expiry_date, 'DD.MM.YYYY')),
          updated_at = now()
      where id = v_purchase_order_id;

      delete from public.purchase_order_items
      where purchase_order_id = v_purchase_order_id;
    end if;

    v_movements := '[]'::jsonb;

    for v_item in
      select item.*, supplier.name as supplier_name, product.purchase_price
      from public.purchase_recurring_order_items item
      join public.purchase_suppliers supplier on supplier.id = v_order.supplier_id
      join public.products product on product.id = item.product_id
      where item.recurring_order_id = v_order.id
        and item.active
        and product.expiry_tracking_mode = 'use_by'
        and product.product_category = 'food_ready'
      order by item.id
    loop
      v_quantity := coalesce(
        nullif(v_item.order_quantity_by_weekday ->> v_iso_day::text, '')::numeric,
        v_item.base_order_quantity,
        0
      );
      if v_quantity <= 0 then
        continue;
      end if;

      insert into public.inventory_batches (
        product_id,
        lot_code,
        use_by_date,
        received_at,
        supplier_name,
        note
      ) values (
        v_item.product_id,
        format('AUTO-%s-%s-%s', v_order.id, to_char(v_delivery_date, 'YYYYMMDD'), v_item.product_id),
        v_expiry_date,
        timezone('Europe/Prague', v_delivery_date::timestamp),
        v_item.supplier_name,
        format('Automatický příjem stálé dodávky #%s', v_order.id)
      ) returning id into v_batch_id;

      insert into public.purchase_order_items (
        purchase_order_id,
        recurring_order_item_id,
        product_id,
        ordered_quantity,
        received_quantity,
        unit_cost,
        note
      ) values (
        v_purchase_order_id,
        v_item.id,
        v_item.product_id,
        v_quantity,
        v_quantity,
        nullif(v_item.purchase_price, 0),
        format('Automaticky přijato; spotřebujte do %s.', to_char(v_expiry_date, 'DD.MM.YYYY'))
      );

      v_movements := v_movements || jsonb_build_array(jsonb_build_object(
        'product_id', v_item.product_id,
        'batch_id', v_batch_id,
        'to_stock_location_id', v_order.auto_receive_stock_location_id,
        'movement_type', 'receipt',
        'quantity_base_units', v_quantity,
        'unit_price', nullif(v_item.purchase_price, 0),
        'reference_type', 'purchase_order',
        'reference_id', v_purchase_order_id::text,
        'note', format('Automatický příjem stálé dodávky #%s; expirace %s.', v_order.id, to_char(v_expiry_date, 'DD.MM.YYYY'))
      ));
      v_created_items := v_created_items + 1;
    end loop;

    if jsonb_array_length(v_movements) = 0 then
      delete from public.purchase_orders where id = v_purchase_order_id;
      continue;
    end if;

    perform public.apply_stock_movements_v13(v_movements);

    insert into public.purchase_recurring_auto_receipts (
      recurring_order_id,
      delivery_date,
      expiry_date,
      purchase_order_id,
      stock_location_id
    ) values (
      v_order.id,
      v_delivery_date,
      v_expiry_date,
      v_purchase_order_id,
      v_order.auto_receive_stock_location_id
    );
    v_created_orders := v_created_orders + 1;
  end loop;

  return jsonb_build_object(
    'delivery_date', v_delivery_date,
    'created_orders', v_created_orders,
    'created_items', v_created_items
  );
end;
$$;

revoke all on function public.auto_receive_recurring_fresh_orders(date) from public, anon, authenticated;

-- Pouze existující Crocodille stálá dodávka #2 -> sklad BLUČINA, trvanlivost 8 dní.
update public.purchase_recurring_orders recurring
set
  auto_receive_enabled = true,
  auto_receive_stock_location_id = location.id,
  shelf_life_days = 8,
  updated_at = now()
from public.purchase_suppliers supplier
cross join lateral (
  select stock.id
  from public.stock_locations stock
  where stock.active
    and stock.location_type = 'warehouse'
    and upper(stock.name) = 'BLUČINA'
  order by stock.id
  limit 1
) location
where supplier.id = recurring.supplier_id
  and recurring.id = 2
  and recurring.active
  and supplier.name = 'Crocodille ČR, spol. s r.o.';

do $$
begin
  if exists (select 1 from cron.job where jobname = 'recurring-fresh-auto-receive') then
    perform cron.unschedule((select jobid from cron.job where jobname = 'recurring-fresh-auto-receive' limit 1));
  end if;
  perform cron.schedule(
    'recurring-fresh-auto-receive',
    '5 * * * *',
    'select public.auto_receive_recurring_fresh_orders();'
  );
end;
$$;

comment on function public.auto_receive_recurring_fresh_orders(date) is
  'Idempotentně přijme aktivní stálé fresh dodávky do nastaveného skladu a založí šarže s expirací.';
