begin;

create table if not exists public.route_vehicle_waste_items (
  id bigint generated by default as identity primary key,
  stock_reference_id text not null unique,
  route_plan_id bigint references public.route_plans (id) on delete set null,
  route_machine_visit_id bigint not null references public.route_machine_visits (id) on delete cascade,
  route_machine_visit_item_id bigint references public.route_machine_visit_items (id) on delete set null,
  machine_id bigint references public.machines (id) on delete set null,
  employee_id uuid references public.employees (id) on delete set null,
  vehicle_id bigint not null references public.vehicles (id) on delete restrict,
  product_id bigint not null references public.products (id) on delete restrict,
  product_sku text,
  product_name text,
  quantity numeric(12,3) not null check (quantity > 0),
  unit text not null default 'ks',
  reason text not null check (reason in ('expired', 'shaken', 'damaged', 'opened', 'other')),
  expiry_date date,
  machine_name text,
  location_name text,
  note text,
  status text not null default 'pending' check (status in ('pending', 'unloaded')),
  collected_at timestamptz not null default now(),
  unloaded_at timestamptz,
  unloaded_by uuid references public.employees (id) on delete set null,
  unload_reference_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists route_vehicle_waste_pending_vehicle_idx
  on public.route_vehicle_waste_items (vehicle_id, status, collected_at);

comment on table public.route_vehicle_waste_items is
  'Fyzické odpisy svezené z automatů. Nejsou použitelnou zásobou vozidla; pending pouze znamená, že sáček ještě nebyl potvrzený ve skladu.';

alter table public.route_vehicle_waste_items enable row level security;

drop policy if exists "Allow read route vehicle waste" on public.route_vehicle_waste_items;
create policy "Allow read route vehicle waste"
on public.route_vehicle_waste_items for select
to anon, authenticated
using (true);

drop policy if exists "Allow insert route vehicle waste" on public.route_vehicle_waste_items;
create policy "Allow insert route vehicle waste"
on public.route_vehicle_waste_items for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow update route vehicle waste" on public.route_vehicle_waste_items;
create policy "Allow update route vehicle waste"
on public.route_vehicle_waste_items for update
to anon, authenticated
using (true)
with check (true);

grant select, insert, update on public.route_vehicle_waste_items to anon, authenticated;
grant usage, select on sequence public.route_vehicle_waste_items_id_seq to anon, authenticated;

create or replace function public.confirm_route_vehicle_waste_unload_v29(
  waste_ids bigint[],
  unloading_employee_id uuid default null
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_reference text := 'route-waste-unload:' || gen_random_uuid()::text;
  v_requested_count integer;
  v_unloaded_count integer;
begin
  v_requested_count := coalesce(array_length(waste_ids, 1), 0);
  if v_requested_count = 0 then
    raise exception 'K vyložení nebyly předány žádné odpisy.';
  end if;

  if (
    select count(distinct vehicle_id)
    from public.route_vehicle_waste_items
    where id = any(waste_ids)
      and status = 'pending'
  ) <> 1 then
    raise exception 'Vybrané odpisy musí být nevyložené a patřit jednomu vozidlu.';
  end if;

  update public.route_vehicle_waste_items
  set
    status = 'unloaded',
    unloaded_at = now(),
    unloaded_by = unloading_employee_id,
    unload_reference_id = v_reference,
    updated_at = now()
  where id = any(waste_ids)
    and status = 'pending';

  get diagnostics v_unloaded_count = row_count;
  if v_unloaded_count <> v_requested_count then
    raise exception 'Některý odpis už byl vyložen nebo neexistuje (% z %).', v_unloaded_count, v_requested_count;
  end if;

  return jsonb_build_object(
    'unloaded_count', v_unloaded_count,
    'reference_id', v_reference
  );
end
$$;

grant execute on function public.confirm_route_vehicle_waste_unload_v29(bigint[], uuid) to anon, authenticated;

commit;
