begin;

create table if not exists public.route_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  route_type text not null default 'operational'
    check (route_type in ('operational', 'service', 'mixed')),
  default_employee_id uuid null references public.employees(id) on delete set null,
  default_role text null,
  default_vehicle_id bigint null references public.vehicles(id) on delete set null,
  default_warehouse_id bigint null references public.warehouses(id) on delete set null,
  active boolean not null default true,
  note text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.route_template_stops (
  id bigint generated by default as identity primary key,
  route_template_id bigint not null references public.route_templates(id) on delete cascade,
  location_id bigint null references public.locations(id) on delete set null,
  machine_id bigint null references public.machines(id) on delete set null,
  stop_order integer not null default 1,
  default_service_minutes integer null,
  note text null,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.route_plans
  add column if not exists route_template_id bigint null references public.route_templates(id) on delete set null;

create index if not exists idx_route_templates_active on public.route_templates(active);
create index if not exists idx_route_templates_type on public.route_templates(route_type);
create index if not exists idx_route_template_stops_template on public.route_template_stops(route_template_id, stop_order);
create index if not exists idx_route_plans_template on public.route_plans(route_template_id);

create or replace function public.touch_route_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_route_templates_updated_at on public.route_templates;
create trigger trg_route_templates_updated_at
before update on public.route_templates
for each row
execute function public.touch_route_templates_updated_at();

drop trigger if exists trg_route_template_stops_updated_at on public.route_template_stops;
create trigger trg_route_template_stops_updated_at
before update on public.route_template_stops
for each row
execute function public.touch_route_templates_updated_at();

alter table public.route_templates enable row level security;
alter table public.route_template_stops enable row level security;

drop policy if exists "Allow read route templates" on public.route_templates;
create policy "Allow read route templates"
on public.route_templates
for select
using (true);

drop policy if exists "Allow write route templates" on public.route_templates;
create policy "Allow write route templates"
on public.route_templates
for all
using (true)
with check (true);

drop policy if exists "Allow read route template stops" on public.route_template_stops;
create policy "Allow read route template stops"
on public.route_template_stops
for select
using (true);

drop policy if exists "Allow write route template stops" on public.route_template_stops;
create policy "Allow write route template stops"
on public.route_template_stops
for all
using (true)
with check (true);

comment on table public.route_templates is 'Šablony stálých tras pro provozní a servisní výjezdy.';
comment on table public.route_template_stops is 'Výchozí zastávky patřící do šablony trasy.';

commit;
