alter table public.warehouses
  add column if not exists latitude numeric(10, 7),
  add column if not exists longitude numeric(10, 7);

create table if not exists public.route_plans (
  id bigint generated by default as identity primary key,
  planning_date date not null default current_date,
  title text,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  planner_mode text not null default 'browser_geolocation'
    check (planner_mode in ('browser_geolocation', 'warehouse', 'first_stop')),
  optimization_provider text not null default 'heuristic'
    check (optimization_provider in ('heuristic', 'google_route_optimization', 'google_routes_matrix', 'tomtom_waypoint_optimization')),
  provider_status text not null default 'draft'
    check (provider_status in ('draft', 'ready', 'fallback', 'error')),
  start_latitude numeric(10, 7),
  start_longitude numeric(10, 7),
  end_latitude numeric(10, 7),
  end_longitude numeric(10, 7),
  return_to_start boolean not null default true,
  stop_count integer not null default 0,
  estimated_distance_km numeric(10, 2),
  estimated_drive_minutes integer,
  estimated_service_minutes integer,
  route_payload jsonb not null default '{}'::jsonb,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists route_plans_planning_date_idx
  on public.route_plans (planning_date desc);

create index if not exists route_plans_vehicle_idx
  on public.route_plans (vehicle_id);

create table if not exists public.route_plan_stops (
  id bigint generated by default as identity primary key,
  route_plan_id bigint not null references public.route_plans (id) on delete cascade,
  location_id bigint references public.locations (id) on delete set null,
  service_request_id bigint references public.service_requests (id) on delete set null,
  machine_id bigint references public.machines (id) on delete set null,
  stop_order integer not null,
  stop_kind text not null default 'location_check'
    check (stop_kind in ('service_request', 'location_check', 'restock', 'manual')),
  status text not null default 'planned'
    check (status in ('planned', 'skipped', 'done')),
  title text,
  address_snapshot text,
  city_snapshot text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  priority_snapshot text,
  service_window_snapshot text,
  estimated_service_minutes integer,
  note text,
  created_at timestamp with time zone not null default now(),
  unique (route_plan_id, stop_order)
);

create index if not exists route_plan_stops_plan_idx
  on public.route_plan_stops (route_plan_id, stop_order);

create index if not exists route_plan_stops_location_idx
  on public.route_plan_stops (location_id);

create or replace function public.set_route_plans_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_route_plans_updated_at on public.route_plans;

create trigger trg_route_plans_updated_at
before update on public.route_plans
for each row
execute function public.set_route_plans_updated_at();

alter table public.route_plans enable row level security;
alter table public.route_plan_stops enable row level security;

create policy "Allow read route plans"
on public.route_plans
for select
to authenticated, anon
using (true);

create policy "Allow insert route plans"
on public.route_plans
for insert
to authenticated, anon
with check (true);

create policy "Allow update route plans"
on public.route_plans
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read route plan stops"
on public.route_plan_stops
for select
to authenticated, anon
using (true);

create policy "Allow insert route plan stops"
on public.route_plan_stops
for insert
to authenticated, anon
with check (true);

create policy "Allow update route plan stops"
on public.route_plan_stops
for update
to authenticated, anon
using (true)
with check (true);
