create table if not exists public.route_cash_reports (
  id bigint generated by default as identity primary key,
  route_plan_id bigint references public.route_plans (id) on delete cascade,
  route_plan_stop_id bigint references public.route_plan_stops (id) on delete set null,
  machine_id bigint not null references public.machines (id) on delete cascade,
  location_id bigint references public.locations (id) on delete set null,
  collection_status text not null default 'pending'
    check (collection_status in ('pending', 'collected', 'not_collected')),
  expected_cash_czk numeric(12,2) not null default 0,
  expected_card_czk numeric(12,2) not null default 0,
  expected_total_czk numeric(12,2) not null default 0,
  actual_cash_czk numeric(12,2),
  difference_cash_czk numeric(12,2)
    generated always as (
      case
        when collection_status <> 'collected' or actual_cash_czk is null then null
        else actual_cash_czk - expected_cash_czk
      end
    ) stored,
  telemetry_from_at timestamptz,
  telemetry_to_at timestamptz,
  reported_at timestamptz not null default now(),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (route_plan_id, machine_id)
);

create index if not exists route_cash_reports_machine_idx
  on public.route_cash_reports (machine_id, reported_at desc);

create index if not exists route_cash_reports_status_idx
  on public.route_cash_reports (collection_status, reported_at desc);

create or replace function public.set_route_cash_reports_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_route_cash_reports_updated_at on public.route_cash_reports;
create trigger trg_route_cash_reports_updated_at
before update on public.route_cash_reports
for each row
execute function public.set_route_cash_reports_updated_at();

alter table public.route_cash_reports enable row level security;

drop policy if exists "Allow read route cash reports" on public.route_cash_reports;
create policy "Allow read route cash reports" on public.route_cash_reports
for select to authenticated, anon using (true);

drop policy if exists "Allow write route cash reports" on public.route_cash_reports;
create policy "Allow write route cash reports" on public.route_cash_reports
for all to authenticated, anon using (true) with check (true);
