-- OLVEND v40: měsíční porovnání plánovaných a skutečných kilometrů tras.
create table if not exists public.route_distance_explanations (
  id bigint generated by default as identity primary key,
  vehicle_operation_log_id bigint not null references public.vehicle_operation_logs(id) on delete cascade,
  route_plan_id bigint references public.route_plans(id) on delete set null,
  driver_employee_id uuid references public.employees(id) on delete set null,
  reason_code text not null check (reason_code in ('detour','extra_stop','service','warehouse_return','traffic','other')),
  distance_km numeric(10,2) not null check (distance_km > 0),
  note text,
  approved_by_employee_id uuid not null references public.employees(id) on delete restrict,
  approved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists route_distance_explanations_log_idx
  on public.route_distance_explanations(vehicle_operation_log_id, approved_at desc);
create index if not exists route_distance_explanations_driver_idx
  on public.route_distance_explanations(driver_employee_id, approved_at desc);

alter table public.route_distance_explanations enable row level security;
revoke all on public.route_distance_explanations from anon, authenticated;

create or replace function public.set_route_distance_explanation_updated_at_v40()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_route_distance_explanation_updated_at_v40 on public.route_distance_explanations;
create trigger trg_route_distance_explanation_updated_at_v40
before update on public.route_distance_explanations
for each row execute function public.set_route_distance_explanation_updated_at_v40();

create or replace function public.get_route_distance_report_v40(
  p_date_from date,
  p_date_to date,
  p_employee_id uuid default null,
  p_vehicle_id bigint default null
)
returns table (
  log_id bigint,
  report_date date,
  employee_id uuid,
  employee_name text,
  vehicle_id bigint,
  vehicle_name text,
  vehicle_plate text,
  route_ids bigint[],
  route_titles text[],
  route_count integer,
  planned_km numeric,
  actual_km numeric,
  difference_km numeric,
  explained_km numeric,
  unexplained_km numeric,
  start_odometer_km integer,
  end_odometer_km integer,
  log_status text,
  explanations jsonb
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.employees e
    where e.auth_user_id = auth.uid()
      and e.active is not false
      and (
        lower(coalesce(e.role, '')) like '%admin%'
        or lower(coalesce(e.role, '')) like '%manaž%'
        or lower(coalesce(e.role, '')) like '%manaz%'
        or lower(coalesce(e.role, '')) like '%manager%'
        or lower(coalesce(e.role, '')) like '%vedouc%'
        or lower(coalesce(e.role, '')) like '%majitel%'
      )
  ) then
    raise exception 'Report kilometrů je dostupný pouze vedení.';
  end if;
  if p_date_from is null or p_date_to is null or p_date_to < p_date_from then
    raise exception 'Neplatné období reportu.';
  end if;
  if p_date_to - p_date_from > 370 then
    raise exception 'Report lze načíst nejvýše za 370 dní.';
  end if;

  return query
  with route_days as (
    select
      rp.planning_date,
      rp.planned_employee_id,
      rp.vehicle_id,
      array_agg(rp.id order by rp.id) as route_ids,
      array_agg(coalesce(nullif(trim(rp.title), ''), 'Trasa #' || rp.id::text) order by rp.id) as route_titles,
      count(*)::integer as route_count,
      round(sum(coalesce(rp.estimated_distance_km, 0))::numeric, 2) as planned_km
    from public.route_plans rp
    where rp.planning_date between p_date_from and p_date_to
      and rp.execution_status in ('done', 'completed')
      and rp.planned_employee_id is not null
      and rp.vehicle_id is not null
      and (p_employee_id is null or rp.planned_employee_id = p_employee_id)
      and (p_vehicle_id is null or rp.vehicle_id = p_vehicle_id)
    group by rp.planning_date, rp.planned_employee_id, rp.vehicle_id
  ), ranked_logs as (
    select
      vol.*,
      row_number() over (
        partition by vol.log_date, vol.employee_id, vol.vehicle_id
        order by
          (vol.distance_km is not null) desc,
          (vol.status = 'closed') desc,
          vol.updated_at desc,
          vol.id desc
      ) as row_rank
    from public.vehicle_operation_logs vol
    where vol.log_date between p_date_from and p_date_to
      and (p_employee_id is null or vol.employee_id = p_employee_id)
      and (p_vehicle_id is null or vol.vehicle_id = p_vehicle_id)
  ), explanation_totals as (
    select
      rde.vehicle_operation_log_id,
      round(sum(rde.distance_km)::numeric, 2) as explained_km,
      jsonb_agg(jsonb_build_object(
        'id', rde.id,
        'reason_code', rde.reason_code,
        'distance_km', rde.distance_km,
        'note', rde.note,
        'approved_at', rde.approved_at,
        'approved_by', trim(concat_ws(' ', approver.name, approver.surname))
      ) order by rde.approved_at desc, rde.id desc) as explanations
    from public.route_distance_explanations rde
    left join public.employees approver on approver.id = rde.approved_by_employee_id
    group by rde.vehicle_operation_log_id
  )
  select
    vol.id as log_id,
    rd.planning_date as report_date,
    rd.planned_employee_id as employee_id,
    coalesce(nullif(trim(concat_ws(' ', employee.name, employee.surname)), ''), employee.email, 'Bez pracovníka') as employee_name,
    rd.vehicle_id,
    coalesce(nullif(trim(vehicle.name), ''), 'Vozidlo') as vehicle_name,
    coalesce(vehicle.plate, '') as vehicle_plate,
    rd.route_ids,
    rd.route_titles,
    rd.route_count,
    rd.planned_km,
    vol.distance_km::numeric as actual_km,
    case when vol.distance_km is null then null else round((vol.distance_km::numeric - rd.planned_km)::numeric, 2) end as difference_km,
    round(coalesce(et.explained_km, 0)::numeric, 2) as explained_km,
    case
      when vol.distance_km is null then null
      else round(greatest(vol.distance_km::numeric - rd.planned_km - coalesce(et.explained_km, 0), 0)::numeric, 2)
    end as unexplained_km,
    vol.start_odometer_km,
    vol.end_odometer_km,
    vol.status as log_status,
    coalesce(et.explanations, '[]'::jsonb) as explanations
  from route_days rd
  left join ranked_logs vol
    on vol.log_date = rd.planning_date
   and vol.employee_id = rd.planned_employee_id
   and vol.vehicle_id = rd.vehicle_id
   and vol.row_rank = 1
  left join explanation_totals et on et.vehicle_operation_log_id = vol.id
  left join public.employees employee on employee.id = rd.planned_employee_id
  left join public.vehicles vehicle on vehicle.id = rd.vehicle_id
  order by rd.planning_date desc, 4, 6;
end;
$$;

revoke all on function public.get_route_distance_report_v40(date, date, uuid, bigint) from public, anon;
grant execute on function public.get_route_distance_report_v40(date, date, uuid, bigint) to authenticated;

create or replace function public.add_route_distance_explanation_v40(
  p_vehicle_operation_log_id bigint,
  p_route_plan_id bigint,
  p_reason_code text,
  p_distance_km numeric,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_manager public.employees%rowtype;
  v_log public.vehicle_operation_logs%rowtype;
  v_plan_km numeric;
  v_existing_km numeric;
  v_id bigint;
begin
  select * into v_manager from public.employees e
  where e.auth_user_id = auth.uid() and e.active is not false;
  if v_manager.id is null or not (
    lower(coalesce(v_manager.role, '')) like '%admin%'
    or lower(coalesce(v_manager.role, '')) like '%manaž%'
    or lower(coalesce(v_manager.role, '')) like '%manaz%'
    or lower(coalesce(v_manager.role, '')) like '%manager%'
    or lower(coalesce(v_manager.role, '')) like '%vedouc%'
    or lower(coalesce(v_manager.role, '')) like '%majitel%'
  ) then
    raise exception 'Odchylku může vysvětlit pouze vedení.';
  end if;
  if p_reason_code not in ('detour','extra_stop','service','warehouse_return','traffic','other') then
    raise exception 'Vyber platný důvod.';
  end if;
  if p_distance_km is null or p_distance_km <= 0 then
    raise exception 'Počet kilometrů musí být větší než nula.';
  end if;

  select * into v_log from public.vehicle_operation_logs where id = p_vehicle_operation_log_id for update;
  if v_log.id is null or v_log.distance_km is null then
    raise exception 'Výjezd nemá uzavřené skutečné kilometry.';
  end if;

  select coalesce(sum(rp.estimated_distance_km), 0) into v_plan_km
  from public.route_plans rp
  where rp.planning_date = v_log.log_date
    and rp.planned_employee_id = v_log.employee_id
    and rp.vehicle_id = v_log.vehicle_id
    and rp.execution_status in ('done','completed');
  select coalesce(sum(rde.distance_km), 0) into v_existing_km
  from public.route_distance_explanations rde
  where rde.vehicle_operation_log_id = v_log.id;
  if v_existing_km + p_distance_km > greatest(v_log.distance_km::numeric - v_plan_km, 0) + 0.01 then
    raise exception 'Vysvětlené kilometry nemohou překročit kladnou odchylku výjezdu.';
  end if;

  insert into public.route_distance_explanations(
    vehicle_operation_log_id, route_plan_id, driver_employee_id, reason_code,
    distance_km, note, approved_by_employee_id
  ) values (
    v_log.id, p_route_plan_id, v_log.employee_id, p_reason_code,
    round(p_distance_km, 2), nullif(trim(coalesce(p_note, '')), ''), v_manager.id
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.add_route_distance_explanation_v40(bigint, bigint, text, numeric, text) from public, anon;
grant execute on function public.add_route_distance_explanation_v40(bigint, bigint, text, numeric, text) to authenticated;

create or replace function public.delete_route_distance_explanation_v40(p_explanation_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_employee public.employees%rowtype;
begin
  select * into v_employee from public.employees e
  where e.auth_user_id = auth.uid() and e.active is not false;
  if v_employee.id is null or not (
    lower(coalesce(v_employee.role, '')) like '%admin%'
    or lower(coalesce(v_employee.role, '')) like '%manaž%'
    or lower(coalesce(v_employee.role, '')) like '%manaz%'
    or lower(coalesce(v_employee.role, '')) like '%manager%'
    or lower(coalesce(v_employee.role, '')) like '%vedouc%'
    or lower(coalesce(v_employee.role, '')) like '%majitel%'
  ) then
    raise exception 'Vysvětlení může odebrat pouze vedení.';
  end if;
  delete from public.route_distance_explanations where id = p_explanation_id;
  return found;
end;
$$;

revoke all on function public.delete_route_distance_explanation_v40(bigint) from public, anon;
grant execute on function public.delete_route_distance_explanation_v40(bigint) to authenticated;
