create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations (id) on delete cascade,
  title text not null,
  description text,
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'critical')),
  status text not null default 'new'
    check (status in ('new', 'assigned', 'in_progress', 'done', 'cancelled')),
  due_date date,
  estimated_duration_minutes integer,
  actual_duration_minutes integer,
  service_started_at timestamp with time zone,
  service_finished_at timestamp with time zone,
  last_service_result text
    check (last_service_result in ('fixed', 'return_with_part')),
  assigned_employee_id uuid references public.employees (id) on delete set null,
  created_by uuid references public.employees (id) on delete set null,
  resolution_note text,
  resolved_at timestamp with time zone,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists service_requests_location_idx
  on public.service_requests (location_id);

create index if not exists service_requests_assigned_idx
  on public.service_requests (assigned_employee_id);

create index if not exists service_requests_status_idx
  on public.service_requests (status);

create index if not exists service_requests_due_date_idx
  on public.service_requests (due_date);

create or replace function public.set_service_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.service_started_at is not null and new.service_finished_at is not null then
    new.actual_duration_minutes = greatest(0, floor(extract(epoch from (new.service_finished_at - new.service_started_at)) / 60));
  end if;
  if new.status = 'done' and new.resolved_at is null then
    new.resolved_at = now();
  end if;
  if new.status <> 'done' then
    new.resolved_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_service_requests_updated_at on public.service_requests;

create trigger trg_service_requests_updated_at
before update on public.service_requests
for each row
execute function public.set_service_requests_updated_at();

alter table public.service_requests enable row level security;

create policy "Allow read service requests"
on public.service_requests
for select
to authenticated, anon
using (true);

create policy "Allow insert service requests"
on public.service_requests
for insert
to authenticated, anon
with check (true);

create policy "Allow update service requests"
on public.service_requests
for update
to authenticated, anon
using (true)
with check (true);
