alter table public.service_requests
  alter column location_id drop not null;

alter table public.service_requests
  add column if not exists service_scope text not null default 'internal',
  add column if not exists external_service_place text,
  add column if not exists external_service_address text,
  add column if not exists external_customer_name text,
  add column if not exists external_customer_company_id text,
  add column if not exists external_customer_contact text,
  add column if not exists external_customer_email text,
  add column if not exists external_customer_phone text,
  add column if not exists external_billing_address text,
  add column if not exists external_order_number text,
  add column if not exists billable boolean not null default false,
  add column if not exists billing_status text not null default 'not_billable',
  add column if not exists billing_note text,
  add column if not exists service_onsite_minutes integer,
  add column if not exists travel_distance_km numeric(10,1),
  add column if not exists billable_travel_minutes integer,
  add column if not exists billable_work_minutes integer,
  add column if not exists billable_materials_summary text,
  add column if not exists customer_visible_note text;

alter table public.service_requests
  drop constraint if exists service_requests_service_scope_check;

alter table public.service_requests
  add constraint service_requests_service_scope_check
  check (service_scope in ('internal', 'external'));

alter table public.service_requests
  drop constraint if exists service_requests_billing_status_check;

alter table public.service_requests
  add constraint service_requests_billing_status_check
  check (billing_status in ('not_billable', 'ready', 'invoiced', 'paid', 'cancelled'));

update public.service_requests
set
  billable = true,
  billing_status = case
    when billing_status = 'not_billable' then 'ready'
    else billing_status
  end
where service_scope = 'external'
  and billable is distinct from true;

create index if not exists service_requests_scope_idx
  on public.service_requests (service_scope, billing_status);

create table if not exists public.service_request_signatures (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests (id) on delete cascade,
  signer_name text not null,
  signer_role text,
  signature_data text not null,
  signed_at timestamp with time zone not null default now(),
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  unique (service_request_id)
);

create index if not exists service_request_signatures_request_idx
  on public.service_request_signatures (service_request_id);

create table if not exists public.service_request_protocols (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests (id) on delete cascade,
  protocol_kind text not null default 'external_service',
  protocol_html text,
  generated_at timestamp with time zone not null default now(),
  generated_by uuid references public.employees (id) on delete set null,
  billing_status_snapshot text,
  unique (service_request_id)
);

create index if not exists service_request_protocols_request_idx
  on public.service_request_protocols (service_request_id);

alter table public.service_request_signatures enable row level security;
alter table public.service_request_protocols enable row level security;

drop policy if exists "Allow read service request signatures" on public.service_request_signatures;
create policy "Allow read service request signatures"
on public.service_request_signatures
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert service request signatures" on public.service_request_signatures;
create policy "Allow insert service request signatures"
on public.service_request_signatures
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update service request signatures" on public.service_request_signatures;
create policy "Allow update service request signatures"
on public.service_request_signatures
for update
to authenticated, anon
using (true)
with check (true);

drop policy if exists "Allow read service request protocols" on public.service_request_protocols;
create policy "Allow read service request protocols"
on public.service_request_protocols
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert service request protocols" on public.service_request_protocols;
create policy "Allow insert service request protocols"
on public.service_request_protocols
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update service request protocols" on public.service_request_protocols;
create policy "Allow update service request protocols"
on public.service_request_protocols
for update
to authenticated, anon
using (true)
with check (true);
