create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  note text,
  status text not null default 'new'
    check (status in ('new', 'in_progress', 'done')),
  priority text not null default 'normal'
    check (priority in ('normal', 'important', 'today')),
  due_date date,
  assigned_employee_id uuid references public.employees (id) on delete set null,
  created_by uuid references public.employees (id) on delete set null,
  completed_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists tasks_status_idx
  on public.tasks (status);

create index if not exists tasks_due_date_idx
  on public.tasks (due_date);

create index if not exists tasks_assigned_idx
  on public.tasks (assigned_employee_id);

create or replace function public.set_tasks_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.status = 'done' and new.completed_at is null then
    new.completed_at = now();
  end if;
  if new.status <> 'done' then
    new.completed_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_tasks_updated_at on public.tasks;

create trigger trg_tasks_updated_at
before update on public.tasks
for each row
execute function public.set_tasks_updated_at();

alter table public.tasks enable row level security;

drop policy if exists "Allow read tasks" on public.tasks;
create policy "Allow read tasks"
on public.tasks
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert tasks" on public.tasks;
create policy "Allow insert tasks"
on public.tasks
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update tasks" on public.tasks;
create policy "Allow update tasks"
on public.tasks
for update
to authenticated, anon
using (true)
with check (true);
