begin;

alter table public.technical_jobs
  drop constraint if exists technical_jobs_job_type_check;

alter table public.technical_jobs
  add constraint technical_jobs_job_type_check
  check (job_type in (
    'service', 'installation', 'deinstallation', 'transfer', 'revision',
    'workshop_prep', 'delivery', 'general'
  ));

alter table public.locations
  add column if not exists customer_id bigint references public.business_contacts(id) on delete set null,
  add column if not exists contact_email text;

create index if not exists locations_customer_idx on public.locations(customer_id);

alter table public.technical_jobs
  add column if not exists customer_id bigint references public.business_contacts(id) on delete set null,
  add column if not exists source_stock_location_id bigint references public.stock_locations(id) on delete set null,
  add column if not exists target_stock_location_id bigint references public.stock_locations(id) on delete set null,
  add column if not exists assignment_notified_at timestamptz,
  add column if not exists assignment_notification_key text;

create index if not exists technical_jobs_customer_idx on public.technical_jobs(customer_id);
create index if not exists technical_jobs_source_stock_idx on public.technical_jobs(source_stock_location_id);
create index if not exists technical_jobs_target_stock_idx on public.technical_jobs(target_stock_location_id);

create table if not exists public.technical_job_material_items (
  id bigint generated by default as identity primary key,
  technical_job_id bigint not null references public.technical_jobs(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  source_stock_location_id bigint references public.stock_locations(id) on delete set null,
  requested_quantity numeric(12,3) not null default 0 check (requested_quantity >= 0),
  prepared_quantity numeric(12,3) not null default 0 check (prepared_quantity >= 0),
  used_quantity numeric(12,3) not null default 0 check (used_quantity >= 0),
  returned_quantity numeric(12,3) not null default 0 check (returned_quantity >= 0),
  unit text not null default 'ks',
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (technical_job_id, product_id, source_stock_location_id)
);

create index if not exists technical_job_material_job_idx
  on public.technical_job_material_items(technical_job_id, sort_order);
create index if not exists technical_job_material_product_idx
  on public.technical_job_material_items(product_id);
create index if not exists technical_job_material_stock_idx
  on public.technical_job_material_items(source_stock_location_id);

create or replace function public.set_technical_job_material_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_technical_job_material_updated_at on public.technical_job_material_items;
create trigger trg_technical_job_material_updated_at
before update on public.technical_job_material_items
for each row execute function public.set_technical_job_material_updated_at();

alter table public.technical_job_material_items enable row level security;

drop policy if exists "Allow read technical job materials" on public.technical_job_material_items;
create policy "Allow read technical job materials"
on public.technical_job_material_items for select to authenticated, anon using (true);

drop policy if exists "Allow insert technical job materials" on public.technical_job_material_items;
create policy "Allow insert technical job materials"
on public.technical_job_material_items for insert to authenticated, anon with check (true);

drop policy if exists "Allow update technical job materials" on public.technical_job_material_items;
create policy "Allow update technical job materials"
on public.technical_job_material_items for update to authenticated, anon using (true) with check (true);

drop policy if exists "Allow delete technical job materials" on public.technical_job_material_items;
create policy "Allow delete technical job materials"
on public.technical_job_material_items for delete to authenticated, anon using (true);

create or replace view public.technical_job_material_availability_v29 as
select
  material.id,
  material.technical_job_id,
  material.product_id,
  material.source_stock_location_id,
  material.requested_quantity,
  material.prepared_quantity,
  material.used_quantity,
  material.returned_quantity,
  material.unit,
  material.note,
  material.sort_order,
  product.name as product_name,
  product.sku as product_sku,
  stock.name as stock_location_name,
  coalesce(balance.quantity_on_hand, 0) as quantity_on_hand,
  coalesce(balance.reserved_quantity, 0) as reserved_quantity,
  greatest(coalesce(balance.quantity_on_hand, 0) - coalesce(balance.reserved_quantity, 0), 0) as available_quantity
from public.technical_job_material_items material
join public.products product on product.id = material.product_id
left join public.stock_locations stock on stock.id = material.source_stock_location_id
left join lateral (
  select
    sum(coalesce(item.quantity_on_hand, 0)) as quantity_on_hand,
    sum(coalesce(item.reserved_quantity, 0)) as reserved_quantity
  from public.stock_location_balances item
  where item.product_id = material.product_id
    and item.stock_location_id = material.source_stock_location_id
) balance on true;

grant select on public.technical_job_material_availability_v29 to authenticated, anon;

create unique index if not exists email_notification_queue_technical_job_dedupe_unique
  on public.email_notification_queue ((metadata ->> 'dedupe_key'))
  where kind in ('technical_job_assignment', 'technical_job_update');

create or replace function public.queue_technical_job_assignment_notification(
  p_technical_job_id bigint,
  p_force_update boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job public.technical_jobs%rowtype;
  v_employee record;
  v_location record;
  v_source record;
  v_target record;
  v_source_stock record;
  v_target_stock record;
  v_machine record;
  v_customer record;
  v_materials jsonb;
  v_checklist jsonb;
  v_kind text;
  v_subject text;
  v_body text;
  v_payload jsonb;
  v_fingerprint text;
  v_dedupe_key text;
  v_queue_id bigint;
begin
  select * into v_job from public.technical_jobs where id = p_technical_job_id and active;
  if v_job.id is null then raise exception 'Technical job % was not found', p_technical_job_id; end if;
  if v_job.assigned_employee_id is null then
    return jsonb_build_object('queued', false, 'reason', 'unassigned');
  end if;

  select id, name, surname, email, active into v_employee
  from public.employees where id = v_job.assigned_employee_id;
  if not coalesce(v_employee.active, false) or nullif(trim(v_employee.email), '') is null then
    return jsonb_build_object('queued', false, 'reason', 'employee_email_missing');
  end if;

  select id, name, city, address, contact_person, contact_phone, contact_email into v_location
  from public.locations where id = v_job.location_id;
  select id, name, city, address, contact_person, contact_phone, contact_email into v_source
  from public.locations where id = v_job.source_location_id;
  select id, name, city, address, contact_person, contact_phone, contact_email into v_target
  from public.locations where id = v_job.target_location_id;
  select id, name into v_source_stock
  from public.stock_locations where id = v_job.source_stock_location_id;
  select id, name into v_target_stock
  from public.stock_locations where id = v_job.target_stock_location_id;
  select id, name, machine_type, brand, model, serial_number, evidence_number into v_machine
  from public.machines where id = v_job.machine_id;
  select id, name, company_id, tax_id, contact_name, email, phone, billing_address, delivery_address into v_customer
  from public.business_contacts where id = v_job.customer_id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'product_id', material.product_id,
    'product_name', material.product_name,
    'quantity', material.requested_quantity,
    'prepared_quantity', material.prepared_quantity,
    'unit', material.unit,
    'stock_location', material.stock_location_name,
    'available_quantity', material.available_quantity,
    'note', material.note
  ) order by material.sort_order, material.id), '[]'::jsonb)
  into v_materials
  from public.technical_job_material_availability_v29 material
  where material.technical_job_id = v_job.id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'section', item.section,
    'label', item.label,
    'required', item.required,
    'completed', item.completed
  ) order by item.sort_order, item.id), '[]'::jsonb)
  into v_checklist
  from public.technical_job_checklist_items item
  where item.technical_job_id = v_job.id;

  v_payload := jsonb_build_object(
    'technical_job_id', v_job.id,
    'job_type', v_job.job_type,
    'title', v_job.title,
    'description', v_job.description,
    'priority', v_job.priority,
    'status', v_job.status,
    'planned_date', v_job.planned_date,
    'due_at', v_job.due_at,
    'workshop_note', v_job.workshop_note,
    'configuration', coalesce(v_job.configuration_payload, '{}'::jsonb),
    'employee', to_jsonb(v_employee),
    'location', to_jsonb(v_location),
    'source_location', to_jsonb(v_source),
    'target_location', to_jsonb(v_target),
    'source_stock_location', to_jsonb(v_source_stock),
    'target_stock_location', to_jsonb(v_target_stock),
    'machine', to_jsonb(v_machine),
    'customer', to_jsonb(v_customer),
    'materials', v_materials,
    'checklist', v_checklist
  );

  v_fingerprint := md5(v_payload::text);
  v_dedupe_key := format('technical-job:%s:%s:%s', v_job.id, v_job.assigned_employee_id, v_fingerprint);
  v_kind := case when v_job.assignment_notified_at is null and not p_force_update
    then 'technical_job_assignment' else 'technical_job_update' end;
  v_subject := format(
    'OLVEND: %s · %s',
    case v_job.job_type
      when 'service' then 'nový servis'
      when 'workshop_prep' then 'nachystat automat'
      when 'installation' then 'nová instalace'
      when 'transfer' then 'nový přesun'
      when 'deinstallation' then 'nový odvoz'
      when 'delivery' then 'nový závoz / odvoz'
      else 'nový požadavek'
    end,
    v_job.title
  );
  v_body := concat_ws(E'\n',
    v_job.title,
    'Termín: ' || coalesce(to_char(v_job.due_at at time zone 'Europe/Prague', 'DD.MM.YYYY HH24:MI'), to_char(v_job.planned_date, 'DD.MM.YYYY'), 'bez termínu'),
    'Priorita: ' || v_job.priority,
    nullif(v_job.description, '')
  );

  insert into public.email_notification_queue(
    employee_id, kind, subject, body, action_url, metadata
  ) values (
    v_job.assigned_employee_id,
    v_kind,
    v_subject,
    v_body,
    'technical-jobs.html?job=' || v_job.id,
    v_payload || jsonb_build_object('dedupe_key', v_dedupe_key)
  )
  on conflict do nothing
  returning id into v_queue_id;

  if v_queue_id is not null then
    update public.technical_jobs
    set assignment_notified_at = now(), assignment_notification_key = v_dedupe_key
    where id = v_job.id;
  end if;

  return jsonb_build_object(
    'queued', v_queue_id is not null,
    'queue_id', v_queue_id,
    'kind', v_kind,
    'dedupe_key', v_dedupe_key
  );
end;
$$;

grant execute on function public.queue_technical_job_assignment_notification(bigint, boolean) to authenticated;

commit;
