begin;

create table if not exists public.technical_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null
    check (job_type in ('service', 'installation', 'deinstallation', 'transfer', 'revision')),
  status text not null default 'new'
    check (status in ('new', 'planned', 'assigned', 'workshop_ready', 'on_the_way', 'on_site', 'in_progress', 'pending_confirmation', 'closed', 'blocked', 'postponed', 'cancelled')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'critical')),
  title text not null,
  description text,
  note text,
  result text,
  location_id bigint references public.locations (id) on delete set null,
  machine_id bigint references public.machines (id) on delete set null,
  source_location_id bigint references public.locations (id) on delete set null,
  target_location_id bigint references public.locations (id) on delete set null,
  assigned_employee_id uuid references public.employees (id) on delete set null,
  workshop_ready boolean not null default false,
  workshop_ready_at timestamp with time zone,
  workshop_ready_by uuid references public.employees (id) on delete set null,
  workshop_note text,
  configuration_kind text not null default 'general'
    check (configuration_kind in ('general', 'food', 'coffee')),
  configuration_payload jsonb not null default '{}'::jsonb,
  planned_date date,
  due_at timestamp with time zone,
  arrived_at timestamp with time zone,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  submitted_at timestamp with time zone,
  manager_confirmed_at timestamp with time zone,
  manager_confirmed_by uuid references public.employees (id) on delete set null,
  qr_token text not null unique,
  protocol_url text,
  active boolean not null default true,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists technical_jobs_type_idx
  on public.technical_jobs (job_type);

create index if not exists technical_jobs_status_idx
  on public.technical_jobs (status);

create index if not exists technical_jobs_priority_idx
  on public.technical_jobs (priority);

create index if not exists technical_jobs_planned_date_idx
  on public.technical_jobs (planned_date);

create index if not exists technical_jobs_assigned_idx
  on public.technical_jobs (assigned_employee_id);

create index if not exists technical_jobs_location_idx
  on public.technical_jobs (location_id);

create index if not exists technical_jobs_machine_idx
  on public.technical_jobs (machine_id);

create table if not exists public.technical_job_checklist_items (
  id bigint generated by default as identity primary key,
  technical_job_id bigint not null references public.technical_jobs (id) on delete cascade,
  section text,
  label text not null,
  required boolean not null default true,
  completed boolean not null default false,
  completed_at timestamp with time zone,
  completed_by uuid references public.employees (id) on delete set null,
  note text,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists technical_job_checklist_job_idx
  on public.technical_job_checklist_items (technical_job_id, sort_order);

create table if not exists public.technical_job_signatures (
  id bigint generated by default as identity primary key,
  technical_job_id bigint not null references public.technical_jobs (id) on delete cascade,
  signer_name text not null,
  signer_role text,
  signature_data text not null,
  signed_at timestamp with time zone not null default now(),
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  unique (technical_job_id)
);

create table if not exists public.technical_job_protocols (
  id bigint generated by default as identity primary key,
  technical_job_id bigint not null references public.technical_jobs (id) on delete cascade,
  protocol_kind text not null default 'standard',
  protocol_html text,
  generated_at timestamp with time zone not null default now(),
  generated_by uuid references public.employees (id) on delete set null,
  unique (technical_job_id)
);

create table if not exists public.technical_job_attachments (
  id bigint generated by default as identity primary key,
  technical_job_id bigint not null references public.technical_jobs (id) on delete cascade,
  attachment_type text not null default 'photo',
  attachment_url text not null,
  note text,
  created_by uuid references public.employees (id) on delete set null,
  created_at timestamp with time zone not null default now()
);

create or replace function public.set_technical_jobs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.status = 'workshop_ready' and new.workshop_ready_at is null then
    new.workshop_ready_at = now();
  end if;
  if new.status = 'pending_confirmation' and new.submitted_at is null then
    new.submitted_at = now();
  end if;
  if new.status = 'closed' and new.finished_at is null then
    new.finished_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_technical_jobs_updated_at on public.technical_jobs;

create trigger trg_technical_jobs_updated_at
before update on public.technical_jobs
for each row
execute function public.set_technical_jobs_updated_at();

create or replace function public.set_technical_job_checklist_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if new.completed and new.completed_at is null then
    new.completed_at = now();
  end if;
  if not new.completed then
    new.completed_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_technical_job_checklist_updated_at on public.technical_job_checklist_items;

create trigger trg_technical_job_checklist_updated_at
before update on public.technical_job_checklist_items
for each row
execute function public.set_technical_job_checklist_updated_at();

alter table public.technical_jobs enable row level security;
alter table public.technical_job_checklist_items enable row level security;
alter table public.technical_job_signatures enable row level security;
alter table public.technical_job_protocols enable row level security;
alter table public.technical_job_attachments enable row level security;

create policy "Allow read technical jobs"
on public.technical_jobs
for select
to authenticated, anon
using (true);

create policy "Allow insert technical jobs"
on public.technical_jobs
for insert
to authenticated, anon
with check (true);

create policy "Allow update technical jobs"
on public.technical_jobs
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read technical job checklist items"
on public.technical_job_checklist_items
for select
to authenticated, anon
using (true);

create policy "Allow insert technical job checklist items"
on public.technical_job_checklist_items
for insert
to authenticated, anon
with check (true);

create policy "Allow update technical job checklist items"
on public.technical_job_checklist_items
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read technical job signatures"
on public.technical_job_signatures
for select
to authenticated, anon
using (true);

create policy "Allow insert technical job signatures"
on public.technical_job_signatures
for insert
to authenticated, anon
with check (true);

create policy "Allow update technical job signatures"
on public.technical_job_signatures
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read technical job protocols"
on public.technical_job_protocols
for select
to authenticated, anon
using (true);

create policy "Allow insert technical job protocols"
on public.technical_job_protocols
for insert
to authenticated, anon
with check (true);

create policy "Allow update technical job protocols"
on public.technical_job_protocols
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read technical job attachments"
on public.technical_job_attachments
for select
to authenticated, anon
using (true);

create policy "Allow insert technical job attachments"
on public.technical_job_attachments
for insert
to authenticated, anon
with check (true);

create policy "Allow update technical job attachments"
on public.technical_job_attachments
for update
to authenticated, anon
using (true)
with check (true);

commit;
