begin;

-- Zasahy technika do zasobniku pri servisu jsou samostatne auditovatelne.
-- Ukladaji se pouze zasobniky, ktere technik vybral a skutecne zmenil.
create table if not exists public.service_request_container_actions (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests(id) on delete cascade,
  machine_id bigint not null references public.machines(id) on delete cascade,
  coffee_container_id bigint not null references public.machine_coffee_containers(id) on delete restrict,
  product_id bigint references public.products(id) on delete set null,
  source_stock_location_id bigint references public.stock_locations(id) on delete set null,
  employee_id uuid references public.employees(id) on delete set null,
  operation_key uuid not null,
  system_quantity numeric(12,3),
  actual_before_quantity numeric(12,3) not null check (actual_before_quantity >= 0),
  added_quantity numeric(12,3) not null default 0 check (added_quantity >= 0),
  final_quantity numeric(12,3) not null check (final_quantity >= 0),
  capacity_quantity numeric(12,3),
  unit text not null default 'ks',
  note text,
  created_at timestamptz not null default now(),
  unique (operation_key, coffee_container_id)
);

create index if not exists service_request_container_actions_request_idx
  on public.service_request_container_actions(service_request_id, created_at desc);

create index if not exists service_request_container_actions_machine_idx
  on public.service_request_container_actions(machine_id, created_at desc);

alter table public.service_request_container_actions enable row level security;

drop policy if exists "Allow read service container actions" on public.service_request_container_actions;
create policy "Allow read service container actions"
on public.service_request_container_actions for select to authenticated using (
  exists (
    select 1
    from public.service_requests request
    join public.employees employee
      on employee.auth_user_id = auth.uid()
     and coalesce(employee.active, true)
    where request.id = service_request_id
      and (
        request.assigned_employee_id = employee.id
        or lower(coalesce(employee.role, '')) in ('admin', 'manager', 'vedoucí', 'vedouci')
      )
  )
);

-- Klient nema primy zapis. RPC nize kontroluje prihlaseni, servis, vozidlo,
-- kapacitu i skutecnou skladovou zasobu a vse provede v jedne transakci.
create or replace function public.apply_technician_service_container_stock_v51(
  p_service_request_id bigint,
  p_employee_id uuid,
  p_vehicle_stock_location_id bigint,
  p_operation_key uuid,
  p_items jsonb,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_employee_id uuid;
  v_role text;
  v_request public.service_requests%rowtype;
  v_container public.machine_coffee_containers%rowtype;
  v_machine_stock_location_id bigint;
  v_vehicle_id bigint;
  v_vehicle_name text;
  v_item jsonb;
  v_actual_before numeric(12,3);
  v_added numeric(12,3);
  v_added_stock numeric(12,3);
  v_final numeric(12,3);
  v_remaining numeric(12,3);
  v_take numeric(12,3);
  v_available numeric(12,3);
  v_available_display numeric(12,3);
  v_product_base_unit text;
  v_movements jsonb;
  v_balance record;
  v_changed_count integer := 0;
  v_refill_count integer := 0;
  v_today date := (now() at time zone 'Europe/Prague')::date;
begin
  if p_operation_key is null then
    raise exception 'Chybí identifikátor servisního zápisu.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Není vybraný žádný změněný zásobník.';
  end if;

  select employee.id, lower(coalesce(employee.role, ''))
  into v_auth_employee_id, v_role
  from public.employees employee
  where employee.auth_user_id = auth.uid()
    and coalesce(employee.active, true)
  limit 1;

  if v_auth_employee_id is null then
    raise exception 'Přihlášený uživatel nemá aktivní profil zaměstnance.';
  end if;
  if v_auth_employee_id <> p_employee_id
     and v_role not in ('admin', 'manager', 'vedoucí', 'vedouci') then
    raise exception 'Zásah lze uložit jen za přihlášeného technika.';
  end if;

  select request.*
  into v_request
  from public.service_requests request
  where request.id = p_service_request_id
  for update;

  if v_request.id is null then
    raise exception 'Servisní požadavek neexistuje.';
  end if;
  if v_request.machine_id is null then
    raise exception 'Servisní požadavek nemá přiřazený automat.';
  end if;
  if v_request.assigned_employee_id <> p_employee_id
     and v_role not in ('admin', 'manager', 'vedoucí', 'vedouci') then
    raise exception 'Servisní požadavek není přiřazený tomuto technikovi.';
  end if;
  if coalesce(v_request.status, '') <> 'in_progress' then
    raise exception 'Zásobníky lze měnit jen během zahájeného servisu.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('technician-service-stock:' || p_operation_key::text, 0));
  if exists (
    select 1
    from public.service_request_container_actions action
    where action.operation_key = p_operation_key
      and action.service_request_id = p_service_request_id
  ) then
    return jsonb_build_object(
      'inserted', 0,
      'already_applied', true,
      'operation_key', p_operation_key
    );
  end if;

  if p_vehicle_stock_location_id is not null then
    select location.vehicle_id, location.name
    into v_vehicle_id, v_vehicle_name
    from public.stock_locations location
    where location.id = p_vehicle_stock_location_id
      and location.location_type = 'vehicle'
      and coalesce(location.active, true)
    for update;

    if v_vehicle_id is null then
      raise exception 'Vybraný sklad vozidla není aktivní.';
    end if;
    if v_role not in ('admin', 'manager', 'vedoucí', 'vedouci') and not exists (
      select 1
      from public.attendance_days attendance
      where attendance.employee_id = p_employee_id
        and attendance.attendance_date = v_today
        and attendance.vehicle_id = v_vehicle_id
        and attendance.status = 'open'
        and attendance.actual_start is not null
        and attendance.actual_end is null
    ) then
      raise exception 'Materiál lze odepsat jen z vozidla aktuální směny.';
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('machine-stock-location:' || v_request.machine_id::text, 0));
  select location.id
  into v_machine_stock_location_id
  from public.stock_locations location
  where location.location_type = 'machine'
    and location.machine_id = v_request.machine_id
    and coalesce(location.active, true)
  order by location.id
  limit 1
  for update;

  if v_machine_stock_location_id is null then
    insert into public.stock_locations(location_type, name, machine_id, active, note)
    select 'machine', 'Automat · ' || coalesce(machine.evidence_number::text, machine.name, machine.id::text), machine.id, true,
           'Automaticky vytvořeno při servisním doplnění technikem.'
    from public.machines machine
    where machine.id = v_request.machine_id
    returning id into v_machine_stock_location_id;
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    select container.*
    into v_container
    from public.machine_coffee_containers container
    where container.id = nullif(v_item->>'container_id', '')::bigint
      and container.machine_id = v_request.machine_id
      and coalesce(container.active, true)
    for update;

    if v_container.id is null then
      raise exception 'Vybraný zásobník nepatří k automatu tohoto servisu.';
    end if;

    v_actual_before := round(nullif(v_item->>'actual_before_quantity', '')::numeric, 3);
    v_added := round(coalesce(nullif(v_item->>'added_quantity', '')::numeric, 0), 3);
    if v_actual_before is null or v_actual_before < 0 or v_added < 0 then
      raise exception 'Množství u zásobníku % není platné.', v_container.product_name;
    end if;

    v_final := round(v_actual_before + v_added, 3);
    if v_container.capacity_quantity is not null
       and v_final > v_container.capacity_quantity + 0.0001 then
      raise exception 'Zásobník % by překročil kapacitu % %.',
        v_container.product_name, v_container.capacity_quantity, v_container.unit;
    end if;
    if abs(v_actual_before - coalesce(v_container.current_quantity, 0)) < 0.0001
       and v_added < 0.0001 then
      raise exception 'U zásobníku % není žádná změna.', v_container.product_name;
    end if;

    if v_added > 0 then
      if p_vehicle_stock_location_id is null then
        raise exception 'Pro doplnění zásobníku % chybí vozidlo aktuální směny.', v_container.product_name;
      end if;
      if v_container.product_id is null then
        raise exception 'Zásobník % nemá přiřazený skladový produkt.', v_container.product_name;
      end if;

      select lower(trim(coalesce(product.base_unit, v_container.unit)))
      into v_product_base_unit
      from public.products product
      where product.id = v_container.product_id;

      v_added_stock := case
        when lower(trim(coalesce(v_container.unit, ''))) = v_product_base_unit then v_added
        when lower(trim(coalesce(v_container.unit, ''))) = 'g' and v_product_base_unit = 'kg' then v_added / 1000
        when lower(trim(coalesce(v_container.unit, ''))) = 'kg' and v_product_base_unit = 'g' then v_added * 1000
        when lower(trim(coalesce(v_container.unit, ''))) = 'ml' and v_product_base_unit = 'l' then v_added / 1000
        when lower(trim(coalesce(v_container.unit, ''))) = 'l' and v_product_base_unit = 'ml' then v_added * 1000
        else v_added
      end;
      v_added_stock := round(v_added_stock, 3);
      if v_added_stock <= 0 then
        raise exception 'Doplněné množství % je po převodu na skladovou jednotku příliš malé.', v_container.product_name;
      end if;

      v_remaining := v_added_stock;
      v_movements := '[]'::jsonb;
      for v_balance in
        select balance.batch_id,
               greatest(coalesce(balance.quantity_on_hand, 0) - coalesce(balance.reserved_quantity, 0), 0)::numeric(12,3) as available_quantity
        from public.stock_location_balances balance
        left join public.inventory_batches batch on batch.id = balance.batch_id
        where balance.stock_location_id = p_vehicle_stock_location_id
          and balance.product_id = v_container.product_id
          and coalesce(balance.quantity_on_hand, 0) - coalesce(balance.reserved_quantity, 0) > 0.0001
        order by coalesce(batch.use_by_date, batch.best_before_date, '9999-12-31'::date),
                 coalesce(batch.received_at, balance.updated_at), balance.id
      loop
        exit when v_remaining <= 0.0001;
        v_take := least(v_remaining, v_balance.available_quantity);
        v_movements := v_movements || jsonb_build_array(jsonb_build_object(
          'product_id', v_container.product_id,
          'batch_id', v_balance.batch_id,
          'from_stock_location_id', p_vehicle_stock_location_id,
          'to_stock_location_id', v_machine_stock_location_id,
          'movement_type', 'fill_machine',
          'quantity_base_units', v_take,
          'reference_type', 'service_request_container_refill',
          'reference_id', p_operation_key::text || ':container:' || v_container.id::text,
          'note', concat_ws(' · ', 'Servis #' || p_service_request_id::text, v_container.product_name, nullif(trim(coalesce(p_note, '')), ''))
        ));
        v_remaining := round(v_remaining - v_take, 3);
      end loop;

      if v_remaining > 0.0001 then
        select coalesce(sum(greatest(coalesce(balance.quantity_on_hand, 0) - coalesce(balance.reserved_quantity, 0), 0)), 0)
        into v_available
        from public.stock_location_balances balance
        where balance.stock_location_id = p_vehicle_stock_location_id
          and balance.product_id = v_container.product_id;
        v_available_display := case
          when lower(trim(coalesce(v_container.unit, ''))) = v_product_base_unit then v_available
          when v_product_base_unit = 'kg' and lower(trim(coalesce(v_container.unit, ''))) = 'g' then v_available * 1000
          when v_product_base_unit = 'g' and lower(trim(coalesce(v_container.unit, ''))) = 'kg' then v_available / 1000
          when v_product_base_unit = 'l' and lower(trim(coalesce(v_container.unit, ''))) = 'ml' then v_available * 1000
          when v_product_base_unit = 'ml' and lower(trim(coalesce(v_container.unit, ''))) = 'l' then v_available / 1000
          else v_available
        end;
        raise exception 'Nedostatek zásoby: % na % (požadováno % %, dostupné % %).',
          v_container.product_name, coalesce(v_vehicle_name, 'vozidle'), v_added, v_container.unit,
          coalesce(round(v_available_display, 3), 0), v_container.unit;
      end if;

      perform public.apply_stock_movements_v13(v_movements);
      v_refill_count := v_refill_count + 1;
    end if;

    update public.machine_coffee_containers
    set current_quantity = v_final,
        updated_at = now()
    where id = v_container.id;

    insert into public.service_request_container_actions(
      service_request_id, machine_id, coffee_container_id, product_id,
      source_stock_location_id, employee_id, operation_key,
      system_quantity, actual_before_quantity, added_quantity, final_quantity,
      capacity_quantity, unit, note
    ) values (
      p_service_request_id, v_request.machine_id, v_container.id, v_container.product_id,
      case when v_added > 0 then p_vehicle_stock_location_id else null end,
      p_employee_id, p_operation_key,
      v_container.current_quantity, v_actual_before, v_added, v_final,
      v_container.capacity_quantity, coalesce(v_container.unit, 'ks'), nullif(trim(coalesce(p_note, '')), '')
    );

    v_changed_count := v_changed_count + 1;
  end loop;

  return jsonb_build_object(
    'inserted', v_changed_count,
    'refilled', v_refill_count,
    'already_applied', false,
    'operation_key', p_operation_key
  );
end;
$$;

revoke all on function public.apply_technician_service_container_stock_v51(bigint, uuid, bigint, uuid, jsonb, text) from public, anon;
grant execute on function public.apply_technician_service_container_stock_v51(bigint, uuid, bigint, uuid, jsonb, text) to authenticated;

commit;
