begin;

-- Denní plán pouze odkazuje na existující servisní požadavky a technické karty.
-- Obsah zakázky se nekopíruje, takže PC i mobil stále pracují nad jedním zdrojem pravdy.
create table if not exists public.technician_day_plan_items (
  id bigint generated by default as identity primary key,
  plan_date date not null,
  employee_id uuid not null references public.employees(id) on delete cascade,
  source_type text not null check (source_type in ('service_request', 'technical_job')),
  source_id bigint not null,
  sort_order integer not null default 0,
  fixed_time timestamptz,
  dispatcher_note text,
  created_by uuid references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_date, employee_id, source_type, source_id)
);

create index if not exists technician_day_plan_employee_date_idx
  on public.technician_day_plan_items(employee_id, plan_date, sort_order);

create or replace function public.set_technician_day_plan_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_technician_day_plan_updated_at on public.technician_day_plan_items;
create trigger trg_technician_day_plan_updated_at
before update on public.technician_day_plan_items
for each row execute function public.set_technician_day_plan_updated_at();

alter table public.technician_day_plan_items enable row level security;

drop policy if exists "Allow read technician day plan" on public.technician_day_plan_items;
create policy "Allow read technician day plan"
on public.technician_day_plan_items for select to authenticated using (
  employee_id in (
    select e.id from public.employees e
    where e.auth_user_id = auth.uid() and coalesce(e.active, true)
  )
  or exists (
    select 1 from public.employees e
    where e.auth_user_id = auth.uid()
      and coalesce(e.active, true)
      and lower(coalesce(e.role, '')) in ('admin', 'manager', 'vedoucí', 'vedouci')
  )
);

drop policy if exists "Allow write technician day plan" on public.technician_day_plan_items;
create policy "Allow write technician day plan"
on public.technician_day_plan_items for all to authenticated
using (
  exists (
    select 1 from public.employees e
    where e.auth_user_id = auth.uid()
      and coalesce(e.active, true)
      and lower(coalesce(e.role, '')) in ('admin', 'manager', 'vedoucí', 'vedouci')
  )
)
with check (
  exists (
    select 1 from public.employees e
    where e.auth_user_id = auth.uid()
      and coalesce(e.active, true)
      and lower(coalesce(e.role, '')) in ('admin', 'manager', 'vedoucí', 'vedouci')
  )
);

-- Pole pro skutečný průběh převozu. Stávající technické karty zůstávají beze změny.
alter table public.technical_jobs
  add column if not exists picked_up_at timestamptz,
  add column if not exists delivered_at timestamptz,
  add column if not exists transport_receiver_name text,
  add column if not exists transport_completion_note text;

-- Materiál použitý přímo na servisním požadavku. Technické karty už mají
-- technical_job_material_items, proto je zde pouze chybějící protějšek.
create table if not exists public.service_request_material_items (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  source_stock_location_id bigint not null references public.stock_locations(id) on delete restrict,
  batch_id bigint references public.inventory_batches(id) on delete set null,
  used_quantity numeric(12,3) not null check (used_quantity > 0),
  unit text not null default 'ks',
  stock_reference_id text not null unique,
  used_by uuid references public.employees(id) on delete set null,
  used_at timestamptz not null default now(),
  note text
);

create index if not exists service_request_material_request_idx
  on public.service_request_material_items(service_request_id, used_at);

alter table public.service_request_material_items enable row level security;

drop policy if exists "Allow read service request materials" on public.service_request_material_items;
create policy "Allow read service request materials"
on public.service_request_material_items for select to authenticated using (
  exists (
    select 1
    from public.service_requests r
    join public.employees e on e.auth_user_id = auth.uid() and coalesce(e.active, true)
    where r.id = service_request_id
      and (
        r.assigned_employee_id = e.id
        or lower(coalesce(e.role, '')) in ('admin', 'manager', 'vedoucí', 'vedouci')
      )
  )
);

drop policy if exists "Allow insert service request materials" on public.service_request_material_items;
-- Přímý zápis z klienta není povolen. Zápis provádí pouze níže uvedená
-- security-definer funkce po kontrole přihlášeného technika a jeho zakázky.

-- Jediný atomický vstup pro použití dílu technikem. Ověří přiřazení zakázky,
-- odečte konkrétní šarži ze zvoleného auta/dílny a zapíše vazbu na zakázku.
create or replace function public.consume_technician_part_v45(
  p_source_type text,
  p_source_id bigint,
  p_stock_location_id bigint,
  p_product_id bigint,
  p_batch_id bigint,
  p_quantity numeric,
  p_employee_id uuid,
  p_operation_key text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_employee_id uuid;
  v_role text;
  v_allowed boolean := false;
  v_unit text := 'ks';
  v_reference_type text;
  v_result jsonb;
begin
  if p_source_type not in ('service_request', 'technical_job') then
    raise exception 'Neplatný typ zakázky.';
  end if;
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Množství dílu musí být větší než nula.';
  end if;
  if nullif(trim(coalesce(p_operation_key, '')), '') is null then
    raise exception 'Chybí identifikátor skladového pohybu.';
  end if;

  select e.id, lower(coalesce(e.role, ''))
  into v_auth_employee_id, v_role
  from public.employees e
  where e.auth_user_id = auth.uid()
    and coalesce(e.active, true)
  limit 1;

  if v_auth_employee_id is null then
    raise exception 'Přihlášený uživatel nemá aktivní profil zaměstnance.';
  end if;
  if v_auth_employee_id <> p_employee_id and v_role not in ('admin', 'manager', 'vedoucí', 'vedouci') then
    raise exception 'Díl lze odepsat jen za přihlášeného technika.';
  end if;

  if p_source_type = 'service_request' then
    select exists(
      select 1 from public.service_requests r
      where r.id = p_source_id
        and (r.assigned_employee_id = p_employee_id or v_role in ('admin', 'manager', 'vedoucí', 'vedouci'))
    ) into v_allowed;
    v_reference_type := 'service_request_material';
  else
    select exists(
      select 1 from public.technical_jobs j
      where j.id = p_source_id
        and (j.assigned_employee_id = p_employee_id or v_role in ('admin', 'manager', 'vedoucí', 'vedouci'))
    ) into v_allowed;
    v_reference_type := 'technical_job_material';
  end if;

  if not v_allowed then
    raise exception 'Zakázka není přiřazená tomuto technikovi.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('technician-part:' || p_operation_key, 0));
  if exists(
    select 1 from public.stock_movements_v13
    where reference_type = v_reference_type and reference_id = p_operation_key
  ) then
    return jsonb_build_object('inserted', 0, 'already_applied', true, 'reference_id', p_operation_key);
  end if;

  select coalesce(base_unit, 'ks') into v_unit from public.products where id = p_product_id;

  select public.apply_stock_movements_v13(jsonb_build_array(jsonb_build_object(
    'product_id', p_product_id,
    'batch_id', p_batch_id,
    'from_stock_location_id', p_stock_location_id,
    'to_stock_location_id', null,
    'movement_type', 'consumption',
    'quantity_base_units', p_quantity,
    'reference_type', v_reference_type,
    'reference_id', p_operation_key,
    'note', concat_ws(' · ', case when p_source_type = 'service_request' then 'Servis' else 'Technická karta' end || ' #' || p_source_id, nullif(trim(coalesce(p_note, '')), ''))
  ))) into v_result;

  if p_source_type = 'service_request' then
    insert into public.service_request_material_items(
      service_request_id, product_id, source_stock_location_id, batch_id,
      used_quantity, unit, stock_reference_id, used_by, note
    ) values (
      p_source_id, p_product_id, p_stock_location_id, p_batch_id,
      p_quantity, v_unit, p_operation_key, p_employee_id, p_note
    );
  else
    insert into public.technical_job_material_items(
      technical_job_id, product_id, source_stock_location_id,
      requested_quantity, prepared_quantity, used_quantity, returned_quantity,
      unit, note
    ) values (
      p_source_id, p_product_id, p_stock_location_id,
      0, 0, p_quantity, 0,
      v_unit, p_note
    )
    on conflict (technical_job_id, product_id, source_stock_location_id)
    do update set
      used_quantity = public.technical_job_material_items.used_quantity + excluded.used_quantity,
      note = concat_ws(E'\n', public.technical_job_material_items.note, excluded.note),
      updated_at = now();
  end if;

  return coalesce(v_result, '{}'::jsonb) || jsonb_build_object('reference_id', p_operation_key, 'already_applied', false);
end;
$$;

revoke all on function public.consume_technician_part_v45(text,bigint,bigint,bigint,bigint,numeric,uuid,text,text) from public;
grant execute on function public.consume_technician_part_v45(text,bigint,bigint,bigint,bigint,numeric,uuid,text,text) to authenticated;

commit;
