create table if not exists public.telemetry_planogram_counters (
  id bigint generated by default as identity primary key,
  provider text not null,
  machine_id bigint not null references public.machines (id) on delete cascade,
  planogram_slot_id bigint not null references public.machine_planogram_slots (id) on delete cascade,
  selection_code text not null,
  last_total_count integer not null default 0,
  last_event_at timestamp with time zone,
  last_ingest_id bigint references public.telemetry_dex_ingests (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (provider, machine_id, planogram_slot_id, selection_code)
);

create index if not exists telemetry_planogram_counters_machine_idx
  on public.telemetry_planogram_counters (provider, machine_id);

create or replace function public.set_telemetry_planogram_counters_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_telemetry_planogram_counters_updated_at on public.telemetry_planogram_counters;
create trigger trg_telemetry_planogram_counters_updated_at
before update on public.telemetry_planogram_counters
for each row
execute function public.set_telemetry_planogram_counters_updated_at();

alter table public.telemetry_planogram_counters enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_planogram_counters'
      and policyname = 'Allow read telemetry planogram counters'
  ) then
    create policy "Allow read telemetry planogram counters"
    on public.telemetry_planogram_counters
    for select
    to authenticated, anon
    using (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_planogram_counters'
      and policyname = 'Allow insert telemetry planogram counters'
  ) then
    create policy "Allow insert telemetry planogram counters"
    on public.telemetry_planogram_counters
    for insert
    to authenticated, anon
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_planogram_counters'
      and policyname = 'Allow update telemetry planogram counters'
  ) then
    create policy "Allow update telemetry planogram counters"
    on public.telemetry_planogram_counters
    for update
    to authenticated, anon
    using (true)
    with check (true);
  end if;
end;
$$;
