create table if not exists public.machine_external_links (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  provider text not null,
  external_machine_id text not null,
  external_location_id text,
  telemetry_enabled boolean not null default true,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (provider, external_machine_id)
);

create index if not exists machine_external_links_machine_idx
  on public.machine_external_links (machine_id);

create table if not exists public.telemetry_raw_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_machine_id text not null,
  event_type text not null,
  event_at timestamp with time zone not null,
  payload jsonb not null,
  processed boolean not null default false,
  created_at timestamp with time zone not null default now()
);

create index if not exists telemetry_raw_events_machine_idx
  on public.telemetry_raw_events (provider, external_machine_id);

create index if not exists telemetry_raw_events_processed_idx
  on public.telemetry_raw_events (processed, event_at desc);

create table if not exists public.machine_telemetry_state (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines (id) on delete cascade,
  provider text not null,
  last_seen_at timestamp with time zone,
  connectivity_status text
    check (connectivity_status in ('online', 'offline', 'unknown')),
  stock_payload jsonb,
  counters_payload jsonb,
  alerts_payload jsonb,
  updated_at timestamp with time zone not null default now(),
  unique (machine_id, provider)
);

create or replace function public.set_machine_external_links_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_machine_external_links_updated_at on public.machine_external_links;
create trigger trg_machine_external_links_updated_at
before update on public.machine_external_links
for each row
execute function public.set_machine_external_links_updated_at();

alter table public.machine_external_links enable row level security;
alter table public.telemetry_raw_events enable row level security;
alter table public.machine_telemetry_state enable row level security;

create policy "Allow read machine external links"
on public.machine_external_links
for select
to authenticated, anon
using (true);

create policy "Allow insert machine external links"
on public.machine_external_links
for insert
to authenticated, anon
with check (true);

create policy "Allow update machine external links"
on public.machine_external_links
for update
to authenticated, anon
using (true)
with check (true);

create policy "Allow read telemetry raw events"
on public.telemetry_raw_events
for select
to authenticated, anon
using (true);

create policy "Allow insert telemetry raw events"
on public.telemetry_raw_events
for insert
to authenticated, anon
with check (true);

create policy "Allow read machine telemetry state"
on public.machine_telemetry_state
for select
to authenticated, anon
using (true);

create policy "Allow insert machine telemetry state"
on public.machine_telemetry_state
for insert
to authenticated, anon
with check (true);

create policy "Allow update machine telemetry state"
on public.machine_telemetry_state
for update
to authenticated, anon
using (true)
with check (true);
