create table if not exists public.telemetry_dex_ingests (
  id bigint generated by default as identity primary key,
  provider text not null default 'GP',
  device_id text not null,
  customer_id text,
  transaction_id text,
  transaction_time timestamp with time zone,
  transmit_time timestamp with time zone,
  dex_read_datetime timestamp with time zone,
  dex_reason text,
  raw_xml text not null,
  raw_dex text not null,
  status text not null default 'received'
    check (status in ('received', 'parsed', 'failed')),
  parse_error text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (provider, transaction_id, device_id)
);

create index if not exists telemetry_dex_ingests_device_idx
  on public.telemetry_dex_ingests (provider, device_id, created_at desc);

create index if not exists telemetry_dex_ingests_status_idx
  on public.telemetry_dex_ingests (status, created_at desc);

create or replace function public.set_telemetry_dex_ingests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_telemetry_dex_ingests_updated_at on public.telemetry_dex_ingests;
create trigger trg_telemetry_dex_ingests_updated_at
before update on public.telemetry_dex_ingests
for each row
execute function public.set_telemetry_dex_ingests_updated_at();

alter table public.telemetry_dex_ingests enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_dex_ingests'
      and policyname = 'Allow read telemetry dex ingests'
  ) then
    create policy "Allow read telemetry dex ingests"
    on public.telemetry_dex_ingests
    for select
    to authenticated, anon
    using (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_dex_ingests'
      and policyname = 'Allow insert telemetry dex ingests'
  ) then
    create policy "Allow insert telemetry dex ingests"
    on public.telemetry_dex_ingests
    for insert
    to authenticated, anon
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_dex_ingests'
      and policyname = 'Allow update telemetry dex ingests'
  ) then
    create policy "Allow update telemetry dex ingests"
    on public.telemetry_dex_ingests
    for update
    to authenticated, anon
    using (true)
    with check (true);
  end if;
end;
$$;
