create table if not exists public.telemetry_sales_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  ingest_id bigint references public.telemetry_dex_ingests (id) on delete set null,
  machine_id bigint not null references public.machines (id) on delete cascade,
  planogram_slot_id bigint references public.machine_planogram_slots (id) on delete set null,
  selection_code text not null,
  product_name text,
  product_sku text,
  quantity numeric(12,3) not null default 0,
  cash_quantity numeric(12,3) not null default 0,
  cashless_quantity numeric(12,3) not null default 0,
  unknown_payment_quantity numeric(12,3) not null default 0,
  unit_price_czk numeric(10,2),
  total_amount_czk numeric(12,2),
  cash_amount_czk numeric(12,2),
  cashless_amount_czk numeric(12,2),
  unknown_payment_amount_czk numeric(12,2),
  source_event_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  unique (provider, ingest_id, machine_id, planogram_slot_id, selection_code)
);

alter table public.telemetry_sales_events
  add column if not exists cash_quantity numeric(12,3) not null default 0,
  add column if not exists cashless_quantity numeric(12,3) not null default 0,
  add column if not exists unknown_payment_quantity numeric(12,3) not null default 0,
  add column if not exists cash_amount_czk numeric(12,2),
  add column if not exists cashless_amount_czk numeric(12,2),
  add column if not exists unknown_payment_amount_czk numeric(12,2);

create index if not exists telemetry_sales_events_source_idx
  on public.telemetry_sales_events (source_event_at desc);

create index if not exists telemetry_sales_events_machine_idx
  on public.telemetry_sales_events (machine_id, source_event_at desc);

create index if not exists telemetry_sales_events_product_idx
  on public.telemetry_sales_events (product_sku, source_event_at desc);

alter table public.telemetry_sales_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_sales_events'
      and policyname = 'Allow read telemetry sales events'
  ) then
    create policy "Allow read telemetry sales events"
    on public.telemetry_sales_events
    for select
    to authenticated, anon
    using (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_sales_events'
      and policyname = 'Allow insert telemetry sales events'
  ) then
    create policy "Allow insert telemetry sales events"
    on public.telemetry_sales_events
    for insert
    to authenticated, anon
    with check (true);
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'telemetry_sales_events'
      and policyname = 'Allow update telemetry sales events'
  ) then
    create policy "Allow update telemetry sales events"
    on public.telemetry_sales_events
    for update
    to authenticated, anon
    using (true)
    with check (true);
  end if;
end;
$$;
