create table if not exists public.telemetry_coffee_recipe_depletions (
  id bigint generated by default as identity primary key,
  sale_event_id bigint not null references public.telemetry_sales_events(id) on delete cascade,
  recipe_item_id bigint not null references public.machine_coffee_recipe_items(id) on delete restrict,
  coffee_container_id bigint not null references public.machine_coffee_containers(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  unit text not null,
  created_at timestamptz not null default now(),
  unique (sale_event_id, recipe_item_id)
);

alter table public.telemetry_coffee_recipe_depletions enable row level security;

create or replace function public.apply_telemetry_coffee_depletion(p_sale_event_ids bigint[])
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer := 0;
  v_containers integer := 0;
begin
  with candidates as (
    select s.id sale_event_id, ri.id recipe_item_id, c.id coffee_container_id, c.unit,
      round((case
        when lower(ri.unit)=lower(c.unit) then ri.quantity_per_vend*s.quantity
        when lower(ri.unit)='kg' and lower(c.unit)='g' then ri.quantity_per_vend*s.quantity*1000
        when lower(ri.unit)='g' and lower(c.unit)='kg' then ri.quantity_per_vend*s.quantity/1000
        when lower(ri.unit)='l' and lower(c.unit)='ml' then ri.quantity_per_vend*s.quantity*1000
        when lower(ri.unit)='ml' and lower(c.unit)='l' then ri.quantity_per_vend*s.quantity/1000
        else ri.quantity_per_vend*s.quantity end)::numeric, 3) quantity
    from public.telemetry_sales_events s
    join public.machine_coffee_buttons b
      on b.machine_id=s.machine_id and b.active and b.selection_code=s.selection_code
    join public.machine_coffee_recipe_items ri
      on ri.machine_id=s.machine_id and ri.coffee_button_id=b.id and ri.active
    join public.machine_coffee_containers c
      on c.id=ri.coffee_container_id and c.machine_id=s.machine_id and c.active
    where s.id=any(p_sale_event_ids) and s.quantity>0 and ri.quantity_per_vend>0
  ), inserted as (
    insert into public.telemetry_coffee_recipe_depletions
      (sale_event_id,recipe_item_id,coffee_container_id,quantity,unit)
    select sale_event_id,recipe_item_id,coffee_container_id,quantity,unit
    from candidates where quantity>0
    on conflict (sale_event_id,recipe_item_id) do nothing
    returning coffee_container_id,quantity
  ), usage as (
    select coffee_container_id,sum(quantity) quantity from inserted group by coffee_container_id
  ), updated as (
    update public.machine_coffee_containers c
    set current_quantity=greatest(0,c.current_quantity-u.quantity),updated_at=now()
    from usage u where c.id=u.coffee_container_id
    returning c.id
  )
  select (select count(*) from inserted),(select count(*) from updated)
  into v_inserted,v_containers;
  return jsonb_build_object('inserted',v_inserted,'containers_updated',v_containers);
end $$;

revoke all on function public.apply_telemetry_coffee_depletion(bigint[]) from public;
grant execute on function public.apply_telemetry_coffee_depletion(bigint[]) to service_role;

create table if not exists public.telemetry_stock_depletions (
  id bigint generated by default as identity primary key,
  sale_event_id bigint not null references public.telemetry_sales_events(id) on delete cascade,
  stock_location_id bigint not null references public.stock_locations(id) on delete restrict,
  product_id bigint not null references public.products(id) on delete restrict,
  batch_id bigint references public.inventory_batches(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  created_at timestamptz not null default now()
);
create unique index if not exists telemetry_stock_depletions_event_batch_uidx
  on public.telemetry_stock_depletions(sale_event_id,product_id,batch_id) nulls not distinct;
alter table public.telemetry_stock_depletions enable row level security;

create or replace function public.apply_telemetry_stock_depletion(p_sale_event_ids bigint[])
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_rows integer:=0; v_events integer:=0;
begin
  with candidates as (
    select s.id sale_event_id,sl.id stock_location_id,p.id product_id,b.batch_id,
      least(b.quantity_on_hand,greatest(0,s.quantity-
        coalesce(sum(b.quantity_on_hand) over(partition by s.id order by
          coalesce(ib.use_by_date,ib.best_before_date,'9999-12-31'::date),b.id
          rows between unbounded preceding and 1 preceding),0)))::numeric(14,3) quantity
    from public.telemetry_sales_events s
    join public.products p on p.sku=s.product_sku
    join public.stock_locations sl on sl.location_type='machine' and sl.machine_id=s.machine_id
    join public.stock_location_balances b on b.stock_location_id=sl.id and b.product_id=p.id and b.quantity_on_hand>0
    left join public.inventory_batches ib on ib.id=b.batch_id
    where s.id=any(p_sale_event_ids) and s.quantity>0
  ), inserted as (
    insert into public.telemetry_stock_depletions(sale_event_id,stock_location_id,product_id,batch_id,quantity)
    select sale_event_id,stock_location_id,product_id,batch_id,quantity from candidates where quantity>0
    on conflict do nothing returning *
  ), updated as (
    update public.stock_location_balances b set quantity_on_hand=b.quantity_on_hand-x.quantity,updated_at=now()
    from (select stock_location_id,product_id,batch_id,sum(quantity) quantity from inserted group by 1,2,3) x
    where b.stock_location_id=x.stock_location_id and b.product_id=x.product_id and b.batch_id is not distinct from x.batch_id
    returning b.id
  ), movements as (
    insert into public.stock_movements_v13(product_id,batch_id,from_stock_location_id,to_stock_location_id,movement_type,
      quantity_base_units,reference_type,reference_id,note)
    select product_id,batch_id,stock_location_id,null,'sale',quantity,'telemetry_sale','telemetry-sale:'||sale_event_id,
      'Automatický odečet telemetrického prodeje #'||sale_event_id
    from inserted returning id
  )
  select (select count(*) from inserted),(select count(distinct sale_event_id) from inserted) into v_rows,v_events;
  return jsonb_build_object('inserted',v_rows,'sale_events',v_events);
end $$;
revoke all on function public.apply_telemetry_stock_depletion(bigint[]) from public;
grant execute on function public.apply_telemetry_stock_depletion(bigint[]) to service_role;
