alter table public.vehicles
  add column if not exists fuel_type text
  check (fuel_type in ('petrol', 'diesel', 'lpg', 'electric', 'hybrid'));

alter table public.vehicles
  add column if not exists tank_capacity_l numeric(6,2);

alter table public.vehicles
  add column if not exists assigned_employee_id uuid references public.employees (id) on delete set null;

alter table public.vehicles
  add column if not exists stk_valid_until date;

alter table public.vehicles
  add column if not exists insurance_valid_until date;

alter table public.vehicles
  add column if not exists next_service_date date;

alter table public.vehicles
  add column if not exists next_service_odometer_km integer;

create index if not exists vehicles_assigned_employee_idx
  on public.vehicles (assigned_employee_id);

create table if not exists public.vehicle_operation_logs (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles (id) on delete cascade,
  employee_id uuid references public.employees (id) on delete set null,
  attendance_day_id bigint references public.attendance_days (id) on delete set null,
  log_date date not null default current_date,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  start_odometer_km integer,
  end_odometer_km integer,
  distance_km integer generated always as (
    case
      when start_odometer_km is not null and end_odometer_km is not null and end_odometer_km >= start_odometer_km
        then end_odometer_km - start_odometer_km
      else null
    end
  ) stored,
  fuel_liters numeric(8,2),
  fuel_cost numeric(10,2),
  fuel_note text,
  trip_note text,
  status text not null default 'draft'
    check (status in ('draft', 'open', 'closed', 'review')),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists vehicle_operation_logs_vehicle_date_idx
  on public.vehicle_operation_logs (vehicle_id, log_date desc);

create index if not exists vehicle_operation_logs_employee_date_idx
  on public.vehicle_operation_logs (employee_id, log_date desc);

create or replace function public.set_vehicle_operation_logs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_vehicle_operation_logs_updated_at on public.vehicle_operation_logs;

create trigger trg_vehicle_operation_logs_updated_at
before update on public.vehicle_operation_logs
for each row
execute function public.set_vehicle_operation_logs_updated_at();

alter table public.vehicle_operation_logs enable row level security;

create policy "Allow read vehicle operation logs"
on public.vehicle_operation_logs
for select
to authenticated, anon
using (true);

create policy "Allow insert vehicle operation logs"
on public.vehicle_operation_logs
for insert
to authenticated, anon
with check (true);

create policy "Allow update vehicle operation logs"
on public.vehicle_operation_logs
for update
to authenticated, anon
using (true)
with check (true);

