create table if not exists public.vehicle_auto_load_profiles (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  active boolean not null default true,
  min_trip_usage_ratio numeric(5,3) not null default 0.667
    check (min_trip_usage_ratio >= 0 and min_trip_usage_ratio <= 1),
  stale_vehicle_days integer not null default 1
    check (stale_vehicle_days >= 0),
  safety_stock_quantity numeric(12,3) not null default 0,
  history_days integer not null default 45
    check (history_days > 0),
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (product_id)
);

create index if not exists vehicle_auto_load_profiles_product_idx
  on public.vehicle_auto_load_profiles (product_id);

drop trigger if exists trg_vehicle_auto_load_profiles_updated_at on public.vehicle_auto_load_profiles;
create trigger trg_vehicle_auto_load_profiles_updated_at
before update on public.vehicle_auto_load_profiles
for each row
execute function public.set_updated_at_column();

alter table public.vehicle_auto_load_profiles enable row level security;

drop policy if exists "Allow read vehicle auto load profiles" on public.vehicle_auto_load_profiles;
create policy "Allow read vehicle auto load profiles"
on public.vehicle_auto_load_profiles
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert vehicle auto load profiles" on public.vehicle_auto_load_profiles;
create policy "Allow insert vehicle auto load profiles"
on public.vehicle_auto_load_profiles
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update vehicle auto load profiles" on public.vehicle_auto_load_profiles;
create policy "Allow update vehicle auto load profiles"
on public.vehicle_auto_load_profiles
for update
to authenticated, anon
using (true)
with check (true);

insert into public.vehicle_auto_load_profiles (
  product_id,
  active,
  min_trip_usage_ratio,
  stale_vehicle_days,
  safety_stock_quantity,
  history_days,
  note
)
select
  p.id,
  true,
  0.667,
  case when lower(coalesce(p.name, '')) like '%baget%' then 1 else 2 end,
  0,
  45,
  'Výchozí profil pro automatickou nakládku vozidel.'
from public.products p
where p.active is distinct from false
  and p.product_category = 'food_ready'
on conflict (product_id) do nothing;
