create table if not exists public.vehicle_auto_load_deferred_needs (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  quantity_base_units numeric(12,3) not null default 0
    check (quantity_base_units >= 0),
  unit text not null default 'ks',
  status text not null default 'open'
    check (status in ('open', 'closed', 'cancelled')),
  first_deferred_for_date date,
  last_deferred_for_date date,
  last_reason text,
  last_scope text,
  last_min_trip_usage_ratio numeric(5,3),
  last_usage_ratio numeric(5,3),
  closed_at timestamp with time zone,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists vehicle_auto_load_deferred_open_idx
  on public.vehicle_auto_load_deferred_needs (vehicle_id, product_id)
  where status = 'open';

create unique index if not exists vehicle_auto_load_deferred_one_open_idx
  on public.vehicle_auto_load_deferred_needs (vehicle_id, product_id)
  where status = 'open';

drop trigger if exists trg_vehicle_auto_load_deferred_needs_updated_at on public.vehicle_auto_load_deferred_needs;
create trigger trg_vehicle_auto_load_deferred_needs_updated_at
before update on public.vehicle_auto_load_deferred_needs
for each row
execute function public.set_updated_at_column();

alter table public.vehicle_auto_load_deferred_needs enable row level security;

drop policy if exists "Allow read vehicle auto load deferred needs" on public.vehicle_auto_load_deferred_needs;
create policy "Allow read vehicle auto load deferred needs"
on public.vehicle_auto_load_deferred_needs
for select
to authenticated, anon
using (true);

drop policy if exists "Allow insert vehicle auto load deferred needs" on public.vehicle_auto_load_deferred_needs;
create policy "Allow insert vehicle auto load deferred needs"
on public.vehicle_auto_load_deferred_needs
for insert
to authenticated, anon
with check (true);

drop policy if exists "Allow update vehicle auto load deferred needs" on public.vehicle_auto_load_deferred_needs;
create policy "Allow update vehicle auto load deferred needs"
on public.vehicle_auto_load_deferred_needs
for update
to authenticated, anon
using (true)
with check (true);
