create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  name text not null,
  plate text not null,
  brand text,
  model text,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  current_odometer_km integer,
  note text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.vehicles
  add column if not exists current_odometer_km integer;

create unique index if not exists vehicles_plate_unique
  on public.vehicles (plate);

create index if not exists vehicles_warehouse_idx
  on public.vehicles (warehouse_id);

create or replace function public.set_vehicles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_vehicles_updated_at on public.vehicles;

create trigger trg_vehicles_updated_at
before update on public.vehicles
for each row
execute function public.set_vehicles_updated_at();

alter table public.vehicles enable row level security;

create policy "Allow read vehicles"
on public.vehicles
for select
to authenticated, anon
using (true);

create policy "Allow insert vehicles"
on public.vehicles
for insert
to authenticated, anon
with check (true);

create policy "Allow update vehicles"
on public.vehicles
for update
to authenticated, anon
using (true)
with check (true);
