create table if not exists public.vendsoft_food_sync_state (
  singleton boolean primary key default true check (singleton),
  started_at timestamp with time zone not null default now(),
  last_attempt_at timestamp with time zone,
  last_success_at timestamp with time zone,
  last_seen_event_at timestamp with time zone,
  last_imported_count integer not null default 0,
  last_skipped_count integer not null default 0,
  last_unmatched_count integer not null default 0,
  last_error text,
  updated_at timestamp with time zone not null default now()
);

insert into public.vendsoft_food_sync_state (singleton)
values (true)
on conflict (singleton) do nothing;

create table if not exists public.vendsoft_food_sales_imports (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  machine_id bigint references public.machines (id) on delete set null,
  planogram_slot_id bigint references public.machine_planogram_slots (id) on delete set null,
  vendsoft_machine_code text not null,
  selection_code text not null,
  location_name text,
  machine_name text,
  product_name text,
  quantity numeric(12,3) not null,
  unit_price_czk numeric(10,2),
  total_amount_czk numeric(12,2),
  credit_card_amount_czk numeric(12,2),
  source_event_at timestamp with time zone not null,
  status text not null check (status in ('applied', 'unmatched_machine', 'unmatched_slot', 'ignored_non_food')),
  note text,
  created_at timestamp with time zone not null default now()
);

create index if not exists vendsoft_food_sales_imports_event_idx
  on public.vendsoft_food_sales_imports (source_event_at desc);

create index if not exists vendsoft_food_sales_imports_machine_idx
  on public.vendsoft_food_sales_imports (machine_id, source_event_at desc);

alter table public.vendsoft_food_sync_state enable row level security;
alter table public.vendsoft_food_sales_imports enable row level security;

drop policy if exists "Allow read VendSoft food sync state" on public.vendsoft_food_sync_state;
create policy "Allow read VendSoft food sync state"
on public.vendsoft_food_sync_state
for select
to authenticated
using (true);

drop policy if exists "Allow read VendSoft food sales imports" on public.vendsoft_food_sales_imports;
create policy "Allow read VendSoft food sales imports"
on public.vendsoft_food_sales_imports
for select
to authenticated
using (true);

create or replace function public.apply_vendsoft_food_sale(
  p_event_key text,
  p_vendsoft_machine_code text,
  p_selection_code text,
  p_location_name text,
  p_machine_name text,
  p_product_name text,
  p_quantity numeric,
  p_unit_price_czk numeric,
  p_total_amount_czk numeric,
  p_credit_card_amount_czk numeric,
  p_source_event_at timestamp with time zone
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_machine public.machines%rowtype;
  v_slot public.machine_planogram_slots%rowtype;
  v_import_id bigint;
  v_quantity numeric := greatest(coalesce(p_quantity, 0), 0);
  v_cashless_quantity numeric := 0;
  v_cash_quantity numeric := 0;
  v_unknown_quantity numeric := 0;
  v_cashless_amount numeric := greatest(coalesce(p_credit_card_amount_czk, 0), 0);
  v_cash_amount numeric := 0;
  v_unknown_amount numeric := 0;
  v_next_units numeric;
  v_next_fill numeric;
begin
  if nullif(trim(coalesce(p_event_key, '')), '') is null then
    raise exception 'Event key is required.';
  end if;

  if v_quantity <= 0 then
    return jsonb_build_object('status', 'ignored', 'reason', 'non_positive_quantity');
  end if;

  select m.*
  into v_machine
  from public.machines m
  where m.qr_token = 'vendsoft-' || trim(p_vendsoft_machine_code)
  limit 1;

  if not found then
    insert into public.vendsoft_food_sales_imports (
      event_key, vendsoft_machine_code, selection_code, location_name, machine_name,
      product_name, quantity, unit_price_czk, total_amount_czk, credit_card_amount_czk,
      source_event_at, status, note
    )
    values (
      p_event_key, trim(p_vendsoft_machine_code), trim(p_selection_code), p_location_name, p_machine_name,
      p_product_name, v_quantity, p_unit_price_czk, p_total_amount_czk, p_credit_card_amount_czk,
      p_source_event_at, 'unmatched_machine', 'Automat s tímto VendSoft kódem nebyl nalezen.'
    )
    on conflict (event_key) do nothing
    returning id into v_import_id;

    return jsonb_build_object(
      'status', case when v_import_id is null then 'duplicate' else 'unmatched_machine' end
    );
  end if;

  if lower(coalesce(v_machine.machine_type, '')) <> 'snack' then
    insert into public.vendsoft_food_sales_imports (
      event_key, machine_id, vendsoft_machine_code, selection_code, location_name, machine_name,
      product_name, quantity, unit_price_czk, total_amount_czk, credit_card_amount_czk,
      source_event_at, status, note
    )
    values (
      p_event_key, v_machine.id, trim(p_vendsoft_machine_code), trim(p_selection_code), p_location_name, p_machine_name,
      p_product_name, v_quantity, p_unit_price_czk, p_total_amount_czk, p_credit_card_amount_czk,
      p_source_event_at, 'ignored_non_food', 'Dočasná synchronizace z VendSoftu je povolená jen pro potravinové automaty.'
    )
    on conflict (event_key) do nothing
    returning id into v_import_id;

    return jsonb_build_object(
      'status', case when v_import_id is null then 'duplicate' else 'ignored_non_food' end,
      'machine_id', v_machine.id
    );
  end if;

  select s.*
  into v_slot
  from public.machine_planogram_slots s
  where s.machine_id = v_machine.id
    and s.active = true
    and trim(s.slot_code) = trim(p_selection_code)
  order by s.id
  limit 1;

  if not found then
    insert into public.vendsoft_food_sales_imports (
      event_key, machine_id, vendsoft_machine_code, selection_code, location_name, machine_name,
      product_name, quantity, unit_price_czk, total_amount_czk, credit_card_amount_czk,
      source_event_at, status, note
    )
    values (
      p_event_key, v_machine.id, trim(p_vendsoft_machine_code), trim(p_selection_code), p_location_name, p_machine_name,
      p_product_name, v_quantity, p_unit_price_czk, p_total_amount_czk, p_credit_card_amount_czk,
      p_source_event_at, 'unmatched_slot', 'Aktivní pozice s tímto číslem nebyla nalezena.'
    )
    on conflict (event_key) do nothing
    returning id into v_import_id;

    return jsonb_build_object(
      'status', case when v_import_id is null then 'duplicate' else 'unmatched_slot' end,
      'machine_id', v_machine.id
    );
  end if;

  insert into public.vendsoft_food_sales_imports (
    event_key, machine_id, planogram_slot_id, vendsoft_machine_code, selection_code,
    location_name, machine_name, product_name, quantity, unit_price_czk,
    total_amount_czk, credit_card_amount_czk, source_event_at, status
  )
  values (
    p_event_key, v_machine.id, v_slot.id, trim(p_vendsoft_machine_code), trim(p_selection_code),
    p_location_name, p_machine_name, coalesce(nullif(trim(p_product_name), ''), v_slot.product_name),
    v_quantity, p_unit_price_czk, p_total_amount_czk, p_credit_card_amount_czk,
    p_source_event_at, 'applied'
  )
  on conflict (event_key) do nothing
  returning id into v_import_id;

  if v_import_id is null then
    return jsonb_build_object('status', 'duplicate', 'machine_id', v_machine.id, 'slot_id', v_slot.id);
  end if;

  -- The temporary VendSoft report does not reliably identify payment method.
  -- Keep the sale value, but classify every imported quantity and amount as unknown.
  v_cashless_quantity := 0;
  v_cash_quantity := 0;
  v_unknown_quantity := v_quantity;
  v_cashless_amount := 0;
  v_cash_amount := 0;
  v_unknown_amount := greatest(coalesce(p_total_amount_czk, p_unit_price_czk * v_quantity, 0), 0);

  v_next_units := greatest(0, coalesce(v_slot.current_units, 0) - v_quantity);
  v_next_fill := case
    when coalesce(v_slot.capacity_units, 0) > 0
      then round((v_next_units / v_slot.capacity_units) * 100, 2)
    else null
  end;

  update public.machine_planogram_slots
  set
    current_units = v_next_units,
    fill_percent = v_next_fill,
    updated_at = now()
  where id = v_slot.id;

  insert into public.telemetry_sales_events (
    provider, ingest_id, machine_id, planogram_slot_id, selection_code,
    product_name, product_sku, quantity, cash_quantity, cashless_quantity,
    unknown_payment_quantity, unit_price_czk, total_amount_czk, cash_amount_czk,
    cashless_amount_czk, unknown_payment_amount_czk, source_event_at
  )
  values (
    'VendSoft', null, v_machine.id, v_slot.id, trim(p_selection_code),
    coalesce(nullif(trim(p_product_name), ''), v_slot.product_name), v_slot.product_sku,
    v_quantity, v_cash_quantity, v_cashless_quantity, v_unknown_quantity,
    coalesce(p_unit_price_czk, v_slot.customer_price_czk, v_slot.dex_price_czk),
    coalesce(p_total_amount_czk, p_unit_price_czk * v_quantity),
    nullif(v_cash_amount, 0), nullif(v_cashless_amount, 0), nullif(v_unknown_amount, 0),
    p_source_event_at
  );

  insert into public.machine_telemetry_state (
    machine_id, provider, last_seen_at, connectivity_status, counters_payload, updated_at
  )
  values (
    v_machine.id,
    'VendSoft',
    p_source_event_at,
    'online',
    jsonb_build_object(
      'temporary_food_sync', true,
      'vendsoft_machine_code', trim(p_vendsoft_machine_code),
      'last_selection_code', trim(p_selection_code),
      'last_event_key', p_event_key
    ),
    now()
  )
  on conflict (machine_id, provider)
  do update set
    last_seen_at = greatest(public.machine_telemetry_state.last_seen_at, excluded.last_seen_at),
    connectivity_status = 'online',
    counters_payload = excluded.counters_payload,
    updated_at = now();

  return jsonb_build_object(
    'status', 'applied',
    'machine_id', v_machine.id,
    'slot_id', v_slot.id,
    'previous_units', v_slot.current_units,
    'next_units', v_next_units
  );
end;
$$;

revoke all on function public.apply_vendsoft_food_sale(
  text, text, text, text, text, text, numeric, numeric, numeric, numeric, timestamp with time zone
) from public, anon, authenticated;

grant execute on function public.apply_vendsoft_food_sale(
  text, text, text, text, text, text, numeric, numeric, numeric, numeric, timestamp with time zone
) to service_role;
