create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  type text not null check (type in ('warehouse', 'service_base', 'mixed')),
  city text,
  address text,
  contact_person text,
  phone text,
  note text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists warehouses_code_unique
  on public.warehouses (code)
  where code is not null;

alter table public.warehouses enable row level security;

create policy "Allow read warehouses"
on public.warehouses
for select
to authenticated, anon
using (true);

create policy "Allow insert warehouses"
on public.warehouses
for insert
to authenticated, anon
with check (true);

create policy "Allow update warehouses"
on public.warehouses
for update
to authenticated, anon
using (true)
with check (true);
