import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {pragueMidnight,pragueDay,addDays,comparisonRange,validateRange,mergeComparison,matchesFilter,csvCell} from '../report-core.js';
import {makeXlsx,columnLetter} from '../report-xlsx.js';
assert.equal(pragueDay('2026-09-30T22:30:00Z'),'2026-10-01');
assert.equal(pragueMidnight('2026-09-30').toISOString(),'2026-09-29T22:00:00.000Z');
assert.equal((pragueMidnight('2026-03-30')-pragueMidnight('2026-03-29'))/3600000,23);
assert.equal((pragueMidnight('2026-10-26')-pragueMidnight('2026-10-25'))/3600000,25);
assert.equal(addDays('2026-03-01',-1),'2026-02-28');
assert.deepEqual(comparisonRange({from:'2026-09-01',to:'2026-09-30'},'previous_period'),{from:'2026-08-02',to:'2026-08-31'});
assert.deepEqual(comparisonRange({from:'2024-02-29',to:'2024-02-29'},'previous_year'),{from:'2023-02-28',to:'2023-02-28'});
assert.throws(()=>validateRange({from:'2026-02-30',to:'2026-03-03'}));
assert.throws(()=>validateRange({from:'2026-09-30',to:'2026-09-01'}));
const rows=mergeComparison([{key:'new',revenue:100,profit:null,quantity:5,revenueNet:80}],[{key:'gone',label:'Vypadlý automat',revenue:200,profit:60,quantity:8,revenueNet:160}]);
assert.equal(rows[1].revenueDelta,-200);assert.equal(rows[1].changePercent,-100);assert.equal(rows[1].label,'Vypadlý automat');assert.equal(rows[0].profitDelta,null);assert.equal(rows[0].changePercent,null);
assert(matchesFilter(125.5,'>=125,5'));assert(!matchesFilter(125,'>=125,5'));assert(matchesFilter('Čokoláda','čoko'));
assert.equal(csvCell('=HYPERLINK("x")'),'"\'=HYPERLINK(""x"")"');assert.equal(csvCell(-12.5),'"-12,5"');
assert.equal(columnLetter(26),'AA');
const blob=makeXlsx([['Produkt','Tržba'],['Čokoláda',125.5],['=1+1',null]],[['Kritérium','Hodnota'],['Řádků',2]]);
if(process.env.XLSX_TEST_OUTPUT)writeFileSync(process.env.XLSX_TEST_OUTPUT,new Uint8Array(await blob.arrayBuffer()));
console.log('Report core: dates, DST, comparisons including zero sales, filters and safe exports passed.');
// Execute the actual page aggregators, not a parallel implementation.
const {readFileSync}=await import('node:fs');
const {runInNewContext}=await import('node:vm');
const html=readFileSync(new URL('../report-telemetry.html',import.meta.url),'utf8');
const part=(name,next)=>html.slice(html.indexOf('    function '+name+'('),html.indexOf('    function '+next+'('));
const context={productCost:r=>({unitCost:5,vatRate:0,missingCost:!!r.missingCost,vatFallback:false}),selectedDayCount:()=>30,normalize:v=>String(v||''),getProductKind:()=>'',getProductTypeLabel:()=>'',DEFAULT_VAT_RATE:12,pragueMidnight,addDays,dateKey:pragueDay,getCurrentRange:()=>({from:'2026-09-01',to:'2026-09-02'})};
runInNewContext(part('aggregate','attachComparison')+part('buildDailyRows','renderCharts')+'\nthis.aggregate=aggregate;this.buildDailyRows=buildDailyRows;',context);
const sold=(overrides={})=>({quantity:2,total_amount_czk:40,cash_amount_czk:40,source_event_at:'2026-09-01T10:00:00Z',...overrides});
assert.equal(context.aggregate([sold()],()=>1)[0].profit,30);
for(const r of [sold({missingCost:true}),sold({selection_code:'TERMINAL_SUMMARY'}),sold({total_amount_czk:0}),sold({unknown_payment_quantity:1})])assert.equal(context.aggregate([r],()=>1)[0].profit,null);
const daily=context.buildDailyRows([sold({source_event_at:'2026-08-31T22:30:00Z'})]);assert.equal(daily.length,2);assert.equal(daily[0].revenue,40);assert.equal(daily[1].revenue,0);
console.log('Actual page: incomplete valuation stays unknown; Prague daily buckets retain the first day.');
