import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import vm from 'node:vm'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const html = readFileSync(new URL('../machines.html', import.meta.url), 'utf8')
const ui = readFileSync(new URL('../machines-planogram-ui.js', import.meta.url), 'utf8').replaceAll('export function', 'function')
const script = html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace(/^\s*import .*$/gm, '').replace('    initializePage()', '')
new vm.Script(ui + script)
const fixture = { id:901, machine_id:58, slot_code:'25', product_name:'Bongo máta', product_sku:'SOCO-BONGO-MATA-40', product_family:'Bongo', product_variant:'Máta', price_czk:16, customer_price_czk:16, capacity_units:13, current_units:7, fill_percent:53.85, active:true, substitution_policy:'same_family', allowed_substitutes:'SKU SOCO-BONGO-MATA-40, SKU SOCO-BONGO-ORIGINAL-40', planned_product_name:null, planned_product_sku:null, note:'Zachovat poznámku', settlement_type:'subsidy_receivable', settlement_amount_czk:2, settlement_partner:'Škola', settlement_billing_enabled:true, settlement_note:'Smlouva' }
const machine = {id:58,name:'Aria L',machine_type:'snack',evidence_number:'78'}
const harness = html.replace(/<script[\s\S]*?<\/script>/g,'').replace('</body>', `<script type="module">${ui}\nconst supabase = {};\n${script}\nwindow.pgTest={fillPlanogramForm,openPlanogramModal,closePlanogramModal,getPlanogramPayload,fillCoffeeContainerForm,getCoffeeContainerPayload,bulkPlanogramCandidates,hasPlanogramChange,getPlanogramStatus,renderPlanogramCabinet, setSlots: slots => {planogramSlots=slots}, render: (slots,machine)=>{detailModalBody.innerHTML=renderPlanogramCabinet(slots,machine);detailModalBackdrop.classList.add('show')}};</script></body>`)
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE || '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'})
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}})
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.route('**/*',route=>{
    const url=new URL(route.request().url())
    if(url.pathname==='/machines.html')return route.fulfill({contentType:'text/html',body:harness})
    if(url.pathname==='/machines-planogram.css')return route.fulfill({contentType:'text/css',body:readFileSync(new URL('../machines-planogram.css',import.meta.url),'utf8')})
    return route.fulfill({status:404,body:''})
  })
  await page.goto('http://planogram.test/machines.html')
  await page.waitForFunction(()=>window.pgTest)
  const slots=[fixture,{...fixture,id:902,slot_code:'69',product_name:'Margot',planned_product_name:'RawBar',planned_product_sku:'SOCO-RAWBAR-APPLE',pending_change_mode:'full_swap',planned_price_czk:19,changeover_new_units:2,changeover_old_units:5}]
  await page.evaluate(({slots,machine})=>{pgTest.setSlots(slots);pgTest.render(slots,machine)}, {slots,machine})
  assert.equal(await page.locator('[data-slot-id="901"]').count(),1)
  assert.equal(await page.locator('[data-planogram-layout] [data-slot-id="902"]').count(),1)
  assert.match(await page.locator('[data-planogram-layout]').innerText(),/Aktuálně také: RawBar · 2 ks/)
  await page.locator('[data-planogram-view="changes"]').click()
  assert.equal(await page.locator('[data-planogram-layout]').isVisible(),false)
  await page.locator('[data-planogram-changes] [data-card-tab="plan"]').click()
  assert.equal(await page.locator('#planogram-panel-plan').isVisible(),true)
  await page.evaluate(()=>pgTest.closePlanogramModal())
  await page.evaluate(slot=>{pgTest.fillPlanogramForm(slot);pgTest.openPlanogramModal()},fixture)
  const before=await page.evaluate(()=>pgTest.getPlanogramPayload())
  for(const tab of ['replacements','plan','position'])await page.locator(`#planogramForm [data-card-tab="${tab}"]`).click()
  assert.deepEqual(await page.evaluate(()=>pgTest.getPlanogramPayload()),before,'tab navigation must preserve all saved values')
  assert.equal(before.allowed_substitutes,fixture.allowed_substitutes)
  assert.equal(before.settlement_amount_czk,2)
  assert.equal(before.current_units,7)
  assert.equal(await page.locator('#planogramForm [id]').evaluateAll(nodes=>new Set(nodes.map(n=>n.id)).size===nodes.length),true)
  await page.locator('#slotPrice').fill('17')
  const after=await page.evaluate(()=>pgTest.getPlanogramPayload())
  assert.deepEqual({...after,price_czk:before.price_czk},before,'price edit must preserve replacement lists, stock and finances')
  // Invalid required input in a hidden tab must be opened for native validation.
  await page.locator('#slotProductName').fill('')
  await page.locator('#planogramForm [data-card-tab="plan"]').click()
  await page.evaluate(()=>document.getElementById('planogramForm').reportValidity())
  assert.equal(await page.locator('#planogram-panel-position').isVisible(),true)
  await page.evaluate(slot=>pgTest.fillPlanogramForm(slot),fixture)
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.locator('#planogramModalBackdrop .modal').evaluate(n=>n.scrollWidth<=n.clientWidth+1),true,'mobile card fits viewport')
  await page.evaluate(()=>pgTest.closePlanogramModal())
  await page.locator('[data-planogram-view="layout"]').click()
  assert.equal(await page.locator('.cabinet-shell').evaluate(n=>n.scrollWidth<=n.clientWidth+1),true,'mobile rows do not overflow')
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:'/tmp/modern-planogram-desktop.png'})
  await page.evaluate(()=>{pgTest.fillCoffeeContainerForm({id:9,machine_id:58,container_code:'Z1',product_name:'Káva',unit:'g',capacity_quantity:3000,current_quantity:1500,refill_package_quantity:1000,refill_package_unit:'g'});pgTest.openPlanogramModal()})
  assert.equal(await page.locator('#slotContainerUnit').isVisible(),true)
  assert.equal((await page.evaluate(()=>pgTest.getCoffeeContainerPayload())).current_quantity,1500)
  assert.equal(await page.evaluate(slots=>pgTest.bulkPlanogramCandidates([...slots,{...slots[0],id:903,pending_product_sku:'NEXT'},{...slots[0],id:904,active:false}],'Bongo').length,slots),1,'bulk excludes planned, pending and inactive positions')
  assert.equal(await page.evaluate(slot=>pgTest.hasPlanogramChange({...slot,planned_product_name:slot.product_name,planned_product_sku:slot.product_sku,planned_price_czk:slot.price_czk}),fixture),false)
  assert.equal(await page.evaluate(slot=>pgTest.hasPlanogramChange({...slot,planned_product_name:slot.product_name,planned_product_sku:slot.product_sku,planned_price_czk:19}),fixture),true)
  assert.equal(await page.evaluate(()=>pgTest.getPlanogramStatus({current_units:13,capacity_units:13,fill_percent:0}).label),'OK')
  assert.equal(await page.evaluate(()=>pgTest.getPlanogramStatus({current_units:0,capacity_units:13,fill_percent:100}).label),'Doplnit')
  assert.equal(await page.evaluate(()=>pgTest.getPlanogramStatus({fill_percent:100}).label),'OK')
  assert.deepEqual(errors,[])
  console.log('PASS: real form payload preserved; price-only edit; native validation across tabs; planned-change navigation; mixed stock; coffee container; bulk eligibility; desktop/mobile layout.')
} finally { await browser.close() }
