import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import vm from 'node:vm'
const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const html = readFileSync(new URL('../machines.html', import.meta.url), 'utf8')
const ui = readFileSync(new URL('../machines-planogram-ui.js', import.meta.url), 'utf8').replaceAll('export function', 'function')
const script = html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace(/^\s*import .*$/gm, '').replace('    initializePage()', '')
new vm.Script(ui + script)
const fixture = { id:901, machine_id:58, slot_code:'25', product_name:'Bongo máta', product_sku:'SOCO-BONGO-MATA-40', product_family:'Bongo', product_variant:'Máta', price_czk:16, customer_price_czk:16, capacity_units:13, current_units:7, fill_percent:53.85, active:true, substitution_policy:'same_family', allowed_substitutes:'SKU SOCO-BONGO-MATA-40, SKU SOCO-BONGO-ORIGINAL-40', planned_product_name:null, planned_product_sku:null, note:'Zachovat poznámku', settlement_type:'subsidy_receivable', settlement_amount_czk:2, settlement_partner:'Škola', settlement_billing_enabled:true, settlement_note:'Smlouva' }
const machine = {id:58,name:'Aria L',machine_type:'snack',evidence_number:'78'}
const harness = html.replace(/<script[\s\S]*?<\/script>/g,'').replace('</body>', `<script type="module">${ui}\nconst supabase = {};\n${script}\nwindow.pgTest={fillPlanogramForm,openPlanogramModal,closePlanogramModal,getPlanogramPayload,fillCoffeeContainerForm,getCoffeeContainerPayload,bulkPlanogramCandidates,hasPlanogramChange,getPlanogramStatus,renderPlanogramCabinet, setSlots: slots => {planogramSlots=slots}, render: (slots,machine)=>{detailModalBody.innerHTML=renderPlanogramCabinet(slots,machine);detailModalBackdrop.classList.add('show')}};</script></body>`)
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE || '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'})
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}})
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.route('**/*',route=>{
    const url=new URL(route.request().url())
    if(url.pathname==='/machines.html')return route.fulfill({contentType:'text/html',body:harness})
    if(url.pathname==='/machines-planogram.css')return route.fulfill({contentType:'text/css',body:readFileSync(new URL('../machines-planogram.css',import.meta.url),'utf8')})
    return route.fulfill({status:404,body:''})
  })
  await page.goto('http://planogram.test/machines.html')
  await page.waitForFunction(()=>window.pgTest)
  const slots=[fixture,{...fixture,id:902,slot_code:'69',product_name:'Margot',planned_product_name:'RawBar',planned_product_sku:'SOCO-RAWBAR-APPLE',pending_change_mode:'full_swap',planned_price_czk:19,changeover_new_units:2,changeover_old_units:5}]
  await page.evaluate(({slots,machine})=>{pgTest.setSlots(slots);pgTest.render(slots,machine)}, {slots,machine})
  assert.equal(await page.locator('[data-slot-id="901"]').count(),1)
  assert.equal(await page.locator('[data-planogram-layout] [data-slot-id="902"]').count(),1)
  assert.match(await page.locator('[data-planogram-layout]').innerText(),/Aktuálně také: RawBar · 2 ks/)
  await page.locator('[data-planogram-view="changes"]').click()
  assert.equal(await page.locator('[data-planogram-layout]').isVisible(),false)
  await page.locator('[data-planogram-changes] [data-card-tab="plan"]').click()
  assert.equal(await page.locator('#planogram-panel-plan').isVisible(),true)
  await page.evaluate(()=>pgTest.closePlanogramModal())
  await page.evaluate(slot=>{pgTest.fillPlanogramForm(slot);pgTest.openPlanogramModal()},fixture)
  const before=await page.evaluate(()=>pgTest.getPlanogramPayload())
  for(const tab of ['replacements','plan','position'])await page.locator(`#planogramForm [data-card-tab="${tab}"]`).click()
  assert.deepEqual(await page.evaluate(()=>pgTest.getPlanogramPayload()),before,'tab navigation must preserve all saved values')
  assert.equal(before.allowed_substitutes,fixture.allowed_substitutes)
  assert.equal(before.settlement_amount_czk,2)
  assert.equal(before.current_units,7)
  assert.equal(await page.locator('#planogramForm [id]').evaluateAll(nodes=>new Set(nodes.map(n=>n.id)).size===nodes.length),true)
  await page.locator('#slotPrice').fill('17')
  const after=await page.evaluate(()=>pgTest.getPlanogramPayload())
  assert.deepEqual({...after,price_czk:before.price_czk},before,'price edit must preserve replacement lists, stock and finances')
  // Invalid required input in a hidden tab must be opened for native validation.
  await page.locator('#slotProductName').fill('')
  await page.locator('#planogramForm [data-card-tab="plan"]').click()
  await page.evaluate(()=>document.getElementById('planogramForm').reportValidity())
  assert.equal(await page.locator('#planogram-panel-position').isVisible(),true)
  await page.evaluate(slot=>pgTest.fillPlanogramForm(slot),fixture)
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.locator('#planogramModalBackdrop .modal').evaluate(n=>n.scrollWidth<=n.clientWidth+1),true,'mobile card fits viewport')
  await page.evaluate(()=>pgTest.closePlanogramModal())
  await page.locator('[data-planogram-view="layout"]').click()
  assert.equal(await page.locator('.cabinet-shell').evaluate(n=>n.scrollWidth<=n.clientWidth+1),true,'mobile rows do not overflow')
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:'/tmp/modern-planogram-desktop.png'})
  await page.evaluate(()=>{pgTest.fillCoffeeContainerForm({id:9,machine_id:58,container_code:'Z1',product_name:'Káva',unit:'g',capacity_quantity:3000,current_quantity:1500,refill_package_quantity:1000,refill_package_unit:'g'});pgTest.openPlanogramModal()})
  assert.equal(await page.locator('#slotContainerUnit').isVisible(),true)
  assert.equal((await page.evaluate(()=>pgTest.getCoffeeContainerPayload())).current_quantity,1500)
  assert.equal(await page.evaluate(slots=>pgTest.bulkPlanogramCandidates([...slots,{...slots[0],id:903,pending_product_sku:'NEXT'},{...slots[0],id:904,active:false}],'Bongo').length,slots),1,'bulk excludes planned, pending and inactive positions')
  assert.equal(await page.evaluate(slot=>pgTest.hasPlanogramChange({...slot,planned_product_name:slot.product_name,planned_product_sku:slot.product_sku,planned_price_czk:slot.price_czk}),fixture),false)
  assert.equal(await page.evaluate(slot=>pgTest.hasPlanogramChange({...slot,planned_product_name:slot.product_name,planned_product_sku:slot.product_sku,planned_price_czk:19}),fixture),true)
  assert.equal(await page.evaluate(()=>pgTest.getPlanogramStatus({current_units:13,capacity_units:13,fill_percent:0}).label),'OK')
  assert.equal(await page.evaluate(()=>pgTest.getPlanogramStatus({current_units:0,capacity_units:13,fill_percent:100}).label),'Doplnit')
  assert.equal(await page.evaluate(()=>pgTest.getPlanogramStatus({fill_percent:100}).label),'OK')
  await page.evaluate(({fixture,machine})=>{
    pgTest.closePlanogramModal()
    pgTest.render(Array.from({length:7},(_,i)=>({...fixture,id:910+i,slot_code:String(45+i),product_name:'Corny Big Tyčinka banány v mléčné čokoládě 50g',planned_product_name:'Corny Big Tyčinka banány v mléčné čokoládě velmi dlouhý název produktu',planned_product_sku:'OTHER'})),{...machine,name:'Europa Snack'})
  },{fixture,machine})
  for (const width of [1440,1024,390]) {
    await page.setViewportSize({width,height:1000})
    assert.equal(await page.locator('.cabinet-slot').evaluateAll(cards=>cards.every(card=>card.scrollWidth<=card.clientWidth+1)),true,`long product and planned replacement fit every card at ${width}px`)
  }
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:'/tmp/planogram-wrapping.png'})
  const visitsModule=readFileSync(new URL('../machine-visits.js',import.meta.url),'utf8').replaceAll('export function','function')
  await page.addScriptTag({content:`(()=>{${visitsModule};window.visitsTest={initMachineVisits,renderVisitDetails}})()`})
  await page.evaluate(async()=>{
    document.body.replaceChildren()
    const container=document.createElement('div');container.id='visits';document.body.append(container)
    window.visitQueries=[]
    const summaries=Array.from({length:6},(_,i)=>({id:i+1,employee_id:'operator1',route_plan_id:99,status:'completed',completed_at:'2026-09-13T10:00:00Z'}))
    const api={from(table){const query={table};const builder={select(value){query.select=value;return this},eq(key,value){query[key]=value;return this},order(){return this},range(from,to){query.range=[from,to];return this},in(){return this},single(){query.single=true;return this},then(resolve){window.visitQueries.push(query);return Promise.resolve(resolve({data:table==='employees'?[{id:'operator1',name:'Kristýna',surname:'Dvořáková'}]:query.single?{...summaries[0],operator_note:'<img src=x onerror=alert(1)>',route_machine_visit_items:[{id:11,physical_position_label:'25',actual_product_name:'Bongo',actual_before_quantity:0,actual_add_quantity:7,removed_quantity:0,final_quantity:7,unit:'ks'}],route_machine_cash_reports:[{operator_collected_confirmed:true,supervisor_counted_cash_czk:0}],route_machine_visit_checks:[{label:'Vyčistit',status:'completed'}]}:summaries.slice(query.range[0],query.range[1]+1),error:null}))}};return builder}}
    await visitsTest.initMachineVisits(container,api,58)
  })
  assert.equal(await page.locator('.machine-visit').count(),5)
  assert.equal(await page.evaluate(()=>visitQueries.some(q=>q.single)),false,'details are loaded only after expansion')
  await page.locator('.machine-visit summary').first().click()
  await page.waitForFunction(()=>document.querySelector('.machine-visit-body').textContent.includes('Doplněno: 7'))
  assert.match(await page.locator('.machine-visit-body').first().innerText(),/Před: 0 ks/)
  assert.equal(await page.locator('.machine-visit-body img').count(),0,'operator notes are text, not HTML')
  assert.equal(await page.locator('.machine-visit-body a').first().getAttribute('href'),'./routes-detail.html?id=99')
  await page.locator('.machine-visit summary').first().click()
  await page.locator('.machine-visit summary').first().click()
  assert.equal(await page.evaluate(()=>visitQueries.filter(q=>q.single).length),1,'reopening uses loaded visit')
  await page.locator('.machine-visits-more').click()
  await page.waitForFunction(()=>document.querySelectorAll('.machine-visit').length===6)
  assert.equal(await page.locator('.machine-visits-more').isVisible(),false)
  assert.equal(await page.evaluate(()=>visitQueries.filter(q=>q.table==='route_machine_visits').every(q=>q.machine_id===58)),true,'history and detail queries are scoped to this machine')
  assert.deepEqual(errors,[])
  console.log('PASS: real form payload preserved; price-only edit; native validation across tabs; planned-change navigation; mixed stock; coffee container; bulk eligibility; desktop/mobile layout.')
} finally { await browser.close() }
