// Run with PGLITE_MODULE pointing to @electric-sql/pglite, or install it locally.
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite')
const db = new PGlite()
await db.exec(`
  create role anon; create role authenticated;
  create schema auth;
  create function auth.uid() returns uuid language sql as
    $$ select nullif(current_setting('test.actor', true),'')::uuid $$;
  create table employees(id uuid primary key, auth_user_id uuid, role text, active boolean);
  create table vehicles(id bigint primary key, current_odometer_km integer, active boolean);
  create table attendance_days(id bigint primary key, employee_id uuid, attendance_date date,
    actual_start timestamptz, actual_end timestamptz, status text, vehicle_id bigint,
    break_minutes integer default 0, payable_minutes integer default 0);
  create table vehicle_operation_logs(id bigint generated by default as identity primary key,
    attendance_day_id bigint, employee_id uuid, vehicle_id bigint, log_date date,
    status text, started_at timestamptz, ended_at timestamptz, start_odometer_km integer,
    end_odometer_km integer, trip_note text,
    distance_km integer generated always as (end_odometer_km-start_odometer_km) stored);
  create table route_plans(id bigint primary key, planned_employee_id uuid, vehicle_id bigint,
    planning_date date, execution_status text, estimated_distance_km numeric);
  create table attendance_events(id bigint generated always as identity, attendance_day_id bigint,
    employee_id uuid, event_type text, event_time timestamptz, note text, created_by uuid);
  insert into employees values
    ('00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001','admin',true),
    ('00000000-0000-0000-0000-000000000002','10000000-0000-0000-0000-000000000002','operator',true);
  set test.actor = '10000000-0000-0000-0000-000000000001';
`)
await db.exec(await readFile(new URL('../database/switch_shift_vehicle_v48.sql', import.meta.url), 'utf8'))
const reset = async () => db.exec(`
  truncate attendance_events, vehicle_operation_logs restart identity;
  delete from attendance_days; delete from vehicles; delete from route_plans;
  set test.actor = '10000000-0000-0000-0000-000000000001';
  insert into vehicles values (1,115020,true),(2,152009,true);
  insert into attendance_days values (9,'00000000-0000-0000-0000-000000000002','2026-09-09',
    '2026-09-09 06:01+02',null,'open',1,17,0);
  insert into vehicle_operation_logs(attendance_day_id, employee_id, vehicle_id, log_date,
    status, started_at, start_odometer_km)
  values (9,'00000000-0000-0000-0000-000000000002',1,'2026-09-09','open','2026-09-09 06:01+02',115020);
  insert into route_plans values (96,'00000000-0000-0000-0000-000000000002',1,'2026-09-09','done',124.6);
`)
const run = (end = 115145, start = 152009, plan = 96) => db.query(
  'select switch_shift_vehicle_v48(9,1,2,$1,$2,$3,$4) as result', [end,start,plan,'Inventura'])
const snapshot = async () => {
  const result = []
  for (const table of ['vehicles','attendance_days','vehicle_operation_logs','attendance_events']) {
    result.push((await db.query(`select * from ${table} order by id`)).rows)
  }
  return result
}
await reset()
const before = (await db.query('select * from attendance_days')).rows[0]
await run()
const after = (await db.query('select * from attendance_days')).rows[0]
assert.deepEqual({ ...after, vehicle_id: before.vehicle_id }, before, 'Only vehicle assignment changes in attendance')
assert.equal(after.vehicle_id, 2)
const logs = (await db.query('select * from vehicle_operation_logs order by id')).rows
assert.equal(logs.length, 2)
assert.equal(logs[0].status, 'closed')
assert.equal(logs[0].distance_km, 125)
assert.match(logs[0].trip_note, /odhad podle plánu/)
assert.equal(logs[1].status, 'open')
assert.equal(logs[1].start_odometer_km, 152009)
assert.equal(logs[1].end_odometer_km, null)
assert.equal((await db.query('select count(*)::int as n from attendance_events')).rows[0].n, 1)
let saved = await snapshot()
await assert.rejects(run(), /uzavřen|změnil|jiné vozidlo/)
assert.deepEqual(await snapshot(), saved, 'Double submit cannot change mileage')
console.log('PASS: planned mileage, history, open shift, new log, audit and repeated submit')
const rejectedCases = [
  ['operator', "set test.actor = '10000000-0000-0000-0000-000000000002'", () => run(), /vedení/],
  ['anonymous', "set test.actor = ''", () => run(), /vedení/],
  ['closed shift', "update attendance_days set actual_end=now()", () => run(), /otevřená/],
  ['busy car', "insert into attendance_days values (10,null,'2026-09-09',now(),null,'open',2,0,0)", () => run(), /otevřený/],
  ['inactive car', 'update vehicles set active=false where id=2', () => run(), /aktivní/],
  ['lower new odometer', '', () => run(115145,152000), /Počáteční/],
  ['lower old odometer', '', () => run(115000,152009,null), /Konečné/],
  ['changed plan', 'update route_plans set estimated_distance_km=130', () => run(), /Plán km se změnil/],
  ['wrong route vehicle', 'update route_plans set vehicle_id=2', () => run(), /nepatří/],
  ['route in progress', "update route_plans set execution_status='in_progress'", () => run(), /dokonči/],
  ['saved end mismatch', 'update vehicle_operation_logs set end_odometer_km=115150', () => run(), /Konečné/],
  ['multiple trips', `insert into vehicle_operation_logs(attendance_day_id,employee_id,vehicle_id,log_date,status,start_odometer_km)
    values(9,'00000000-0000-0000-0000-000000000002',1,'2026-09-09','closed',115000)`, () => run(), /více jízd/]
]
for (const [name, setup, action, pattern] of rejectedCases) {
  await reset()
  if (setup) await db.exec(setup)
  saved = await snapshot()
  await assert.rejects(action(), pattern, name)
  assert.deepEqual(await snapshot(), saved, `${name}: no partial writes`)
  console.log(`PASS: rejects ${name} without partial writes`)
}
await reset()
await db.exec(`create function fail_event() returns trigger language plpgsql as $$
  begin raise exception 'test audit failure'; end $$;
  create trigger fail_event before insert on attendance_events for each row execute function fail_event();`)
saved = await snapshot()
await assert.rejects(run(), /test audit failure/)
assert.deepEqual(await snapshot(), saved, 'Final write failure rolls back all vehicle changes')
await db.exec('drop trigger fail_event on attendance_events')
await reset()
await run(115150,152009,null)
assert.equal((await db.query('select distance_km from vehicle_operation_logs where id=1')).rows[0].distance_km,130)
console.log('PASS: atomic rollback on final write failure and manual odometer')
await reset()
await db.exec(`
  insert into attendance_days values(10,null,'2026-09-09',now(),now(),'closed',2,0,0);
  insert into vehicle_operation_logs(attendance_day_id,vehicle_id,log_date,status,start_odometer_km)
    values(10,2,'2026-09-09','open',151569);
`)
await run()
assert.equal((await db.query('select vehicle_id from attendance_days where id=9')).rows[0].vehicle_id,2)
assert.equal((await db.query('select status from vehicle_operation_logs where attendance_day_id=10')).rows[0].status,'open')
console.log('PASS: stale log of a closed shift does not occupy vehicle and remains unchanged')
await reset()
await db.exec(`insert into vehicle_operation_logs(vehicle_id,log_date,status,start_odometer_km)
  values(2,'2026-09-09','open',152009)`)
saved = await snapshot()
await assert.rejects(run(), /otevřený/)
assert.deepEqual(await snapshot(), saved)
console.log('PASS: standalone open trip still blocks handover')
await db.close()
