import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../mobile.html',import.meta.url),'utf8');
const start=html.indexOf('    function foodMachinePriceConfirmationRequired(');
const end=html.indexOf('    function getFoodPlanogramChange(',start);
const context=vm.createContext({state:{products:[{id:1,sku:'OLD'},{id:2,sku:'SOCO-RAWBAR-PEANUTS'},{id:3,sku:'SOCO-RAWBAR-APPLE'}]}});
vm.runInContext(html.slice(start,end),context);
const requires=context.foodMachinePriceConfirmationRequired;
const slot={product_sku:'OLD'},change={priceChanged:true,productChanged:true,nextSku:'SOCO-RAWBAR-PEANUTS'};
assert.equal(requires(slot,change,[{productId:3,quantity:11}]),true,'approved apple replacement must show confirmation');
assert.equal(requires(slot,change,[{productId:2,quantity:11}]),true);
assert.equal(requires(slot,change,[{productId:1,quantity:11}]),false);
assert.equal(requires(slot,change,[{productId:3,quantity:0}]),false);
assert.equal(requires(slot,change,[{productId:3,quantity:0.4}]),false,'use same whole-unit normalization as save');
assert.equal(requires(slot,change,[{productId:1,quantity:0},{productId:3,quantity:11}]),true);
assert.equal(requires(slot,change,[{productId:1,quantity:1},{productId:3,quantity:11}]),false);
assert.equal(requires(slot,{priceChanged:true,productChanged:false},[]),true);
assert.equal(requires(slot,{...change,priceChanged:false},[{productId:3,quantity:11}]),false);
assert.equal(requires(slot,null,[{productId:3,quantity:11}]),false,'deferred swap');
assert.equal((html.match(/const requiresMachinePriceConfirmation = foodMachinePriceConfirmationRequired\(/g)||[]).length,2);
assert.ok(html.includes('const machinePriceChangeRequired = foodMachinePriceConfirmationRequired(slot, planogramChange, fillItems)'));
console.log('PASS: family replacement, original product, quantities, price-only change, deferred swap, both UI paths and saving share one condition.');
