import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002',C='00000000-0000-0000-0000-000000000003';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${A}');create function auth.uid() returns uuid language sql as $$select '${A}'::uuid$$;create function has_manager_access() returns boolean language sql as $$select coalesce(current_setting('test.manager',true),'yes')='yes'$$;create table employees(id uuid primary key,active boolean default true,role text default 'operator');insert into employees(id) values('${A}'),('${B}'),('${C}');create table locations(id bigint primary key,active boolean default true);insert into locations values(1,true),(2,true);create table machines(id bigint primary key,location_id bigint,active boolean);insert into machines values(1,1,true),(2,2,true);`);
const old=await readFile(new URL('../database/operator_territories_v30.sql',import.meta.url),'utf8');
await db.exec(old.slice(0,old.indexOf('\ninsert into public.operator_territory_assignments (',old.indexOf('grant select')))+'\ncommit;');
await db.exec(await readFile(new URL('../database/operator_territory_transfers_v51.sql',import.meta.url),'utf8'));
await db.exec(`select save_operator_territory_assignment(1,'${A}','${B}','location','{}',current_date-2,'initial');select save_operator_territory_assignment(2,'${A}',null,'machines','{2}',current_date-2,'initial');`);
const get=async (offset=0)=>(await db.query(`select * from get_operator_territories_v51(current_date+${offset}) order by location_id`)).rows;
const changes=rows=>rows.map(r=>({location_id:r.location_id,expected_owner_id:r.primary_employee_id,expected_updated_at:r.updated_at,target_employee_id:B}));
const save=async (rows,offset=1)=>db.query(`select transfer_operator_territories_v51($1,current_date+${offset},'test handover')`,[JSON.stringify(rows)]);
const baseline=await get();
await save(changes(baseline));
assert.equal((await get())[0].primary_employee_id,A);
let future=await get(1);assert.equal(future[0].primary_employee_id,B);assert.equal(future[0].backup_employee_id,null);assert.deepEqual(future[1].selected_machine_ids,[2]);
await assert.rejects(save(changes(baseline)),/mezitím/);
await assert.rejects(save(changes(future),0),/Vlastník|pozdější/);
let next=changes(future).map(r=>({...r,target_employee_id:C}));
await db.exec("set test.manager='no'");await assert.rejects(save(next,2),/vedení/);await db.exec("set test.manager='yes'");
await assert.rejects(save([next[0],next[0]],2),/vícekrát/);
await assert.rejects(save([next[0],{...next[1],expected_updated_at:'2000-01-01T00:00:00Z'}],2),/mezitím/);
assert.equal((await get(2))[0].primary_employee_id,B);
await save(next,2);
assert.equal((await get())[0].primary_employee_id,A);assert.equal((await get(1))[0].primary_employee_id,B);assert.equal((await get(2))[0].primary_employee_id,C);
console.log('PASS: future handover, historical ownership, scope, backup collision, concurrent edit rejection, permissions, duplicate rejection, atomic rollback, successive dates.');
await db.close();
