import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync('technician-mobile.html','utf8');
for(const match of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.SourceTextModule(match[1]);
const context=vm.createContext({Intl,Date,state:{employee:{id:'tech'},plan:[]},today:'2026-09-15'});
vm.runInContext(html.slice(html.indexOf('function serviceDone('),html.indexOf('function buildTasks(')),context);
const old={id:140,status:'assigned',assigned_employee_id:'tech',created_at:'2026-09-14T14:28:23Z',due_date:'2026-09-14'};
assert.equal(context.serviceBelongsToToday(old),true,'Yesterday’s open service remains visible');
assert.equal(context.serviceBelongsToToday({...old,due_date:null}),true);
assert.equal(context.serviceBelongsToToday({...old,due_date:'2026-09-16'}),false);
for(const status of ['done','cancelled','blocked'])assert.equal(context.serviceBelongsToToday({...old,status}),false);
assert.equal(context.serviceBelongsToToday({...old,assigned_employee_id:null}),false,'Do not import all historic unassigned work');
assert.equal(context.jobBelongsToToday({...old,planned_date:'2026-09-14'}),true);
assert.equal(context.jobBelongsToToday({...old,planned_date:'2026-09-16'}),false);
assert.equal(context.jobBelongsToToday({...old,status:'closed',planned_date:'2026-09-14'}),false);
const start=html.split('data-screen="start"')[1].split('</section>')[0];
assert.match(start,/data-nav="new-service"/);
const create=html.slice(html.indexOf('async function createService('),html.indexOf('function renderToday('));
assert.doesNotMatch(create,/startShift\(|from\('attendance/);
assert.doesNotMatch(create,/show\('today'\)/);
const elements=new Map();const element=key=>{if(!elements.has(key))elements.set(key,{classList:{toggle(){}},dataset:{}});return elements.get(key)};
const ui=vm.createContext({state:{attendance:null},$:element,$$:()=>[],window:{scrollTo(){}}});
vm.runInContext(html.slice(html.indexOf('function show(screen)'),html.indexOf('\n',html.indexOf('function show(screen)'))),ui);
ui.show('new-service');assert.equal(element('#headerTitle').textContent,'Nový servis');assert.equal(element('#nav').hidden,true);
ui.show('today');assert.equal(element('#headerTitle').textContent,'Zahájení směny');
console.log('PASS: overdue service/job visibility, terminal statuses, future scheduling, pre-shift creation/navigation, module syntax');
