process.on('uncaughtException', e => { console.error(e.message, e.detail || '', e.where || '', e.position || ''); process.exit(1) })
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite')
const db=new PGlite()
const file=p=>readFile(new URL('../'+p,import.meta.url),'utf8')
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create table employees(id uuid primary key,auth_user_id uuid,active boolean,role text);
create table products(id bigint primary key,name text,sku text,base_unit text,active boolean,product_category text);
create table stock_locations(id bigint primary key,name text,vehicle_id bigint,machine_id bigint,location_type text,active boolean);
create table inventory_batches(id bigint primary key,product_id bigint,best_before_date date,use_by_date date);
create table stock_location_balances(id bigint generated always as identity primary key,stock_location_id bigint,product_id bigint,batch_id bigint,quantity_on_hand numeric,reserved_quantity numeric default 0,updated_at timestamptz default now());
create table stock_movements_v13(id bigint generated always as identity primary key,product_id bigint,batch_id bigint,from_stock_location_id bigint,to_stock_location_id bigint,movement_type text,quantity_base_units numeric,unit_price numeric,reference_type text,reference_id text,note text);
create table route_plans(id bigint primary key);
create table route_plan_stops(id bigint primary key,arrived_at timestamptz,status text check(status in ('pending','arrived','done','skipped')),completed_at timestamptz,skipped_at timestamptz);
create table route_machine_visits(id bigint primary key,route_plan_id bigint,route_plan_stop_id bigint,machine_id bigint,vehicle_id bigint,visit_date date,status text,operator_note text,skip_reason text,arrived_at timestamptz,completed_at timestamptz,skipped_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now(),synced_at timestamptz);
create table route_machine_visit_items(id bigint primary key,visit_id bigint,item_kind text,planogram_slot_id bigint,coffee_container_id bigint,actual_product_id bigint,planned_product_id bigint,actual_product_sku text,actual_product_name text,sale_price_czk numeric,unit text,actual_before_quantity numeric,actual_add_quantity numeric,removed_quantity numeric,final_quantity numeric,capacity_quantity numeric,operator_note text,accepted_at timestamptz,updated_at timestamptz default now());
create table route_machine_visit_food_fills(id bigint generated by default as identity primary key,machine_id bigint,planogram_slot_id bigint,load_order integer default 0,visit_id bigint,visit_item_id bigint,product_id bigint,product_sku text,product_name text,quantity integer check(quantity>0),expiry_date date,sale_price_czk numeric,stock_reference_id text);
create table machine_planogram_slots(id bigint primary key,machine_id bigint,product_sku text,product_name text,current_units numeric,capacity_units numeric,target_units numeric,desired_units numeric,fill_percent numeric,expiry_date date,price_czk numeric,customer_price_czk numeric,pending_product_sku text,changeover_new_units numeric,updated_at timestamptz default now());
create table machine_coffee_containers(id bigint primary key,machine_id bigint,current_quantity numeric,capacity_quantity numeric,updated_at timestamptz default now());
create table inventory_audits(id bigint primary key,status text,closed_at timestamptz);
create table inventory_audit_items(id bigint primary key,audit_id bigint,product_id bigint,stock_location_id bigint);
create table route_vehicle_waste_items(id bigint primary key,route_machine_visit_id bigint,route_machine_visit_item_id bigint,status text,product_id bigint,unit text,quantity numeric,reason text check(reason in ('expired','shaken','damaged','opened','other')),note text,updated_at timestamptz);
create table route_machine_visit_checks(id bigint,visit_id bigint);
create table route_machine_cash_reports(id bigint generated always as identity primary key,visit_id bigint unique,machine_id bigint,operator_collected_confirmed boolean,operator_bag_label text,supervisor_counted_cash_czk numeric,supervisor_counted_by uuid,supervisor_counted_at timestamptz,note text,updated_at timestamptz default now());
insert into employees values('00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',true,'admin');
set test.actor='10000000-0000-0000-0000-000000000001';`)
await db.exec(await file('database/stock_movements_readable_insufficient_stock_20260529.sql'))
await db.exec(await file('database/route_visit_corrections_v50.sql'))
const reset=async()=>db.exec(`
set olvend.route_correction='on';
truncate route_vehicle_waste_items,route_visit_corrections,route_machine_visit_food_fills,route_machine_visit_items,route_machine_visits,stock_movements_v13,stock_location_balances,route_machine_cash_reports restart identity cascade;
delete from inventory_audit_items;delete from inventory_audits;delete from machine_planogram_slots;delete from machine_coffee_containers;delete from products;delete from inventory_batches;delete from stock_locations;delete from route_plan_stops;
insert into products values(1,'Původní','OLD','ks',true,'snack_ready'),(2,'Nový','NEW','ks',true,'snack_ready'),(3,'Káva','COF','kg',true,'ingredient');
insert into inventory_batches values(11,1,'2027-01-09',null),(22,2,'2027-02-10',null),(33,3,'2027-02-01',null);
insert into stock_locations values(1,'Auto',1,null,'vehicle',true),(2,'Automat',null,1,'machine',true);
insert into stock_location_balances(stock_location_id,product_id,batch_id,quantity_on_hand) values(1,1,11,20),(2,1,11,10),(1,2,22,20),(2,2,22,0),(1,3,33,3),(2,3,33,1);
insert into route_plan_stops(id,status,completed_at,skipped_at) values(1,'done',now(),null);
insert into route_machine_visits(id,route_plan_id,route_plan_stop_id,machine_id,vehicle_id,visit_date,status,arrived_at,completed_at,created_at,updated_at) values(1,1,1,1,1,'2026-09-09','completed','2026-09-09 08:00Z','2026-09-09 08:10Z','2026-09-09 08:00Z','2026-09-09 08:10Z');
insert into route_machine_visit_items(id,visit_id,item_kind,planogram_slot_id,actual_product_id,planned_product_id,unit,actual_before_quantity,actual_add_quantity,removed_quantity,final_quantity,capacity_quantity,accepted_at) values(1,1,'food_slot',1,1,1,'ks',0,10,0,10,15,'2026-09-09 08:09Z');
insert into route_machine_visit_food_fills(id,visit_id,visit_item_id,product_id,product_sku,product_name,quantity,expiry_date,sale_price_czk,stock_reference_id) values(1,1,1,1,'OLD','Původní',10,'2027-01-09',25,'route_visit_1_food_slot_1_fill_0_1');
insert into stock_movements_v13(product_id,batch_id,from_stock_location_id,to_stock_location_id,movement_type,quantity_base_units,reference_id) values(1,11,1,2,'fill_machine',10,'route_visit_1_food_slot_1_fill_0_1');
insert into machine_planogram_slots(id,machine_id,product_sku,current_units,capacity_units,target_units) values(1,1,'OLD',10,15,15);
set olvend.route_correction='off';set test.actor='10000000-0000-0000-0000-000000000001';`)
const one=async(sql,args=[])=>(await db.query(sql,args)).rows[0]
const patch=(q=6,product=1)=>({items:[{id:1,capacity:15,note:'Opraveno',fills:[{id:1,product_id:product,quantity:q,batch_id:product===1?11:22,expiry:product===1?'2027-01-09':'2027-02-10',price:25}]}]})
const apply=async(p,expected)=>{const v=expected||await one('select * from route_machine_visits where id=1');return one('select correct_route_visit_v50(1,$1,$2,$3,$4) result',[v.correction_revision,v.updated_at,'Operátor potvrdil skutečnost',JSON.stringify(p)])}
const qty=async(loc,prod=1)=>(await one('select sum(quantity_on_hand)::float q from stock_location_balances where stock_location_id=$1 and product_id=$2',[loc,prod])).q
await reset();const old=await one('select * from route_machine_visits where id=1');await apply(patch());assert.equal(await qty(1),24);assert.equal(await qty(2),6);assert.equal((await one('select current_units::float q from machine_planogram_slots')).q,6)
await assert.rejects(()=>apply(patch(),old),/mezitím/)
await apply(patch(8));assert.equal(await qty(1),22);assert.equal(await qty(2),8)
await assert.rejects(()=>db.exec("update route_machine_visit_items set actual_add_quantity=10 where id=1"),/vedení/)
await assert.rejects(()=>db.exec("insert into stock_movements_v13(reference_id) values('route_visit_1_food_slot_1_fill_0_1')"),/vedení/)
await reset();await apply(patch(5,2));assert.equal(await qty(1),30);assert.equal(await qty(2),0);assert.equal(await qty(1,2),15);assert.equal(await qty(2,2),5)
await reset();await assert.rejects(()=>apply(patch(99)),/Nedostatek|kapacitu/);assert.equal(await qty(1),20);assert.equal((await one('select count(*)::int n from route_visit_corrections')).n,0)
await reset();await db.exec("insert into inventory_audits values(1,'closed','2026-09-09 09:00Z');insert into inventory_audit_items values(1,1,1,1)");await assert.rejects(()=>apply(patch()),/inventura/)
await reset();await db.exec("set test.actor='10000000-0000-0000-0000-000000000099'");await assert.rejects(()=>apply(patch()),/vedení/)
await reset();const duplicate=patch();duplicate.items[0].fills.push({...duplicate.items[0].fills[0]});await assert.rejects(()=>apply(duplicate),/Seznam|Duplicitní/)
await reset();await apply({cash:{collected:true,bag:'Sáček 17',counted:'123.50',note:'Přepočet'},note:'Potvrzeno'});assert.equal((await one('select supervisor_counted_cash_czk::float q from route_machine_cash_reports')).q,123.5)
await reset();await assert.rejects(()=>apply({status:'skipped'}),/doplnění/)
await reset();await db.exec("set olvend.route_correction='on';insert into route_machine_visit_items(id,visit_id,item_kind,coffee_container_id,actual_product_id,planned_product_id,unit,actual_before_quantity,actual_add_quantity,removed_quantity,final_quantity,capacity_quantity,accepted_at) values(2,1,'coffee_container',2,3,3,'g',0,1000,0,1000,3000,'2026-09-09 08:09Z');insert into machine_coffee_containers(id,machine_id,current_quantity,capacity_quantity)values(2,1,1000,3000);insert into stock_movements_v13(product_id,batch_id,from_stock_location_id,to_stock_location_id,quantity_base_units,reference_id) values(3,33,1,2,1,'route_visit_1_container_2');set olvend.route_correction='off'");await apply({items:[{id:2,capacity:3000,added:500,note:'Půl kg'}]});assert.equal(await qty(1,3),3.5);assert.equal(await qty(2,3),.5)
await reset();const beforePatch=patch(10);beforePatch.items[0].before=2;await apply(beforePatch);assert.equal(await qty(2),12);assert.equal((await one('select final_quantity::float q from route_machine_visit_items where id=1')).q,12)
await reset();await db.exec("insert into route_vehicle_waste_items values(50,1,1,'pending',1,'ks',2,'expired','',now());set olvend.route_correction='on';update route_machine_visit_items set actual_before_quantity=2,removed_quantity=2 where id=1;set olvend.route_correction='off'");await apply({wastes:[{id:50,quantity:1,reason:'damaged'}]});assert.equal(await qty(2),11);assert.equal((await one('select removed_quantity::float q from route_machine_visit_items where id=1')).q,1)
await reset();await db.exec("set olvend.route_correction='on';delete from route_machine_visit_food_fills;update route_machine_visit_items set actual_add_quantity=0,final_quantity=0 where id=1;update machine_planogram_slots set current_units=0;update stock_location_balances set quantity_on_hand=0 where stock_location_id=2 and product_id=1;set olvend.route_correction='off'");const addPatch=patch(4);addPatch.items[0].fills[0].id=-1;await apply(addPatch);assert.equal(await qty(2),4);
console.log('Route corrections: stock conservation, repeat edits, stale writes, substitutions, rollback, audit guards, roles, cash and kg/g passed.')
await db.close()
